### ISSUE TITLE
get postal code suffix 

### ISSUE THREAD

**Issue by faliendres** [geocoder-php/Geocoder#1006]
i'm using google maps but i do not can get postal code suffix  or ZIP+4

**Comment by atymic** [comment]
Can you provide the code you are using, the address and a `var_dump` of the result object please?

**Comment by faliendres** [comment]
$addresses = $geocoder->geocode('9406 marshall rd Eden Prairie MN 55347');

$response:

**Comment by atymic** [comment]
I checked the [actual response](https://gist.github.com/atymic/2fa7d0cf921e8b38f995f4bf8edc8612) from the google maps API and it doesn't contain a `postalCodeSuffix`.

**Comment by atymic** [comment]
As far as I can tell, google maps does not return a `postalCodeSuffix`

https://developers.google.com/maps/documentation/geocoding/intro#Types

**Comment by atymic** [comment]
@faliendres 

Did you see my response above?

**Comment by atymic** [comment]
Ok, got it :)

I'll open a PR to fix that.

**Comment by atymic** [comment]
@faliendres 
PR is open in #1008  😄
