### ISSUE TITLE
Have pelias provider in packagist

### ISSUE THREAD

**Issue by gaelg** [geocoder-php/Geocoder#1012]
Hi and thank you for this great lib!
I've seen that a pelias provider has been added (https://github.com/geocoder-php/Geocoder/pull/1004), but I cannot find it in packagist: https://packagist.org/providers/geocoder-php/provider-implementation
Could you please release it?

**Comment by gaelg** [comment]
Thank you for your answer. In the meanwhile, is it possible to get it with some composer trick?

**Comment by Nyholm** [comment]
Sorry for keeping you waiting. I’ll do this today. Hopefully within the next hour.

**Comment by gaelg** [comment]
It's OK. Thank you!

**Comment by gaelg** [comment]
This message is a gentle reminder. ;)

**Comment by jbelien** [comment]
Sub-package is created: https://github.com/geocoder-php/pelias-provider ! 🎉 
I'm just waiting to have access to the release creation and the new package will be live!

**Comment by Nyholm** [comment]
So, This is what I did: 

1. Added the new repo
2. Configured subtree split
3. Pushed to the provider in main repo to trigger split https://github.com/geocoder-php/Geocoder/pull/1017
4. Added packagist
5. Added Travis
6. Added scrutnizer
7. Added the repo to the "Release manager"-(Github) team

**Comment by gaelg** [comment]
I confirm I could get it with composer require. Thanks to both of you!
