### ISSUE TITLE
API access denied.

### ISSUE THREAD

**Issue by klikpaspor** [geocoder-php/Geocoder#1028]
` Message: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account`

```
use Geocoder\Query\GeocodeQuery;
use Geocoder\Query\ReverseQuery;

$httpClient = new \Http\Adapter\Guzzle6\Client();
$provider = new \Geocoder\Provider\GoogleMaps\GoogleMaps($httpClient);
$geocoder = new \Geocoder\StatefulGeocoder($provider, 'en');

$result = $geocoder->geocodeQuery(GeocodeQuery::create('Buckingham Palace, London'));
$result = $geocoder->reverseQuery(ReverseQuery::fromCoordinates(...));
```
API access denied.

**Comment by atymic** [comment]
As per the link in the error, you need to use an API key.

https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/GoogleMaps/GoogleMaps.php#L82-L89

We should probably clarify this is the docs, though.

**Comment by klikpaspor** [comment]
version 3.x no need an Api key right? or Google has updated?

**Comment by atymic** [comment]
Sorry about the accidental close. 
PR to update the docs here: https://github.com/geocoder-php/Geocoder/pull/1030
