### ISSUE TITLE
Add IP2Location as IP provider

### ISSUE THREAD

**Issue by ip2location** [geocoder-php/Geocoder#1029]
We would like to add our IP2Location service as the IP provider. May I know how can we proceed from here?

**Comment by atymic** [comment]
I'm not sure that we have specific documentation, but roughly:

- Copy/paste an existing similar provider
- Update the provider logic for the new provider
- Write tests
- Add documentation
- PR for review

**Comment by ip2location** [comment]
Thanks for fast reply. We will work on this and will send the pull request when ready.

**Comment by atymic** [comment]
No worries.
