### ISSUE TITLE
How to limit API calls per second

### ISSUE THREAD

**Issue by tmp-hallenser** [geocoder-php/Geocoder#1035]
Hi,

I want to use the Nominatim API to do some geocoding. According to the Usage Policy, one is allowed to do max. 1 request per second. 

Since several calls will be identical, I'm using the Cache provider to reduce the number of calls. 

Is there a smart way to achieve the 1 request per second restriction in case of caching?

I could of course just pause for 1s after each query. This is a bit suboptimal since it unnecessarily slows down cached queries.

Many thanks!

**Comment by atymic** [comment]
I think the easiest way to do this would be to using some kind of middleware in the HTTP layer.
You could write a HTTplug plugin, but if you're using guzzle there's a preexisting plugin: 
https://github.com/hamburgscleanest/guzzle-advanced-throttle

Maybe give that a go?

**Comment by tmp-hallenser** [comment]
Thanks. Here's a working example using https://github.com/spatie/guzzle-rate-limiter-middleware

It combines caching with rate limiting, i.e. limits calls to API but first checks the cache.

Perhaps it's worth adding a comment to the readme.

```
<?php
// https://github.com/spatie/guzzle-rate-limiter-middleware
require __DIR__ . '/vendor/autoload.php';

$stack = \GuzzleHttp\HandlerStack::create();
$stack->push(\Spatie\GuzzleRateLimiterMiddleware\RateLimiterMiddleware::perMinute(1));

$httpClient = new \GuzzleHttp\Client(['handler' => $stack, 'timeout' => 30.0, ]);
$httpAdapter = new \Http\Adapter\Guzzle6\Client($httpClient);
$psr6Cache = new \Cache\Adapter\PHPArray\ArrayCachePool();
$provider = new \Geocoder\Provider\Nominatim\Nominatim($httpAdapter, 'https://nominatim.openstreetmap.org', 'Geocoder test');
$cachedProvider = new \Geocoder\Provider\Cache\ProviderCache($provider, $psr6Cache);
$geocoder = new \Geocoder\StatefulGeocoder($cachedProvider, 'en');
$formatter = new \Geocoder\Formatter\StringFormatter();

$gps_coords = array(
    array(
        'lat' => 52.516275,
        'lgn' => 13.377704
    ) ,
    array(
        'lat' => 51.503396,
        'lgn' => - 0.12764
    ) ,
    array(
        'lat' => 52.516275,
        'lgn' => 13.377704
    )
);
foreach ($gps_coords as $gps_coord)
{
    $result_list = $geocoder->reverseQuery(\Geocoder\Query\ReverseQuery::fromCoordinates($gps_coord['lat'], $gps_coord['lgn']));
    $result = $result_list->first();
    echo $formatter->format($result, '%S %n, %z %L') . PHP_EOL;

}

```
