### ISSUE TITLE
Here Provider now uses an API Key for REST

### ISSUE THREAD

**Issue by kenton-r** [geocoder-php/Geocoder#1041]
Would it be possible to get support for the API KEY authentication in the Here provider? It uses a different URL and only needs the API KEY attribute.

**Comment by jbelien** [comment]
Hello @kenton-r ,

Could you give a bit more information about the API KEY authentication ?

**Comment by kenton-r** [comment]
There are two ways of authenticating with HERE. If you use a none freemium SDK for a mobile app than there is still an App_ID and App_Code, but they have moved their REST API to an API KEY.

An example is:
https://geocoder.ls.hereapi.com/6.2/geocode.json
?apiKey={YOUR_API_KEY}
&searchtext=425+W+Randolph+Chicago

Note that this is a new URL and CIT address.

**Comment by jbelien** [comment]
Interesting!
Yes, it would definitely be possible to update Here Provider to allow request with the API Key !
Thanks for the notice !

Would you have time to submit a PR ?

**Comment by atymic** [comment]
PR opened here 🎉 
https://github.com/geocoder-php/Geocoder/pull/1042

**Comment by jbelien** [comment]
Version `0.5.0` is [released](https://packagist.org/packages/geocoder-php/here-provider).
