### ISSUE TITLE
[Pelias] Notice: Trying to access array offset on value of type null on php 7.4

### ISSUE THREAD

**Issue by kmadenski** [geocoder-php/Geocoder#1043]
Hi
Got error on **php 7.4** 
**Notice: Trying to access array offset on value of type null on php**

in vendor/willdurand/geocoder/Model/Address.php (line 258)

**Comment by atymic** [comment]
Can you post the stack trace please? It's not clear which provider you are using.

**Comment by kmadenski** [comment]
Sure. Sorry
The bug is from https://github.com/geocoder-php/pelias-provider/blob/master/Pelias.php
The bug coming from (line 181) **Address::createFromArray**

**Comment by jbelien** [comment]
Could you also provide us the address you were looking for and/or the response ?

**Comment by jbelien** [comment]
Okay, found where the issue is !
I set `$bound = null;` if there is no `bbox` properties in the response (see [Pelias.php#L169](https://github.com/geocoder-php/pelias-provider/blob/master/Pelias.php#L169) and `$bounds` should be an array !

Thanks for the notice @kmadenski , I'll fix it ASAP !

**Comment by jbelien** [comment]
@kmadenski Could you provide us the address that generated the error ? So I can add a new test for that case.

**Comment by kmadenski** [comment]
https://gist.github.com/kmadenski/421fe8f97ae6e64000238aa37a3e51fd its json response from ->getUrlContents($url)
https://gist.github.com/kmadenski/2fa613eaa75d0571e2d65cad5b96964e its param of Address::createFromArray

gettype($bounds) give a NULL

**Comment by jbelien** [comment]
Sorry for the (really) late reply !

I'm adding a test for `dworzec centralny` but I don't have a GeocodeEarth API key.
I requested an API key but in case I don't receive one. Could you provide the cached response for `dworzec centralny` search.

Thanks !
