### ISSUE TITLE
count PHP errors

### ISSUE THREAD

**Issue by dereuromark** [geocoder-php/Geocoder#1049]
> count(): Parameter must be an array or an object that implements Countable

```php
$result = $this->geocoder->geocode('10178 Berlin, Deutschland');
$this->assertSame(1, $result->count());
```

count() uses internally

    return count($this->locations);

Which then operations apparently on a non-valid type in some cases.

  - Installing geocoder-php/common-http (4.2.0): Downloading (100%)         
  - Installing geocoder-php/google-maps-provider (4.4.0): Downloading (100%)

**Comment by dereuromark** [comment]
PHP 74 is missing the test travis matrix it seems, but this particular issue might also be on our side at this time.

**Comment by dereuromark** [comment]
Actually, the issue is that

    array_values($locations);

on an empty array returns null, which then triggers this

I recommend properly checking the return value here:

    $this->locations = array_values($locations) ?? [];

or alike

**Comment by jbelien** [comment]
Thanks @dereuromark , I'll have a look !

**Comment by dereuromark** [comment]
I understand that passing empty array is a rare case, still not sure why it happened for us.
But in that case having this kind of solution here helps to fix the edge case :)

**Comment by jbelien** [comment]
I gave it a deeper look and here is the `AddressCollection` constructor:
```php
    public function __construct(array $locations = [])
    {
        $this->locations = array_values($locations);
    }
```
Since `$locations` is typed as an array, there is no issue to use `array_values()`.
Also, `AddressCollection` implements `Collection` that extends `Countable`.

---

Could you give a bit more of context about your issue ?
Do you still have this issue ?
What provider do you use ?
What PHP version do you use ?

Thanks!

**Comment by dereuromark** [comment]
Yeah, after over a year I am now also not sure anymore.
I will then just close this now.
