### ISSUE TITLE
Compatibility with CakePHP

### ISSUE THREAD

**Issue by dereuromark** [geocoder-php/Geocoder#1050]
https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php

This one is installed along the original repo, together with https://github.com/php-http/cakephp-adapter:cake4 branch

The AbstractHttpProvider is

    public function __construct(HttpClient $client, MessageFactory $factory = null)

But the GoogleMaps extends AbstractHttpProvider implements Provider:

    /**
     * @param HttpClient $client An HTTP adapter
     * @param string     $region Region biasing (optional)
     * @param string     $apiKey Google Geocoding API key (optional)
     */
    public function __construct(HttpClient $client, string $region = null, string $apiKey = null)
    {
        parent::__construct($client);

        $this->region = $region;
        $this->apiKey = $apiKey;
    }

This way, the provided factory is never used, resulting in errors:

    $adapter = new $adapterClass(new \Cake\Http\Client(), new \Geo\Geocoder\ResponseFactory());

> Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors

If those versions are not compatible composer should probably outline a conflict of sorts.
Best to fix this though to be compatible with the interface and thus contracting of these classes.

Composer:

  - Installing willdurand/geocoder (4.2.2): Loading from cache
  - Installing php-http/discovery (1.7.4): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-server-handler (1.0.1): Loading from cache
  - Installing psr/http-server-middleware (1.0.1): Loading from cache
  - Installing psr/http-client (1.0.0): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing laminas/laminas-zendframework-bridge (1.0.1): Loading from cache
  - Installing laminas/laminas-diactoros (2.2.2): Loading from cache
  - Installing laminas/laminas-httphandlerrunner (1.1.0): Loading from cache
  - Installing composer/ca-bundle (1.2.6): Loading from cache
  - Installing cakephp/chronos (2.0.2): Loading from cache
  - Installing aura/intl (3.0.0): Loading from cache
  - Installing cakephp/cakephp (4.0.4): Downloading (100%)         
  - Installing php-http/promise (v1.0.0): Loading from cache
  - Installing php-http/httplug (v1.1.0): Loading from cache
  - Installing php-http/cakephp-adapter (dev-cake4 daff520): Cloning daff520d32 from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing geocoder-php/common-http (4.2.0): Loading from cache
  - Installing geocoder-php/google-maps-provider (4.4.0): Loading from cache

**Comment by jbelien** [comment]
Hello @dereuromark ,

I'm not sure I understand the issue here.
You're trying to use our Google Maps provider with Cake PHP HTTP Client (instead of Guzzle, for instance) and it doesn't work, is that it ?

---

What is your `$adapterClass` variable ?
What is the `\Geo\Geocoder\ResponseFactory` class ?

**Comment by dereuromark** [comment]
$adapterClass = $this->getConfig('adapter');

So `Http\Adapter\Cake\Client` as per linked repo, implements HttpClient (as per psr7).

```php
namespace Geo\Geocoder;

use Cake\Http\Client\Response;
use Http\Message\ResponseFactory as ResponseFactoryInterface;

class ResponseFactory implements ResponseFactoryInterface {

	/**
	 * @inheritDoc
	 */
	public function createResponse($statusCode = 200, $reasonPhrase = null, array $headers = [], $body = null, $protocolVersion = '1.1') {
		return new Response($headers, (string)$body);
	}

}
```

This should all work if the GoogleMaps class would follow the spec of the interface, `HttpClient $client, MessageFactory $factory = null)`

**Comment by jbelien** [comment]
@Nyholm Any idea ?

**Comment by dereuromark** [comment]
I now managed in my PR to get it working.
What is quite annoying is the overuse of final and private, making it hard to extend at least somehow without having to copy over complete classes.
But fair enough for the time being. Closing then.
