### ISSUE TITLE
HostIP no longer supplies lat,lng in JSON

### ISSUE THREAD

**Issue by oleg-andreyev** [geocoder-php/Geocoder#1056]
It's probably due that MaxMind commercialized it or  due to GDPR
http://api.hostip.info/get_json.php
but XML still has it http://api.hostip.info/get_xml.php

**Comment by jbelien** [comment]
http://api.hostip.info/get_xml.php doesn't seem to provide coordinates either.
```xml
<!-- Co-ordinates are unavailable -->
```

Could you provide some documentation about this change in the API ?

**Comment by oleg-andreyev** [comment]
@jbelien it does provide in some cases :/
![image](https://user-images.githubusercontent.com/1244112/80388521-a9a5e800-88b2-11ea-9aa1-b89532d472e6.png)

The only issue I have locally it's `Notice: Undefined index: lat`
