### ISSUE TITLE
[Nominatim] no category in place object

### ISSUE THREAD

**Issue by Sandman83** [geocoder-php/Geocoder#1061]
I'm trying out the geocoder via

`"toin0u/geocoder-laravel": "^4.3" `

The example of interest is:
https://github.com/geocoder-php/Geocoder#usage

together with the Nominatim-provider. 

In line 243 of `vendor/geocoder-php/nominatim-provider/Nominatim.php`

I get the error

`ErrorException : Undefined property: stdClass::$category`

as the place does have a type but does not have a category.

**Comment by Sandman83** [comment]
Sure. For example, let's look out for 
'Johanneskirchner Str. 98, 81927 Munich, Germany'

via* 

`https://nominatim.openstreetmap.org/search?format=json&limit=1/search?format=jsonv2&q=Johanneskirchner+Straße+98%2C+81927+München%2C+Germany&addressdetails=1&limit=5`

and receive* 

`[{"place_id":918741,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":289551153,"boundingbox":["48.1673541","48.1674541","11.642958","11.643058"],"lat":"48.1674041","lon":"11.643008","display_name":"Stadtsparkasse Johanneskirchen, 98, Johanneskirchner Straße, Gartenstadt Johanneskirchen, Bezirksteil Johanneskirchen, Stadtbezirk 13 Bogenhausen, München, Bayern, 81927, Deutschland","class":"amenity","type":"bank","importance":0.5309999999999999,"icon":"https://nominatim.openstreetmap.org/images/mapicons/money_bank2.p.20.png","address":{"amenity":"Stadtsparkasse Johanneskirchen","house_number":"98","road":"Johanneskirchner Straße","neighbourhood":"Gartenstadt Johanneskirchen","suburb":"Bezirksteil Johanneskirchen","city_district":"Stadtbezirk 13 Bogenhausen","city":"München","state":"Bayern","postcode":"81927","country":"Deutschland","country_code":"de"}},{"place_id":19834805,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":2016819624,"boundingbox":["48.1674814","48.1675814","11.6430121","11.6431121"],"lat":"48.1675314","lon":"11.6430621","display_name":"98, Johanneskirchner Straße, Gartenstadt Johanneskirchen, Bezirksteil Johanneskirchen, Stadtbezirk 13 Bogenhausen, München, Bayern, 81927, Deutschland","class":"place","type":"house","importance":0.5309999999999999,"address":{"house_number":"98","road":"Johanneskirchner Straße","neighbourhood":"Gartenstadt Johanneskirchen","suburb":"Bezirksteil Johanneskirchen","city_district":"Stadtbezirk 13 Bogenhausen","city":"München","state":"Bayern","postcode":"81927","country":"Deutschland","country_code":"de"}}]`

I have to add, that the starred things are from the description of Nominatim-API description in order to debug the provider code. So... my test case code is

```
$adapter  = new \Http\Client\Curl\Client(null, null);
$rootUrl = 'https://nominatim.openstreetmap.org/search?format=json&limit=1';
$userAgent = 'sascha.orlov@gmail.com';
$geocoder = new Nominatim($adapter, $rootUrl, $userAgent);
$address_to_search = 'Johanneskirchner Str. 98, 81927 Munich, Germany';
$result = $geocoder->geocodeQuery(GeocodeQuery::create($address_to_search))->first();
```

**Comment by jbelien** [comment]
The URL you provide is "strange", you specify twice the format and the limit.
`https://nominatim.openstreetmap.org/search?format=json&limit=1/search?format=jsonv2&q=Johanneskirchner+Straße+98%2C+81927+München%2C+Germany&addressdetails=1&limit=5`

Our Nominatim provider uses `format=jsonv2` !
The `category` property is defined for the search on `Johanneskirchner Str. 98, 81927 Munich, Germany` : 
https://nominatim.openstreetmap.org/search?format=jsonv2&q=Johanneskirchner+Stra%C3%9Fe+98%2C+81927+M%C3%BCnchen%2C+Germany&addressdetails=1&limit=5

What address did you look for that didn't return a `category` property ?

**Comment by Sandman83** [comment]
Its here, in the second line. https://github.com/geocoder-php/Geocoder/issues/1061#issuecomment-640423646

'Johanneskirchner Str. 98, 81927 Munich, Germany'

**Comment by jbelien** [comment]
The [search](https://nominatim.openstreetmap.org/search?format=jsonv2&q=Johanneskirchner+Stra%C3%9Fe+98%2C+81927+M%C3%BCnchen%2C+Germany&addressdetails=1&limit=5) for `Johanneskirchner Str. 98, 81927 Munich, Germany` returns a `category` property !

As I said, your URL is wrong, and the format used is `jsonv2` (**not** `json`).

You don't have to specify the `$rootURL` if you want to use the "default" Nominatim server. Just use `Nominatim::withOpenStreetMapServer()` function.
If you want to specify the `$rootURL`, you only have to specify the root URL (**without** any parameters and **without** the `/search` path). In this case, just `https://nominatim.openstreetmap.org`.

I'll update the README to make it more clear !

**Comment by Sandman83** [comment]
The URL does not really matter. Look at my test code at the end of https://github.com/geocoder-php/Geocoder/issues/1061#issuecomment-640423646

```
$adapter  = new \Http\Client\Curl\Client(null, null);
$rootUrl = 'https://nominatim.openstreetmap.org/search?format=json&limit=1';
$userAgent = 'sascha.orlov@gmail.com';
$geocoder = new Nominatim($adapter, $rootUrl, $userAgent);
$address_to_search = 'Johanneskirchner Str. 98, 81927 Munich, Germany';
$result = $geocoder->geocodeQuery(GeocodeQuery::create($address_to_search))->first();
```

I tried to follow the example in your docu. If this code is ok, then the provider has a bug.

**Comment by jbelien** [comment]
This code is **not** ok.
You provide a **wrong** `$rootUrl` !

I've updated the README: https://github.com/geocoder-php/nominatim-provider#readme

**Comment by Sandman83** [comment]
Ah! got it! Thanks a lot.
