### ISSUE TITLE
Google Maps Places reverse lookup: without `type`, `keyword`, `name`

### ISSUE THREAD

**Issue by wivaku** [geocoder-php/Geocoder#1063]
[Geocoder provider documentation](https://geocoder-php.org/docs/providers/googlemapsplaces/) says one of these is required: `type`, `keyword`, `name`.

[Google Maps Places documentation](https://developers.google.com/places/web-service/search#PlaceSearchRequests) shows these are optional parameters.

How do I search for any Place near a certain lat,lon?

**Comment by jbelien** [comment]
Indeed, you seem to be right !
Maybe there were required back when we released our Google Maps Places provider.

I guess @atymic will know more about it since he/she developed the provider back in August 2019.

**Comment by wivaku** [comment]
For [buildNearbySearchQuery()](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/GoogleMapsPlaces/GoogleMapsPlaces.php#L213) it seems it is hardcoded that `rankby:distance` is used (in which case indeed keyword/name/type are required).

Would prefer (in fact, just like the API: as default) to use `range=<meters>` and the (default)  `rankby=prominence`.

And related:

For [reverseQuery()](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/GoogleMapsPlaces/GoogleMapsPlaces.php#L123) I would expect it would use `NEARBY_ENDPOINT_URL_SSL` instead of `SEARCH_ENDPOINT_URL_SSL`.

**Comment by jbelien** [comment]
Nice catch!

Would you be able to submit a PR to fix this ?

**Comment by wivaku** [comment]
Will do (this weekend or so). Is going to be my first pull request though, be gentle. ;-)
