### ISSUE TITLE
Drop support for PHP 7.0 (End of life)

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#1066]
PHP 7.0 end of life was more than a year ago (1st January 2019).

Could we drop the support for this version ?
Should we also drop the support for PHP 7.1 (End of life begin of this year) ?

That would allow us to use nullable types, among other things (see #1065).

**Comment by Nyholm** [comment]
Im happy to drop any PHP version if there is a good reason for it. 

Since we have a use case for nullable types then Im happy with that. 

We should release a new minor version when updating the PHP version.

👍

**Comment by jbelien** [comment]
Awesome !
I'll take care of it this weekend !

**Comment by atymic** [comment]
I think we should consider dropping 7.1 as well, it's also well out of active support.

**Comment by jbelien** [comment]
I created a new release for all the sub-packages! 🎉 

I noticed too late that Mapzen provider was abandoned so didn't need a new release. I could delete the release but I guess it's not a good practice.
Didn't make the same mistake for the other abandoned package : GeoIPs provider (@Nyholm could you mark it as abandoned on Packagist ? Thanks)

I notice that a lot of `branch-alias` in `composer.json` files are out of sync.
I'll create a new PR to update it soon ! 💪

**Comment by stevevance** [comment]
@jbelien  Mapzen as an endpoint doesn't exist, but there are still geocoders that are based on it. The commercially available [Geocode.earth](http://geocode.earth) provides a Mapzen-compatible endpoint.

**Comment by jbelien** [comment]
> @jbelien Mapzen as an endpoint doesn't exist, but there are still geocoders that are based on it. The commercially available [Geocode.earth](http://geocode.earth) provides a Mapzen-compatible endpoint.

@stevevance No worries, we have a [Geocode Earth provider](https://github.com/geocoder-php/geocode-earth-provider) !
