### ISSUE TITLE
Switch from PHP-HTTP to PSR-18

### ISSUE THREAD

**Issue by JaZo** [geocoder-php/Geocoder#1076]
PHP-HTTP has been formalized into PSR-18 a while back. It would be really nice if we can switch to PSR-18 as this would allow us to use clients with 'native' PSR-18 support, but lacking PHP-HTTP support, such as Guzzle 7. Most (if not all) PHP-HTTP-clients also support PSR-18 so it should not be a big breaking change.

**Comment by jbelien** [comment]
Yes! You're absolutely right, that's definitely something we should do! 🎉 

I'll try to find some time in the next few month to prepare that migration.

**Comment by Nyholm** [comment]
We just need to drop php5. We can even do thin without breaking BC if I remember correctly.

**Comment by holtkamp** [comment]
For people who would like to understand this request, some additional documentation can be found here: http://docs.php-http.org/en/latest/httplug/introduction.html#client-interfaces

**Comment by jbelien** [comment]
@JaZo Would you have time to submit a PR ? Thanks :)

**Comment by JaZo** [comment]
I'd love to get this through, but don't exactly know how to do it without breaking BC. @Nyholm do you have some guidance or examples to get this through without breaking BC?

**Comment by Nyholm** [comment]
If we dont use any async stuff. Then there is no real BC break, Of course it is a technical BC break and we should update the major version. But befeore we are ready for a new major release, we can use both PSR18 and HTTPlug at the same time.

**Comment by JaZo** [comment]
Okay, I'll give it a go!
