### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by ildyria** [geocoder-php/Geocoder#1093]
Currently Geocoder is only supporting php 7.2 and higher as seen in composer.json.
```
    "require": {
        "php": "^7.2",
```

Would it be possible to additionally enable support for php 8.0 which [will be/has been] released on November 26th, 2020 ?

**Comment by jbelien** [comment]
Excellent idea !
I'll test and make the update once PHP 8.0 is officially released (announced for later today).

**Comment by jbelien** [comment]
Apparently PHP 8.0 is not available in TravisCI at the moment : https://travis-ci.org/github/geocoder-php/Geocoder/builds/746552201
I'll try again in a few days!

**Comment by ildyria** [comment]
At LycheeOrg we got limited by the credits system on TravisCI (docker was taking a lot of time to build) so we migrated to Github actions. I have to say, this option is significantly faster than Travis builds.

**Comment by ildyria** [comment]
I spent a few hours setting up GitHub actions as it provides PHP 8.0 (https://github.com/ildyria/Geocoder/tree/add-github-actions)

Unfortunately, simply changing the composer file to also accept php 8.0 is not enough as some dependencies do not accept PHP 8: https://github.com/ildyria/Geocoder/runs/1470099431?check_suite_focus=true

**Comment by jbelien** [comment]
Awesome, thanks for the information @ildyria 👍

**Comment by jbelien** [comment]
Travis CI has been updated and now PHP 8.0 is available.
As you noticed, we need support for PHP 8.0 on `php-http/curl-client`.

**Comment by ildyria** [comment]
Yes, I know: https://github.com/php-http/curl-client/issues/68

**Comment by ildyria** [comment]
Pull request on the Curl-client side: https://github.com/php-http/curl-client/pull/71

**Comment by mruz** [comment]
Curl-client has been updated. @jbelien can you open a PR to check if php8 branch passes?

**Comment by jbelien** [comment]
I'm having a look this week 👍 
I'll have to "upgrade" [`geocoder-php/provider-integration-tests`](https://github.com/geocoder-php/provider-integration-tests). I'm working on it.

**Comment by jbelien** [comment]
PR is ready and waiting for review : https://github.com/geocoder-php/provider-integration-tests/pull/17

**Comment by jbelien** [comment]
PR #1102 is ready and waiting for review 🚀

**Comment by jbelien** [comment]
It will need a bit more work to fully support PHP 8.0.

**Comment by jbelien** [comment]
It will (still) need a bit more work to fully support PHP 8.0.

**Comment by jbelien** [comment]
All (official) providers and components have got a new release and are now supporting PHP 8.0 !

Merry Christmas everyone ! 🎅

**Comment by mikebronner** [comment]
That is awesome! Thanks @jbelien. Will there be a new release of the main package as well in the near future, or does that still require more work?

**Comment by jbelien** [comment]
> Will there be a new release of the main package as well in the near future, or does that still require more work?

@mikebronner All packages already have a new release including our main package [`willdurand/geocoder`](https://packagist.org/packages/willdurand/geocoder).

If you're asking about a new release of [this repository](https://github.com/geocoder-php/Geocoder), I just released it but AFAIK there is no package linked to our main repository.
