### ISSUE TITLE
Migration to GitHub Actions

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#1100]
Travis CI is closing https://travis-ci.org/ for https://travis-ci.com/ and with that migration it seems like the free tier will be limited to 10000 credits.

I don't exactly understand the pricing model but I think it's time to migrate to GitHub Actions.

**EDIT:** I'm not even sure our Travis CI tests are still running, I triggered https://travis-ci.org/github/geocoder-php/provider-integration-tests/builds/749849954 1 hour ago and it still didn't start.

@Nyholm @atymic  Any concern about migrating from Travis CI to GitHub Actions ?

**Comment by jbelien** [comment]
@ildyria already gave it a try here : https://github.com/ildyria/Geocoder/tree/add-github-actions

**Comment by ildyria** [comment]
At LycheeOrg we migrated most of our CI to Github, because of the new "requirements" of travis. Some people took advantage of the "free" computational power to actually do crypto currency mining... (no comments)

I have to say that we haven't had any problem with the CI on Github Actions.
