### ISSUE TITLE
GeocodeQuery with zero as text fails

### ISSUE THREAD

**Issue by dmolineus** [geocoder-php/Geocoder#1124]
When creating a geocode query with `'0'` as text, the value is handled as invalid character. `'0'` though can be a valid query, e.g. when querying for postal codes. The issue here is the usage of `empty()`.

```php

$query = \Geocoder\Query\GeocodeQuery::create('0');

```

**Comment by jbelien** [comment]
Good point, thanks @dmolineus !

I'll create a PR to fix this later today.
