### ISSUE TITLE
Need a hand over here, keep getting an error

### ISSUE THREAD

**Issue by ccresz** [geocoder-php/Geocoder#1129]
`Class Geocoder\Provider\GoogleMaps\Model\GoogleAddress may not inherit from final class (Geocoder\Model\Address)

Symfony\Component\ErrorHandler\Error\FatalError 
…\vendor\geocoder-php\google-maps-provider\Model\GoogleAddress.php22

`
Have tried everything I can think of.

Even if you just suspect anything let me know and I'll try it.

**Comment by jbelien** [comment]
Hello @ccresz ,

I'll have a look, can you give us a bit more of context ? Could you show us your piece of code ?

**Comment by ccresz** [comment]
Is like I just needed you to answer to find the solution, was a file on Laravel cache stuck from previous versions I did:
`composer dump-autoload`
`composer clear-cache`
`php artisan optimize:clear`

and the problem went away, not exactly sure was the command that actually did the trick, but thanks problem is gone.
Thanks for your help.
