### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by ruudk** [geocoder-php/Geocoder#1145]
Important for Symfony 6.0:

- https://github.com/geocoder-php/chain-provider/commit/24f9a63d1fbcb7bb8d87c3427290f5e1a8c3faa7 
- https://github.com/geocoder-php/plugin/commit/6efd5e0be78128bf6e6df350d682063e01264f54

**Comment by jbelien** [comment]
Excellent point! Thanks for the reminder.

I'll create new releases before the end of the year!

**Comment by ruudk** [comment]
@jbelien Just a friendly reminder that the year is almost over 🎆 😉

**Comment by norkunas** [comment]
ping :wink:

**Comment by jbelien** [comment]
✨ New releases are live!
