### ISSUE TITLE
Clean wrong tag/release created by @JaZo

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#1161]
After #1110, I've updated all changelog files and was planning to create new releases.
But while creating new releases I realized that some tags already have been created by @JaZo.
Unfortuntately, a lot of those tags are **wrong** : he seems to have created a `4.3.0` tag for all providers instead of following the correct semver!

I'm currently deleting the wrong tags but it has already been updated on https://packagist.org/.

@Nyholm Could you give me the rights on "your" packages so I can deleted the tags that are wrong on Packagist ? Thanks.

To avoid this in the future I've added a tag protection rule on all the provider repositories.

**Comment by Nyholm** [comment]
It is updated!

**Comment by jbelien** [comment]
Cleaning is now complete!
Thanks @Nyholm for the assistance. 😄

**Comment by JaZo** [comment]
I don't know how that happened and I'm really sorry about that! I for sure didn't create these tags manually 🤔 Do you have any idea how that could've happened so I can make sure it never happens again?

**Comment by JaZo** [comment]
Ahhh, an issue with subtree split sounds plausible, let's hope it won't happen again!
