### ISSUE TITLE
Unable to install providers

### ISSUE THREAD

**Issue by mrelliot69** [geocoder-php/Geocoder#1163]
Heyy, im trying to install the providers like
composer require geocoder-php/nominatim-provider
but i allways get an error and i'm unable to procced

```
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-sup
port/
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - geocoder-php/common-http 4.5.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - geocoder-php/common-http 4.4.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - geocoder-php/common-http 4.3.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - geocoder-php/common-http 4.2.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - geocoder-php/common-http 4.1.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - geocoder-php/nominatim-provider 5.6.0 requires geocoder-php/common-http ^4.1 -> satisfiable by geocoder-php/common-http[4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0].
    - Installation request for geocoder-php/nominatim-provider ^5.6 -> satisfiable by geocoder-php/nominatim-provider[5.6.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

anyone know how i can fix this?

**Comment by jbelien** [comment]
Hello @mrelliot69 ,

According to the following warning, it seems that you're still using Composer version 1.
> Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-sup
port/

Could you try to [upgrade to Composer version 2](https://getcomposer.org/upgrade/UPGRADE-2.0.md) and give it another try?

**Comment by jbelien** [comment]
Also, you seem to run the following command:

```cmd
composer require geocoder-php/nominatim-provider
```

But Composer indicates that you miss a `php-http/client-implementation`.

You indeed need to specify which library you want to use (Guzzle, cUrl, ...)!

Check the main documentation here: https://github.com/geocoder-php/Geocoder#summary-just-give-me-the-command

**Comment by mrelliot69** [comment]
Thanks @jbelien , another question: 
is it possible to get the address id also when the provider list the results ..

For example arcgis have an id to identify that address, its possible to get that info also on the result array?

**Comment by jbelien** [comment]
> is it possible to get the address id also when the provider list the results ..
> 
> For example arcgis have an id to identify that address, its possible to get that info also on the result array?

See #1164
