### ISSUE TITLE
Static Maps

### ISSUE THREAD

**Issue by mrelliot69** [geocoder-php/Geocoder#1166]
Just came across a website that is using a feature that may interest other developers using this library.
Basically when they return the location they also provide a static map using the provider api

for example mapbox
https://docs.mapbox.com/api/maps/static-images/
https://api.mapbox.com/styles/v1/{username}/{style_id}/static/{overlay}/{lon},{lat},{zoom},{bearing},{pitch}|{bbox}|{auto}/{width}x{height}{@2x}

google maps:
https://developers.google.com/maps/documentation/maps-static/start

Is this on scope of geocoder-php?

**Comment by jbelien** [comment]
Hello @mrelliot69 ,

Thanks for your suggestion!
It's a really interesting feature but indeed out of scope of Geocoder PHP that is focused on geocoding (search for an address).
