### ISSUE TITLE
[Nominatim] Neighbourhood field

### ISSUE THREAD

**Issue by Jeremylepr** [geocoder-php/Geocoder#1167]
Some addresses have a "neighbourhood" field, for example : 

https://nominatim.openstreetmap.org/reverse?format=xml&lat=35.685939&lon=139.811695&zoom=18&addressdetails=1

In jsonResultToLocation(), this field is not processed, so we can't get that value through the reverseQuery() method.

**Comment by jbelien** [comment]
Hello @Jeremylepr,

Thanks for the idea.
It should be relatively easy to implement, could you create a PR ?
