### ISSUE TITLE
Google invalid response

### ISSUE THREAD

**Issue by paveldvorak5** [geocoder-php/Geocoder#1198]
Sometimes I get an error when using Google. It happens only few times a day, so I have no idea what's wrong.
But I noticed some strange characters in the URI after language.
How can I debug this?
Thanks
```
>>> (Geocoder)InvalidServerResponse <<<
`The geocoder server returned an invalid response (500) for query "https://maps.googleapis.com/maps/api/geocode/json?latlng=37.269400,28.208292&language=cs_CZ®ion=cs&key=...". We could not parse it.`
Error 0 (undefined) at ./vendor/willdurand/geocoder/Exception/InvalidServerResponse.php:30
```

**Comment by jbelien** [comment]
Hello @paveldvorak5,

The query seems "strange" ; `https://maps.googleapis.com/maps/api/geocode/json?latlng=37.269400,28.208292&language=cs_CZ®ion=cs&key=...` contains `®` after `&language=cs_CZ`.

Is that a copy paste issue or is it really the error message returned ?

**Comment by paveldvorak5** [comment]
No issue, that's the error message I saw

**Comment by jbelien** [comment]
Okay, I'll investigate.
Can you provide as much information as possible on the request you've tried to make ?

**Comment by paveldvorak5** [comment]
Hmm, I couldn't simulate is today
