### ISSUE TITLE
Provider and/or adapter list 

### ISSUE THREAD

**Issue by anggiaj** [geocoder-php/Geocoder#221]
Hi, is there any methods to list all available provider or adapter in this packages?

ex:
$class->getAvailableProviders();

and returning

array(
  'ip_info_db' => ...,
 ...
);

**Comment by jbelien** [comment]
I know this is an old issue but would it be a simple way to detect all installed providers ?

**Comment by Nyholm** [comment]
Maybe with Symfony autowirng. But we should create a new issue. This one is almost 5 years old =)

**Comment by jbelien** [comment]
#809 opened.
