### ISSUE TITLE
CacheProvider

### ISSUE THREAD

**Issue by Baachi** [geocoder-php/Geocoder#256]
Hey William,

The library is really popular (971 Stars on GitHub and 37063 Downloads on Packagist), which is really :cool: . But i think geocoder has a missing feature, _caching_. 

I created already a `CacheProvider` in the [`BazingaGeocoderBundle`](https://github.com/willdurand/BazingaGeocoderBundle/blob/master/Provider/CacheProvider.php), so i would suggest to move this provider to the core library.

What do you think about this change?

**Comment by advokata** [comment]
I use geotools. It is built atop Geocoder and has cache layer.

**Comment by canfiax** [comment]
+1 for caching

**Comment by egeloen** [comment]
I just added caching support to the http-adapter library: https://github.com/egeloen/ivory-http-adapter/pull/123

**Comment by Nyholm** [comment]
This is an very old issue. The current support for caching is using the psr6 and it is placed in the http adapter. Here is a cookbook entry for it: https://github.com/geocoder-php/Geocoder/blob/master/docs/cookbook/cache.md
