### ISSUE TITLE
GoogleMapsProvider doesn't support Component Filtering

### ISSUE THREAD

**Issue by zavan** [geocoder-php/Geocoder#299]
I'm talking about this: https://developers.google.com/maps/documentation/geocoding/#ComponentFiltering

Any ideas on how can we implement it? This has to be dynamic, easy to change on each "geocode" method call.

I'm thinking about a free array with keys and values corresponding to query parameters.
So

$provider->appendToQuery(array('components' => 'postal_code:555'));

 appends "&components=postal_code:555"

**Comment by ddctd143** [comment]
Thats bad, that this feature isn't implemented.
I'm working with Yandex provider and now I can't limit my search scope to only one city.

If I would work with pure yandex api, I would add additional parameters to default query string:
bbox=40.198610,54.249422~35.210817,56.891229&rspn=1

At the moment, with geocoder package this is impossible.
I have to fork yandex provider and add custom query parameters editing code.

geocoder package must be more flexible.

**Comment by Nyholm** [comment]
@ddctd143 A lot has happened since this issue was created. Have a look at current master. I think we can easily support this now. I would be happy to review a PR for this issue.
