### ISSUE TITLE
Add Factual provider?

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/Geocoder#395]
http://developer.factual.com/

**Comment by benjaminmullard** [comment]
Hi Will,

I'd like to contribute to this project and I though this issue might be a good place for me to start.  Is anyone working a Factual provider or am I okay to take this?

Cheers, Ben

**Comment by willdurand** [comment]
Hi Ben, glad to hear you want to help on this. Please, start working on this new provider! Thank you :heart:

**Comment by toin0u** [comment]
:heart:

**Comment by willdurand** [comment]
@benjaminmullard by the way, if you need help for anything, get in touch with us!

**Comment by benjaminmullard** [comment]
Cheers Will.  I'm just working on it now and I'm sure I'll have some questions soon.

**Comment by Nyholm** [comment]
This issue is very old. It seams that there is no demand for it. I will close this issue now but feel free to open a new issue or send a PR with the new provider.
