### ISSUE TITLE
Improving Geonames

### ISSUE THREAD

**Issue by stevro** [geocoder-php/Geocoder#400]
Currently GeonamesProvider implements only two endpoints, from a total of 38 possible, and the current provider doesn't seem to offer the possibility to add new endpoints without writing a complete new provider.

Do you think the project could benefit from a rewrite on this provider? Or it would be better to simply write a new provider?

I personally am interested in adding postalCodeLookupJSON.

http://www.geonames.org/export/ws-overview.html

**Comment by toin0u** [comment]
I think the other endpoints are a bit out of the scope. I'm not sure if it's a good idea. But I see your use case..

**Comment by willdurand** [comment]
:-1: because it is out of the scope to me as well

**Comment by stevro** [comment]
Ok, thanks for the feedback.
