### ISSUE TITLE
Could not parse version constraint ^2.5.7: Invalid version string "^2.5.7"

### ISSUE THREAD

**Issue by phuclh** [geocoder-php/Geocoder#403]
I try to run: `composer require willdurand/geocoder`. But I got a message:

```composer
[RuntimeException]                                                           
  Could not load package egeloen/http-adapter in http://packagist.org: [Unexp  
  ectedValueException] Could not parse version constraint ^2.5.7: Invalid ver  
  sion string "^2.5.7"
```

```composer
 [UnexpectedValueException]                                                  
  Could not parse version constraint ^2.5.7: Invalid version string "^2.5.7" 
```

Please help me. Thank you very much !!!

**Comment by willdurand** [comment]
Hi! I can't reproduce the issue unfortunately, so let's see... Could you please:

1. update composer by running `composer self-update`
2. use `--prefer-dist` option

**Comment by pyrech** [comment]
I think this should indeed be fixed after running `composer self-update` because the issue seems related to the operator `^` that was added recently in composer (related PR composer/)#2596 ;)

**Comment by phuclh** [comment]
Thank you everyone. It worked :D.
