### ISSUE TITLE
Documentation: Not clear how to provide the API key

### ISSUE THREAD

**Issue by gajus** [geocoder-php/Geocoder#404]
https://github.com/geocoder-php/Geocoder/blob/master/README.md `Geocoder\Provider\GoogleMaps` example fails to show that the last parameter is the API key. Had to take a look at the source code to find it, https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Provider/GoogleMaps.php#L56.

**Comment by toin0u** [comment]
Thank you for the report @gajus :)
