### ISSUE TITLE
Could not execute query 

### ISSUE THREAD

**Issue by trbsi** [geocoder-php/Geocoder#405]
I installed GeoCoder via composer. This is my query
> $adapter = new \Geocoder\HttpAdapter\CurlHttpAdapter;
> $provider = new \Geocoder\Provider\GoogleMapsProvider($adapter);
> $geocoder = new \Geocoder\Geocoder($provider);		
> $result=$geocoder->reverse(45.309976899999995, 18.4111394);

But sometimes it works, sometimes not, it just returns this:

> Geocoder\Exception\NoResultException
> Could not execute query http://maps.googleapis.com/maps/api/geocode/json?address=45.309977%2C18.411139

**Comment by toin0u** [comment]
Hi @trbsi 

Thank you for your feedback. Which version of Geocoder do you use ? A gist of your code could be nice. So I can try to reproduce the issue as well :)

Can you provide us in a gist your `composer.json` and the output of the command `composer show -i` please ?

**Comment by trbsi** [comment]
I'm using latest version. Downloaded it few hours ago.
It might be because I'm testing my site on localhost. I transferred it to hosting account and tried to refresh the same code few times in a row. Code on server worked fine, on localhost not. Might be the problem in XAMPP. That doesn't matter, it is important that it works on hosting server.

I can still give that info you need, but error didn't show up on online server at all

**Comment by toin0u** [comment]
@trbsi cool if it works on production but maybe it's not really safe to push in prod if your dev env do not work.. I advice to use something like [vagrant](https://www.vagrantup.com/) which will reflect the dev/test/prod envs. There is also a [Homestead](http://laravel.com/docs/4.2/homestead). Hope that will help.

I'll close this as it's not an issue related to the lib :)

**Comment by jacobnijgh** [comment]
I am having the same issue as well and i am using Homestead. I'm using version 3.3.0. With the GoogleMaps provider. We haven't yet tested it on production though.
