### ISSUE TITLE
FreeGeoIp US regionCode now invalid

### ISSUE THREAD

**Issue by patrickcarlohickman** [geocoder-php/Geocoder#407]
In PR #84, the FreeGeoIp provider was updated to return the FIPS_10-4 standard values for US regions, in order to match the response for the other countries.  However, the service at https://freegeoip.net has been updated to use the MaxMind GeoIP2 database (GeoLite2, specifically), which now returns the ISO 3166-2 standard values.  So now, the roles have been reversed, where the US regions are FIPS_10-4 and all others are ISO 3166-2.

The comparison urls from PR #84 are still valid: [http://freegeoip.net/json/bbc.com](http://freegeoip.net/json/bbc.com), [http://freegeoip.net/json/google.com](http://freegeoip.net/json/google.com).  Both now show the ISO 3166-2 values, not the FIPS_10-4 values.

The update merged in via PR #84 needs to be reverted to provide consistent region codes.

GeoIP2 changes described here: [http://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/](http://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/)

freegeoip service here: [https://github.com/fiorix/freegeoip](https://github.com/fiorix/freegeoip).  Update to GeoIP2 was done when v3.0 was released on Nov. 17, 2014

**Comment by willdurand** [comment]
Thanks for the report. We'll look at it soon!
