### ISSUE TITLE
Field like "Building Name"?

### ISSUE THREAD

**Issue by tannermccoleman** [geocoder-php/Geocoder#409]
OpenCage has the "house" field in some of their results, which shows the name of the building. Here's an example for the Duncan Building at 119 W Pender St, Vancouver, BC:

```
components: {
    city: "Vancouver",
    country: "Canada",
    country_code: "ca",
    county: "Greater Vancouver Regional District",
    house: "Duncan Building",
    house_number: "119",
    postcode: "V6B 1G8",
    road: "West Pender Street",
    state: "British Columbia",
    suburb: "Gastown"
}
```

Could a field be added in to include this information? I'm not sure if other providers have similar fields, but it can be very useful information for geocoding apartment and office buildings.

**Comment by Baachi** [comment]
If other provider also support this, sure we can implement it, if OpenCage is the only provider, we can't include them.

**Comment by stevevance** [comment]
Mapzen's [Pelias service](https://github.com/pelias) provides the building name if they know, pulling from OpenStreetMap and Geonames.

**Comment by aight8** [comment]
Sure you can implement specific information. Just add another field which holds the response of the provider.

**Comment by Nyholm** [comment]
Sorry for the very late response. This is now very easy to achieve. See https://github.com/geocoder-php/Geocoder/pull/624

I will close this issue, do not think that I do not want to see this feature. I will be happy to review a PR.
