### ISSUE TITLE
Yahoo! Boss Provider

### ISSUE THREAD

**Issue by travisghansen** [geocoder-php/Geocoder#410]
Would it be possible to implement this provider?  Or would you accept an implemented class?

https://developer.yahoo.com/boss/geo/

**Comment by toin0u** [comment]
Maybe not... :trollface: 

![](https://i.imgur.com/RxhBWnm.png)

More seriously, I think it could be great for the `3.0.0` release :) It's also possible to put in the [geocoder-extra](https://github.com/geocoder-php/geocoder-extra)

**Comment by travisghansen** [comment]
Yikes.  I wouldn't mind hacking something together but it requires OAuth 1.0..any tips on that front?
I currently leverage this: http://oauth.googlecode.com/svn/code/php/OAuth.php but I'm guessing that would be frowned upon in this scenario.

**Comment by renatoagds** [comment]
Maybe use YQL could be also an alternative using the tables GEO.PLACEFINDER and GEO.PLACEMAKER.

https://developer.yahoo.com/yql/
https://developer.yahoo.com/boss/geo/docs/free_YQL.html

Has 2000 queries per day for each APP ID.

**Comment by travisghansen** [comment]
YQL cannot be used commercially.  I've created a connector and utilized the standard OAuth pecl extension to implement it.  Happy to hand it over if you're interested for inclusion..

**Comment by toin0u** [comment]
I've looked at it closer and I'm in fact not sure it suits the library's scope..

**Comment by travisghansen** [comment]
Geocoding doesn't fit in the scope of the library?

**Comment by toin0u** [comment]
:) it's not up to me. I just think this provider does not suit the way we're unifying atm IMHO.

**Comment by toin0u** [comment]
@travisghansen FYI https://github.com/geocoder-php/Geocoder/issues/230#issue-13906699

**Comment by travisghansen** [comment]
I guess I'll need some further clarification.  The connector supplies every piece of information currently available in the 'Models' including reverse and IP geocoding, bounding boxes and administrative areas...
