### ISSUE TITLE
[FEATURE] Add formatted_address in result

### ISSUE THREAD

**Issue by onetest** [geocoder-php/Geocoder#411]
Please Add formatted_address in result (normalized address not composed by all part of address)

ex : result->getFormattedAddress()

**Comment by stevevance** [comment]
This is how you can currently get a formatted address:

````echo $geocode->first()->getStreetNumber()." ".$geocode->first()->getStreetName();````

**Comment by willdurand** [comment]
Well, I think you can use a `Formatter` for that purpose, since all addresses are not formatted the same way (it depends on the country).

**Comment by Gounlaf** [comment]
:+1:  for the feature ;

I hope, but it's not explained cleary, that `formatted_address` field provided by the geocoding service is standardized, and, at least, correspond to the format required in the country where the address is

https://developers.google.com/maps/documentation/geocoding/#Results :

> formatted_address is a string containing the human-readable address of this location. Often this address is equivalent to the "postal address," which sometimes differs from country to country. (Note that some countries, such as the United Kingdom, do not allow distribution of true postal addresses due to licensing restrictions.) This address is generally composed of one or more address components.

**Comment by willdurand** [comment]
It is not provided by most of the providers, so :-1:.
