### ISSUE TITLE
Proposal: More appropriate namespacing?

### ISSUE THREAD

**Issue by TheOnlyMerlin** [geocoder-php/Geocoder#413]
**Problem**
I am working on a project that is looking into switch to your geocoding solution, but we discovered that we had a naming conflict because we had a module in a namespace called Geocoder, where we rolled our own geocoding solution.  

**Proposal**
So, I was wondering if in some future version the namespace used by this package could more match http://www.php-fig.org/psr/psr-4/ with a fitting vendor name, such as "willdurand/geocoder/geocoder", or "willdurand/geocoder", or "geocoder-php/geocoder/geocoder" or "geocoder-php/geocoder".  

I understand that this change is unlikely to occur, due to the cost of a breaking change.  But the reduced chance of naming conflicts would be nice.  

**Anticipating Objections**
And to address your proposed solution in advance: we *are* looking into renaming our own packages in a similar way to avoid potential conflicts in the future.  But it would be nice if all involved did the same.

Thank you.

**Comment by willdurand** [comment]
Hi! No, it is not going to happen unfortunately.

The way namespaces are implemented in PHP, it should not be a problem to have two modules with the same root namespace. Classes can conflict though, but aliases can help :) Is there any conflicting class? Geocoder 3.0 has better classnames.
