### ISSUE TITLE
Misleading, and missing installation instructions

### ISSUE THREAD

**Issue by chdig** [geocoder-php/Geocoder#414]
When following the "Installation" instructions,  "composer require willdurand/geocoder", ends up downloading an old version of code (I believe it's 2.8.2). GoogleMaps provider is not present, but instead the old "GoogleMapsProvider" provider is.  As a result, if someone installs according to instructions, they will be lost in a series of dependency issues. [$geocoder = new \Geocoder\Provider\GoogleMaps($curl); as listed in the main example, won't work]

Further, there needs to be instructions of how to install Ivory, and/or when it's necessary.  There is no instruction to create an HttpAdaptor directory under Ivory (which doesn't exist by default), but appears necessary to work.

In the end, in my tests, I see now that PHP5.4 is required due to the use of traits, which I'm  not able to run on my servers, which means that upgrading to the latest codebase is possibly a dangerous thing to try/waste of time.  Can the website and docs be updated to show that PHP5.4 is a requirement to begin using it, as the Ivory code requires traits.  That said, the old version 2 of Geocoder worked with PHP5.3  , but no where have I found whether Geocoder v2 is now completely deprecated and should not be used.  Some clarification on all this would be much appreciated.

As is obvious, I lack the knowledge to add the necessary documentation myself, but hope this shows a few of the frustrations people may experience getting into the code/upgrading from V2

**Comment by willdurand** [comment]
Hi! As you noticed, Composer installed latest stable version (i.e. 2.8.2 as you said).

First paragraph of the README is:

> Important: You are browsing the documentation of Geocoder 3.x. Documentation for version 2.x is available here: Geocoder 2.x documentation.

Here is the documentation you are looking for: https://github.com/geocoder-php/Geocoder/blob/2.x/README.md.

As Geocoder 3.0 should be released very soon, it will stay.

As for PHP 5.3, it is deprecated by PHP itself, nothing related with the lib ;-)
