### ISSUE TITLE
BingMapsProvider has a bug in executeQuery:144

### ISSUE THREAD

**Issue by jedjones-uk** [geocoder-php/Geocoder#415]
When using the bing maps provider I have found that a streetName name isn't always returned. When this happens an empty string is passed on and causes the mbstring branch of formatString in ```AbstractResult``` to choke and throw a "No string given" exception. 

changing ```'streetName'   => $streetName,``` to the same as the other 
```'streetName'   => empty($streetName) ? null : $streetName,``` fixes the issue. I am not sure if this is an issue on standard php as well as I am using HHVM.

This is an example of a query that doesn't return a street name.
http://dev.virtualearth.net/REST/v1/Locations/23.03613140,113.29805420?key=key

**Comment by toin0u** [comment]
@jedjones-uk Thanks for the feedback! The JSON response can be found here https://gist.github.com/toin0u/4475621f71dfb121fb85 

I've tested against the last stable `2.8.2` and the master branch. I do not have any issue.. 

For `2.8.2`.

```php
<?php

require 'vendor/autoload.php';

use Geocoder\Geocoder;
use Geocoder\HttpAdapter\BuzzHttpAdapter;
use Geocoder\Provider\BingMapsProvider;

$geocoder = new Geocoder(new BingMapsProvider(new BuzzHttpAdapter, 'KEY'));
var_dump($geocoder->reverse(23.03613140, 113.29805420));
```

And for the `master` branch:

```php
<?php

require 'vendor/autoload.php';

use Geocoder\Provider\BingMaps;
use Ivory\HttpAdapter\CurlHttpAdapter;

$geocoder = new BingMaps(new CurlHttpAdapter, 'KEY');
print_r($geocoder->reverse(23.03613140,113.29805420));
```

Can you maybe provide a gist? So I'll gladly test against HHVM :)

**Comment by jedjones-uk** [comment]
@toin0u I am using the code in a laravel 4.2 project and it pulled the Geocoder library in when I used the GeocoderLaravel 0.4.x branch via 
``` "require": {
        "toin0u/geocoder-laravel": "@stable"
    }```

This Gist is the code that I was running with some comment and explanations for things. I have also included the excpetion that was being thrown.
https://gist.github.com/jedjones-uk/951a2c4f90a972e28323

The version info in my copy of the vendor files is:
const VERSION = '2.8.2';

**Comment by toin0u** [comment]
@jedjones-uk Thanks! I'll look at it asap :)

**Comment by toin0u** [comment]
@jedjones-uk I've got time to test my first script against HHVM (https://github.com/vicb/hhvm-vagrant) and I could reproduce the error. I get a warning as you can this here: https://i.imgur.com/m5n2jaP.png

The second script works fine.

Let's fix this :) Do you mind to provide a pull request?

**Comment by jedjones-uk** [comment]
I haven't got much experience contributing to a project that is this well maintained, which branch do I need to fork to apply the fix and I am unsure what if any changes I would need to make to the tests.

I am happy to do the fix with a little guidance, although I know because its small it may be preferable for you to handle it quickly.

**Comment by toin0u** [comment]
Well there is a beginning for everything isn't it? :)

1. first fork the project
2. clone your fork to your machine
3. make a new branch (something like patch-abstractresult) of from the `2.x` branch
4. write the patch
5. write a test case that covers the patch
6. push the branch to your fork
7. make a pull request against the `2.x` branch
8. Here you go! :)

Do not hesitate to ask more help if you needed!

**Comment by willdurand** [comment]
ping?

**Comment by jedjones-uk** [comment]
Yeah, sorry, it's like my customers can sense when I am about to do something other than work for them and respond by ramping up their "needs". I probably won't be able to do the fix and testing soon, so it might be better if someone more familiar with the project did it quicker.
