### ISSUE TITLE
require --> "egeloen/http-adapter": "0.5.*"

### ISSUE THREAD

**Issue by remdan** [geocoder-php/Geocoder#416]
In the current composer.json is the "egeloen/http-adapter": "0.5.*" used.
But 0.7.0 is still realised --> https://github.com/egeloen/ivory-http-adapter/releases/tag/0.7.0 , can you switch to this version? or is it in the moment not possible?

**Comment by egeloen** [comment]
For the record, there is no major BC breaks except in the PSR-7 namspeace. So, upgrading should be possible.

**Comment by willdurand** [comment]
@egeloen could you create a PR to adjust the tag of your lib? Do you have a stable version yet?

**Comment by willdurand** [comment]
@egeloen ping?
