### ISSUE TITLE
GoogleMapsBusinessProvider not working 

### ISSUE THREAD

**Issue by webdesign7** [geocoder-php/Geocoder#417]
Hi, 

I can't get your geocode library  working  with GoogleMapsBusinessProvider .. every time it says:

Could not execute query http://maps.googleapis.com/maps/api/geocode/json?address=London%252C%2BUnited%2BKingdom&client=147436736XXX-pr4smhsrfvlgvb0ppp05unbv01akmc6k.apps.googleusercontent.com

my CODE:
        $geocoder = new \Geocoder\Geocoder();
        $adapter  = new \Geocoder\HttpAdapter\CurlHttpAdapter();
        $provider = new \Geocoder\Provider\GoogleMapsBusinessProvider($adapter,'14743673XXXX-nk3e8pubf834gk4ss555a6g8jg8sku12.apps.googleusercontent.com');
        $geocoder->registerProvider($provider);
        $response = $geocoder->geocode($location);

but the GoogleMapsProvider is working .. 

I am using the 2.8.2 version

I will appreciate your soon help as I am in the middle of the project working on this issue

Many thanks

**Comment by webdesign7** [comment]
Hi there, 

Any help ? ideas, suggestions ? 

Thanks

**Comment by toin0u** [comment]
@webdesign7 Have you look at this https://github.com/geocoder-php/Geocoder/issues/295 and this https://github.com/geocoder-php/Geocoder/issues/281 ?

**Comment by dereuromark** [comment]
I had the same problem a few days ago, those screwups silently deactivated their API URL, you must use the primary one now - see https://github.com/dereuromark/cakephp-tools/commit/796864e49bd692bd0359e12bac5ff44298d75095

**Comment by willdurand** [comment]
Anyone to fix the URL?
