### ISSUE TITLE
BUG: SocketHttpAdapter

### ISSUE THREAD

**Issue by robertark** [geocoder-php/Geocoder#418]
When using the Google Map Provider, it appears that the Socket connection is not properly handling SSL (port 443) requests.

## My code:

    $adapter = new \Geocoder\HttpAdapter\SocketHttpAdapter();
    $geocoder = new \Geocoder\Geocoder();
    $geocoder->registerProviders(array(
        new \Geocoder\Provider\GoogleMapsProvider($adapter, null, null, true, GM_API_KEY)
    ));

The SSL parameter is TRUE. Now, when making the request, SocketHttpAdapter is testing for the PORT and setting it accordingly, or defaulting to port 80:

    public function getContent($url)
    {
        $info = parse_url($url);

        $hostname = $info['host'];
        $port     = isset($info['port']) ? $info['port'] : 80;
        $path     = sprintf('%s%s',
            isset($info['path'])  ? $info['path']        : '/',
            isset($info['query']) ? '?' . $info['query'] : ''
        ); 
    [...]

Now, the problem is `const ENDPOINT_URL_SSL = 'https://maps.googleapis.com/maps/api/geocode/json?address=%s';` doesn't have the port `:443` in the URL. And it shouldn't - but the SocketHttpAdapter `getContent()` method doesn't check.

## Suggested solution:

1) Update the logic in the `getContent()` method to set the `$port` variable to: `$port     = isset($info['port']) ? $info['port'] : $info['scheme'] === 'https' ? 443 : 80;`

## Other issue:

For some reason, the socket also doesn't appear to want to function properly at all. I wasn't able to take any more time troubleshooting this, so I can't say if this is a script issue (particularly the `getParsedHttpResponse` method was returning empty strings) or what. I switched to CURL.

**Comment by robertark** [comment]
Note: after looking into this a bit more, I was getting an error from Google: 

    "error_message" : "This IP, site or mobile application is not authorized to use this API key.", "results" : [], "status" : "REQUEST_DENIED"

After looking into the key, which had the proper IP's, I ended up generating a new key and allowed all IP's.

Seems the script isn't handling this particular error, which was making it incredibly hard to troubleshoot.

**Comment by willdurand** [comment]
So, what?

**Comment by ssacard** [comment]
I'm bumping into a similar issue and I hope you could help. I'm using the CurlHttpAdapter from the beginning without API Key. Now I'm using a server API Key to go above the rate limite, and that the server IP is configured on Google side, Google returns this error : 

"error_message" : "This IP, site or mobile application is not authorized to use this API key.", "results" : [], "status" : "REQUEST_DENIED"

Any idea how to debug this ?

**Comment by robertark** [comment]
You must allow the server ip in the google api console for that key

**Comment by ssacard** [comment]
Hi Rob, yes I did this, but even after configuring the IP in the admin console I still get the error message. The error is probably stupid, but I can't find a way to debug this.

**Comment by robertark** [comment]
Try removing ip restrictions

**Comment by ssacard** [comment]
Sorry to bother, but I don't see where to remove IP restrictions ?

**Comment by robertark** [comment]
Generate a new api key

**Comment by ssacard** [comment]
OK, I see. Thank you.
