### ISSUE TITLE
Implement French provider

### ISSUE THREAD

**Issue by Rahe** [geocoder-php/Geocoder#424]
Hi !

In France we have an API dedicated for the geocoding/reverse-geocoding.
Maybe it's a good idea to implement it ?
The API description is here :
http://adresse.data.gouv.fr/api/

Thank you for you great work :)

**Comment by willdurand** [comment]
Heya!

Yes, I stumbled upon this API last week, and a contributor also told me about it.
I didn't look at it yet, but why not. However, I would implement it in [geocoder-extra](https://github.com/geocoder-php/geocoder-extra).

**Comment by Nyholm** [comment]
This issue is very old. It seams that there is no demand for it. I will close this issue now but feel free to open a new issue or send a PR with the new provider.
