### ISSUE TITLE
How to know the provider used in the provider chain?

### ISSUE THREAD

**Issue by drjoju** [geocoder-php/Geocoder#425]
Hi,

I'm using  an array of providers (Google, Bing, Yandex). How can I know the provider used in the geocode method? What provider is delivering the result?

Thanks in advance

**Comment by willdurand** [comment]
I don't think you can know which provider delivered the result.

**Comment by Baachi** [comment]
It is possible, you have to extend the [`ProviderAggregator`](https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/ProviderAggregator.php) class and override the `geocode/reverse` method. You get the name of the actual provider through `$this->provider->getName()`.

Quick example:

```

class MyGeocoder extends ProviderAggregator 
{
    public function geocode($value)
    {
          $name = $this->provider->getName(); // Here is the name of the current provider.
          $result = parent::geocode($value);

          return $result;
    }
}
```

**Comment by drjoju** [comment]
Nice!. Thanks

**Comment by toin0u** [comment]
@Baachi maybe it can be a good idea to update the doc about this :) I think it can be helpful. What do you think?

**Comment by Baachi** [comment]
Sure why not, a opend a issue so i didn't forget it :smile:

**Comment by toin0u** [comment]
Good idea :)
