### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by hannesvdvreken** [geocoder-php/Geocoder#426]
In my project I have extended the GoogleMapsProvider to have a setter for component filters.

https://developers.google.com/maps/documentation/geocoding/#ComponentFiltering

If I'd create a PR, would you such kind of additional functionality?

**Comment by sgb-io** [comment]
:+1: care to share your work, @hannesvdvreken? Also working on this.

**Comment by Nyholm** [comment]
Hey. I'm closing this issue because it is not relevant anymore. We should use he new query object. 

Sorry for taking so long to respond.
