### ISSUE TITLE
Switch from final to public and private to protected

### ISSUE THREAD

**Issue by Gounlaf** [geocoder-php/Geocoder#430]
Hi,

Is it possible to switch `Models` from `final class` to just `class`, and also private properties/methods as protected (for `Models` but also `Providers`) ?
Why ? Because, sometimes, we need extra features (formatted_address, place_id ...), and for this, we have to override everything, because of in `final`and `private`
* Model
* and so Factory ...

**Comment by giosh94mhz** [comment]
Well, I don't know if this apply as-is to this library as well, but you'll find most of the reason in [this good article](http://ocramius.github.io/blog/when-to-declare-classes-final/) from one of the maintainer of the Doctrine library. Don't worry, it has a TL;DR section ;)

**Comment by Baachi** [comment]
@Gounlaf you can extend a class in a different ways, like an decorator pattern.

**Comment by toin0u** [comment]
@Gounlaf There is a good example here https://github.com/domnikl/DesignPatternsPHP/blob/master/Structural%2FDecorator%2FREADME.rst

**Comment by jguittard** [comment]
@giosh94mhz excellent article about the use of `final`, that actually does not apply to what @Gounlaf mentioned, which are DTO. Models do not have contracts what so ever, so there's actually no point of making them `final`.
@Baachi of course, you can extend a class **behavior** with the decorator pattern, but again, we're talking about simple Data Transfer Objects, who don't have any behavior but their accessors/mutators.

@willdurand any chance you would accept a PR that allow inheritance from the models ?
