### ISSUE TITLE
Fatal error when exception is thrown (NoResult with GeoNames)

### ISSUE THREAD

**Issue by Jonas-Jancarik** [geocoder-php/Geocoder#439]
When the search query returns no results, the script fails with

`Fatal error: in C:\...\vendor\willdurand\geocoder\src\Geocoder\Provider\Geonames.php on line 116`

This is what is on line 116 of Geonames.php:

`throw new NoResult(sprintf('No places found for query "%s".', $query));`

I see that [Exception.php](https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Exception/Exception.php) is pretty much empty. Is that intended? What else could be the reason and what would be a suggested workaround?

For the moment, I just commented out the `throw`s.

**Comment by willdurand** [comment]
Hi! What's your PHP version number?

**Comment by Jonas-Jancarik** [comment]
Hi, I am running PHP 5.5.15.

Thanks for looking into this!

**Comment by Jonas-Jancarik** [comment]
I've figured it out, it was an issue on my side - I was not catching the exception properly. Sorry about that and thanks!
