### ISSUE TITLE
Laravel 5.1 Install fails

### ISSUE THREAD

**Issue by azcoppen** [geocoder-php/Geocoder#440]
Using version ^3.0 for willdurand/geocoder
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - egeloen/http-adapter 0.7.0 requires phly/http dev-header-case-sensitivity as 0.11.x-dev -> no matching package found.
    - willdurand/geocoder v3.0.0 requires egeloen/http-adapter 0.7.* -> satisfiable by egeloen/http-adapter[0.7.0, 0.7.1].
    - Installation request for willdurand/geocoder ^3.0 -> satisfiable by willdurand/geocoder[v3.0.0].
    - Conclusion: remove psr/http-message 1.0
    - Conclusion: don't install psr/http-message 1.0
    - egeloen/http-adapter 0.7.1 requires phly/http ^0.11.2 -> satisfiable by phly/http[0.11.2, 0.11.3].
    - phly/http 0.11.2 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - phly/http 0.11.3 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - Can only install one of: psr/http-message[0.9.0, 1.0].
    - Can only install one of: psr/http-message[0.9.1, 1.0].
    - Can only install one of: psr/http-message[0.9.2, 1.0].
    - Installation request for psr/http-message == 1.0.0.0 -> satisfiable by psr/http-message[1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by jenssegers** [comment]
`phly/http` seems to be abandoned.

**Comment by willdurand** [comment]
ah right maybe... ping @egeloen

**Comment by azcoppen** [comment]
Using "willdurand/geocoder": "dev-master" as per newest commit clashes with AWS v3 required for L5.1 filesystem support:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove guzzlehttp/psr7 1.1.0
    - Conclusion: don't install guzzlehttp/psr7 1.1.0
    - Installation request for willdurand/geocoder dev-master -> satisfiable by willdurand/geocoder[dev-master].
    - aws/aws-sdk-php 3.2.0 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.2.0 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.1.0 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.7 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.6 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.5 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.4 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.3 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.2 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.1 requires guzzlehttp/psr7 ~1.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - aws/aws-sdk-php 3.0.0 requires guzzlehttp/psr7 ^1.0.0 -> satisfiable by guzzlehttp/psr7[1.1.0, 1.0.0].
    - Conclusion: don't install guzzlehttp/psr7 1.0.0
    - Installation request for aws/aws-sdk-php 3.* -> satisfiable by aws/aws-sdk-php[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.2.0].

**Comment by egeloen** [comment]
I'm a little bit lost here. Can someone point me what is wrong in my `composer.json` file? I have switched from `phly/http` to `zendframework/zend-diactoros`, I was thinking it will fix the issue but it seems not the case (anyway as it is something which was required due to the abandonned `phly/http` I have not loose my time).

But then, what is the package which is in conflict with `guzzlehttp/psr7` in the http adapter?

**Comment by egeloen** [comment]
Or at least, share your `composer.json` in order I understand what's going on.

**Comment by mariano** [comment]
I see the same issue. My `composer.json`:

```json
    "require": {
        "slim/slim": "^3.0@beta",
        "vlucas/phpdotenv": "^2.0",
        "willdurand/negotiation": "^1.3"
    }
```

Running install:

```bash
composer require willdurand/geocoder
Using version ^3.0 for willdurand/geocoder
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - egeloen/http-adapter 0.7.0 requires phly/http dev-header-case-sensitivity as 0.11.x-dev -> no matching package found.
    - willdurand/geocoder v3.0.0 requires egeloen/http-adapter 0.7.* -> satisfiable by egeloen/http-adapter[0.7.0, 0.7.1].
    - Installation request for willdurand/geocoder ^3.0 -> satisfiable by willdurand/geocoder[v3.0.0].
    - Conclusion: remove psr/http-message 1.0
    - Conclusion: don't install psr/http-message 1.0
    - egeloen/http-adapter 0.7.1 requires phly/http ^0.11.2 -> satisfiable by phly/http[0.11.2, 0.11.3].
    - phly/http 0.11.2 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - phly/http 0.11.3 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - Can only install one of: psr/http-message[0.9.0, 1.0].
    - Can only install one of: psr/http-message[0.9.1, 1.0].
    - Can only install one of: psr/http-message[0.9.2, 1.0].
    - Installation request for psr/http-message == 1.0.0.0 -> satisfiable by psr/http-message[1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by mariano** [comment]
@egeloen fixed the issue, but naturally a new release has to be made. Until then you can use a little composer-fu to fool those packages that require http-adapter into thinking they DO have 0.7:

```bash
$ composer require egeloen/http-adapter "dev-master as 0.7"
```

You can then go ahead and install the latest geocoder release:

```bash
$ composer require willdurand/geocoder
```

**Comment by azcoppen** [comment]
Nice job @mariano! My composer.json is a bit large to paste here, but here's the result:
```
composer require egeloen/http-adapter "dev-master as 0.7"
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)         
  - Installing zendframework/zend-diactoros (1.1.2)
    Downloading: 100%         

  - Installing egeloen/http-adapter (dev-master aa9c449)
    Cloning aa9c449493bd8da51559d526261dcea48a98c767

egeloen/http-adapter suggests installing guzzle/guzzle (Allows you to use the Guzzle 3 adapter)
egeloen/http-adapter suggests installing kriswallsmith/buzz (Allows you to use the Buzz adapter)
egeloen/http-adapter suggests installing nategood/httpful (Allows you to use the httpful adapter)
egeloen/http-adapter suggests installing zendframework/zendframework1 (Allows you to use the Zend 1 adapter)
egeloen/http-adapter suggests installing zendframework/zend-http (Allows you to use the Zend 2 adapter)
egeloen/http-adapter suggests installing symfony/stopwatch (Allows you to use the stopwatch http adapter and event subscriber)
Writing lock file
Generating autoload files
```
Then geocoder:
```
composer require willdurand/geocoder
Using version ^3.0 for willdurand/geocoder         
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)         
  - Installing igorw/get-in (v1.0.3)
    Downloading: 100%         

  - Installing willdurand/geocoder (v3.0.0)
    Downloading: 100%         

willdurand/geocoder suggests installing geoip/geoip (If you are going to use the MaxMindBinaryProvider (conflict with geoip extension).)
willdurand/geocoder suggests installing geoip2/geoip2 (If you are going to use the GeoIP2DatabaseProvider.)
willdurand/geocoder suggests installing symfony/stopwatch (If you want to use the TimedGeocoder)
Writing lock file
Generating autoload files
```
Subsequent composer.json file looks like this:
```
"require": {
        "egeloen/http-adapter": "dev-master as 0.7",
        "willdurand/geocoder": "^3.0"
}
```
