### ISSUE TITLE
Additional address fields

### ISSUE THREAD

**Issue by aaronwebb** [geocoder-php/Geocoder#441]
With providers that return accuracy information the list of address results without the accuracy information I find to not be completely useful.

For instance, the ArcGIS service I'm using can return results matched at different levels and with different accuracies within those levels. I'd like to choose a point/rooftop match over a postal code/approximated match and a 99% street match over a 70%, etc.

If I put together a PR for this do you have any thoughts on how you'd like to see it implemented? Would you accept an extension of the address model? Maybe a custom data property with key value pairs that can be utilized by individual providers?

**Comment by Nyholm** [comment]
Sorry for the very late response. This is now very easy to achieve. See https://github.com/geocoder-php/Geocoder/pull/624

I will close this issue, do not think that I do not want to see this feature. I will be happy to review a PR.
