### ISSUE TITLE
Install via composer issue

### ISSUE THREAD

**Issue by yiioverflow** [geocoder-php/Geocoder#443]
Hi @egeloen 

roopz@roopz-pc:~/www/malabardial$ composer require willdurand/geocoder
Using version ^3.0 for willdurand/geocoder
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.    

  Problem 1
    - egeloen/http-adapter 0.7.0 requires phly/http dev-header-case-sensitivity as 0.11.x-dev -> no matching package found.
    - willdurand/geocoder v3.0.0 requires egeloen/http-adapter 0.7.* -> satisfiable by egeloen/http-adapter[0.7.0, 0.7.1].
    - Installation request for willdurand/geocoder ^3.0 -> satisfiable by willdurand/geocoder[v3.0.0].
    - Conclusion: remove psr/http-message 1.0
    - Conclusion: don't install psr/http-message 1.0
    - egeloen/http-adapter 0.7.1 requires phly/http ^0.11.2 -> satisfiable by phly/http[0.11.2, 0.11.3].
    - phly/http 0.11.2 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - phly/http 0.11.3 requires psr/http-message ^0.9 -> satisfiable by psr/http-message[0.9.0, 0.9.1, 0.9.2].
    - Can only install one of: psr/http-message[0.9.0, 1.0].
    - Can only install one of: psr/http-message[0.9.1, 1.0].
    - Can only install one of: psr/http-message[0.9.2, 1.0].
    - Installation request for psr/http-message == 1.0.0.0 -> satisfiable by psr/http-message[1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by willdurand** [comment]
ping @egeloen

**Comment by yiioverflow** [comment]
@egeloen ,  Any clue ?
