### ISSUE TITLE
Using Google Provider with API

### ISSUE THREAD

**Issue by antoniogarcia78** [geocoder-php/Geocoder#444]
Two problems:

1.If use the parameter $apiKey in the constructor the request fail because Google need a https.
It need set $useSsl to TRUE
1. The request with API an useSSL true fail 
   Error message " with the adapter "curl" ("SSL certificate problem: unable to get local issuer certificate")." Is more a fail of my instalation (Windows) but is good to know

**Comment by willdurand** [comment]
Ok, so we basically have to update the doc to reflect such constraints:

1. SSL with API key (makes totally sense)
2. SSL might not work well with cURL adapter (but should work with others I guess)

**Comment by antoniogarcia78** [comment]
1. Perfect
2. Not work for me. I search for a solution and you can do a workaround
with cert or change the version of guzzle. Now I haven't time to testing
these options.

Thank you William

**Comment by gabrielkaputa** [comment]
got the same issue, this solved it for me https://github.com/egeloen/ivory-http-adapter/issues/121#issuecomment-140651571

**Comment by Nyholm** [comment]
This issue is solved in master.
