### ISSUE TITLE
Get additional api information

### ISSUE THREAD

**Issue by JHGitty** [geocoder-php/Geocoder#446]
I like to get the `viewport` instead of `bounds` in `Google Geocoding API` responses.
Explained here: https://developers.google.com/maps/documentation/geocoding/intro#Results

Or to say it in other words: I like to get the additional information which are responded by the specific API.

Is there any way to get the official response?

As I understand you are currently not able to get additional information or the official response, right? It would be great to have this feature in upcoming releases!

**Comment by p-j** [comment]
@JHGitty you can have a look a my comment here https://github.com/geocoder-php/Geocoder/pull/496#issuecomment-207417758 
We've implemented a quick fix to give the ability to choose between `bounds` and `viewport` when you instantiate the GoogleMaps Geocoder Provider. 

If that can helps...
