### ISSUE TITLE
Class 'Geocoder\HttpAdapter\CurlHttpAdapter' not found

### ISSUE THREAD

**Issue by bonbonpiment** [geocoder-php/Geocoder#449]
Hi

I don t know what's wrong but I always get this error when trying to use Geocoder... Composer has done the job, everything's OK, I double checked the install, inspect my tree files twice but I'm stuck with this error ... Is there an example to install  without using composer ?

**Comment by bonbonpiment** [comment]
And by the way you've done a great job with "geocoder-php" !!

**Comment by Baachi** [comment]
Have you checked that you didn't have a typo? Also do you use geocoder version 2 or version 3? 
In version 3 we use an extern library to interact with the webservices, so there is no `CurlHttpAdapter` anymore.

**Comment by JHGitty** [comment]
I think @bonbonpiment use version 3 but looks for a class of version 2. So this is not a bug/issue.
