### ISSUE TITLE
ArcGIS authentication

### ISSUE THREAD

**Issue by joelclermont** [geocoder-php/Geocoder#451]
How do I provide my client secret for the ArcGIS provider?

**Comment by JHGitty** [comment]
There is no secret key required for the `ArcGISOnline` provider.

**Comment by joelclermont** [comment]
What if I want to use it with my paid account? Unauthorized API requests are limited at a certain point. Similar to Google Maps.

**Comment by JHGitty** [comment]
Currently paid accounts are not supported for the `ArcGISOnline` provider. You are not able to add a secret key. Somebody should add support for it.

**Comment by joelclermont** [comment]
Ok, thanks. Do you have any other providers that currently use an oauth flow to get a token for authentication? If so, I could take a look and work on an ArcGIS implementation.

**Comment by JHGitty** [comment]
There is no provider which use oauth, yet. It is a good question how we should handle it the right way. Maybe we could use an external oauth client but it would add dependency. Otherwise we could do our own basic oauth?

**Comment by joelclermont** [comment]
I'll have some time to work on it next week. Do you want me to leave this issue open and track discussion here? Or should I open a new issue when I have something more concrete to present?

**Comment by JHGitty** [comment]
Sure, let the issue open until it has been fixed (= pull request and merged). :+1: 
I am not a maintainer of Geocoder, just a user of the community. But everyone can help each other.

**Comment by willdurand** [comment]
If you want to improve the current ArcGIS provider, feel free :) We have a few providers that rely on tokens/private keys already, so adding such a feature to the ArcGIS one would make sense.

**Comment by vicchi** [comment]
This is a great idea, but from experience there's 2 issues with this ...

1. All of the current provider implementations are stateless; adding OAuth tokens, which for ArcGIS at least have a finite lifetime, makes this provider stateful, which will need some re-engineering under the hood. It's doable, but not trivial.

2. From using the ArcGIS geocoder in my day job, OAuth tokens are not required and, the last time I tried this a few months back, are actively rejected for calls to the ArcGIS World Geocoder's `find` service. They are supported for the `findAddressCandidates` service, which is part of the World Geocoder, but which isn't (currently) used by the ArcGIS provider implementation.

**Comment by Nyholm** [comment]
If you use dev-master you can add the AuthenticationPlugin on your HTTP client to add a token. 

See http://docs.php-http.org/en/latest/plugins/authentication.html
