### ISSUE TITLE
Add __toString() magic function to Country class

### ISSUE THREAD

**Issue by JHGitty** [geocoder-php/Geocoder#452]
I think we should add a `__toString()` magic function to the `Country` class.
It should return the name of the Country as string.

Reason:
```
Catchable Fatal Error: Object of class Geocoder\Model\Country could not be converted to string
```

**Comment by willdurand** [comment]
:+1:

However, where/how did you get this error?

**Comment by JHGitty** [comment]
I read the address output after geocoding and set the country name into a own object.

Ihave done something like this:
```
$this->setCountry($address->getCountry());
```

Without ``__toString()`` in the ``Country`` class you must do something like this instead:
```
$this->setCountry($address->getCountry()->getName());
```

**Comment by willdurand** [comment]
Alright. So let's add `toString()` methods in such classes then.
