### ISSUE TITLE
Notice at Geonames.php on line 119

### ISSUE THREAD

**Issue by shinesoftware** [geocoder-php/Geocoder#457]
Hi guys,

could this Notice be solved? 

    Notice: Undefined property: stdClass::$geonames in /vendor/willdurand/geocoder/src/Geocoder/Provider/Geonames.php on line 119

Regards

**Comment by toin0u** [comment]
Hi @shinesoftware, how can I reproduce it please? :)

**Comment by shinesoftware** [comment]
solved!
