### ISSUE TITLE
Yandex map response "301 Moved Permanently"

### ISSUE THREAD

**Issue by bubnovKelnik** [geocoder-php/Geocoder#463]
Reason - Yandex moved to https so you must change to:

const GEOCODE_ENDPOINT_URL = 'https://geocode-maps.yandex.ru/1.x/?format=json&geocode=%s';
const REVERSE_ENDPOINT_URL = 'https://geocode-maps.yandex.ru/1.x/?format=json&geocode=%F,%F';

**Comment by willdurand** [comment]
:+1: willing to create a PR maybe?

**Comment by bubnovKelnik** [comment]
Yes

**Comment by bubnovKelnik** [comment]
Sorry, I found this issue has already been closed in 3.1.0 at least.
