### ISSUE TITLE
Wrong order of sprintf`s params in Geocoder\Model\AdminLevelCollection::checkLevel

### ISSUE THREAD

**Issue by bubnovKelnik** [geocoder-php/Geocoder#468]
Now it is: 
throw new \OutOfBoundsException(sprintf(
   self::MAX_LEVEL_DEPTH,
   "Administrative level should be an integer in [1,%d], %d given",
   $level
));
//Output: 5

It should be:

throw new \OutOfBoundsException(sprintf(
   "Administrative level should be an integer in [1,%d], %d given",
   self::MAX_LEVEL_DEPTH,
   $level
));
//Output: Administrative level should be an integer in [1,5], 6 given

**Comment by willdurand** [comment]
Hi! Thanks for the report. Could you create a PR for that? Thank you!

**Comment by bubnovKelnik** [comment]
I have created the PR for this issue
