### ISSUE TITLE
Tests are broken with PHP 7

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/Geocoder#470]

**Comment by philippfrenzel** [comment]
Hi, it looks like google changed something with their geocode api landing point - so curl requests fail... I guess this crashes your tests... I didn't figure out a work around, would be great if someone would post a solution to this? Thanks!

**Comment by Baachi** [comment]
@philippfrenzel Are you sure? Our tests only failing on PHP7 on all other platforms the tests passes.

**Comment by philippfrenzel** [comment]
Hey, it's a other issue I'm facing. I make the requests "out of a docker container" and it looks like the routing is wrong... sorry for messing this up! Thanks for taking care!

**Comment by mattsches** [comment]
Has anyone looked into this yet? If I run the tests locally against a freshly compiled PHP 7, I'm not getting any errors.
