### ISSUE TITLE
Requires egeloen/http-adapter ~0.8 -> no matching package found

### ISSUE THREAD

**Issue by lukepolo** [geocoder-php/Geocoder#476]
- willdurand/geocoder v3.3.0 requires egeloen/http-adapter ~0.8 -> no matching package found.
    - willdurand/geocoder 3.3.x-dev requires egeloen/http-adapter ~0.8 -> no matching package found.
    - Installation request for willdurand/geocoder ^3.3 -> satisfiable by willdurand/geocoder[3.3.x-dev, v3.3.0].

**Comment by lukepolo** [comment]
https://packagist.org/packages/egeloen/http-adapter#0.8.0 , seems to be abandoned. Im assuming composer by default doesn't load abandoned projects. 

Process to fix this ?

**Comment by willdurand** [comment]
Hi @lukepolo, I just merged a fix for that. Could you try to install: `~3.3@dev`? (or `dev-master`)

**Comment by lukepolo** [comment]
Yup worked

**Comment by egeloen** [comment]
I don't understand here. Tag a package as abandon on packagist should not forbid to install it or am I missing something? Futhermore, the `0.8.0` tag exists, so you should not face this error.

**Comment by lukepolo** [comment]
It worked after the merge , so not sure what was going on .

**Comment by egeloen** [comment]
Hum, got it, this is because Symfony3 is not allowed in the `0.8.0` release.
