### ISSUE TITLE
HTTPLug

### ISSUE THREAD

**Issue by Baachi** [geocoder-php/Geocoder#480]
Hey guys,

what are youre thoughts about httplug? It's an http layer which follows the psr7 context and is
similar to ivory http adapter. Its well supported and its support async http calls.

If everyone would agree, i would start to integrate it in next couple of days.

@geocoder-php/geocoder

**Comment by willdurand** [comment]
This is a must have to me. Yet we will have to release Geocoder **v4** (which is perfectly fine).

**Comment by willdurand** [comment]
See #512
