### ISSUE TITLE
Geocoding an image or a file

### ISSUE THREAD

**Issue by drupol** [geocoder-php/Geocoder#482]
Hi,

I'm developping a new release for the Geocoder module for Drupal and it will be using this amazing library.
I made a small provider, it geocodes an image, let me know if a pull request is welcome.

https://github.com/drupol/geocoder/blob/7.x-2.x/src/Geocoder/Provider/File.php

Let me know what you think and don't hesitate to send pull requests.

Thanks !

**Comment by toin0u** [comment]
@drupol Thanks! Your Drupal module looks nice :) I see the use case but I think it goes a bit beyond this library's goals. What do you think @willdurand @Baachi?

**Comment by vicchi** [comment]
It's a neat solution and while `exif_read_data` is part of PHP, I think this is outside of the scope of what the Geocoder project is focused on. As it's easy to read EXIF data from an image file that contains that data, surely extracting the geotags, if present and then reverse geocoding those via a provider of choice is the way forward for this.

It's a -1 from me on this I think.

**Comment by Nyholm** [comment]
I agree. That is cool, but it is out of scope
