### ISSUE TITLE
RFC Resolve Constructor mess

### ISSUE THREAD

**Issue by dereuromark** [geocoder-php/Geocoder#485]
Constructor arguments are especially important for Inversion of Control and providing DI.
So the first argument of the Provider is useful: `HttpAdapterInterface`.
The rest are just random string options that differ per provider, there is no way to more generically call different providers unless you start mapping them in application code.
It is also not too future safe.
A way better approach, like CakePHP often does, is to group those options in an $options array, making it more consistent, extendable and future-safe.

    public function __construct(HttpAdapterInterface $adapter, ArrayObject $options) {}

ArrayObject could also be array, of course.
But the point is, now you can pass all options (locale, region, ssl, apiKey and CO without having to wonder if you have the wrong order or if you miss something because you changed the provider and there the 3rd arg is already the key instead of the 4th etc.

**Comment by jguittard** [comment]
:+1:

**Comment by dereuromark** [comment]
Missing required keys should throw exceptions of course.

**Comment by jguittard** [comment]
@dereuromark a PR would be nice :)

**Comment by willdurand** [comment]
No one said that provider construction should be generic and uniform. 
Constructors are not part of any interface. 

Providers have to be registered/initialized somewhere before being actually used. I don't see the need for consistency here, especially with a random unconsistent array of options...

**Comment by dereuromark** [comment]
Because order and amount matters for constructors, it does not for arrays.

**Comment by Baachi** [comment]
As i said i don't see here any advantage, i would like to keep it simple.

**Comment by willdurand** [comment]
I have to say "no" again. Constructors take multiple arguments for different reasons: readability is one of them, but also for describing dependencies of a class, e.g., which data the class encapsulates, and to determine mandatory/optional args.

An array of options may be convenient/easier, it does not enforce anything. Arguments in constructors are a powerful OOP feature no one should avoid.

**Comment by drupol** [comment]
I think we could get around this problem by implementing a ```setConfiguration(array $configuration = array())``` method in https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Provider/AbstractProvider.php that would set the configuration properly, from an array.

That would also help me in [the Drupal module](https://github.com/drupol/geocoder/tree/8.x-2.x) actually :-)
