### ISSUE TITLE
RFC Sanitizing OOP principles

### ISSUE THREAD

**Issue by jguittard** [geocoder-php/Geocoder#486]
Also see #485 

Moreover, going through the models, they're acting like simple DTO (Data Transfer Object). While I encourage maintaining the class encapsulation and dependency injection, the choice of passing parameters only to the constructor is really limiting to the strict consumption of their use within the library.

It may have been a smart decision at the beginning, yet I'd encourage to **at least** consider parameters to be optional in the constructor **and** to allow either:
- setting the properties through `setters`
- implement `exchangeArray` and `getArrayCopy` like in [Zend ArraySerializableInterface](https://github.com/zendframework/zend-stdlib/blob/master/src/ArraySerializableInterface.php) (or simply `setFromArray(array $array)` and `toArray` methods)

Those _simple_ changes would:
- Follow OOP and SOLID principles
- Allow many extended uses of the library, like the ones I'm currently working on with the [Geocoder Module for ZF2](https://github.com/jguittard/GeocoderModule) where I'm stuck when trying to hydrate the Geocoder entities.

**Comment by dereuromark** [comment]
Yep :+1: 
Absolutely agree that coming from DTOs and alike this will be a huge win.
And also that this would be more SOLID etc.

**Comment by willdurand** [comment]
> where I'm stuck when trying to hydrate the Geocoder entities

What do you mean? I would be interested in understanding/knowing what is problematic?

**Comment by tantegerda1** [comment]
And using `protected` instead of `private` to ease inheritance…

**Comment by unkind** [comment]
So you guys say that:
* setters for value objects makes them follow OOP and SOLID principles;
* coupling models with 3rd party libraries is a good idea;
* inheritance is something that we miss for these value objects.

It goes against OOP principles and SOLID for sure.

**Comment by Nyholm** [comment]
Please review the latest changes is master. Consider Bing or Google Maps provider. Do you have any feedback regarding oop?

**Comment by Nyholm** [comment]
I will close this issue due inactivity. Please feel free to review master and create new issues.
