### ISSUE TITLE
StreetName is not well formatted

### ISSUE THREAD

**Issue by collmomo** [geocoder-php/Geocoder#489]
My Providers:

``` php
        $this->geo = new ProviderAggregator;
        $adapter = new CurlHttpAdapter;
        $providers = array(
            new ArcGISOnline($adapter, "CA"),
            new GoogleMaps($adapter, 'en', 'CA'),
            new OpenCage($adapter, "###########", false, "en"),
            new MapQuest($adapter, "########"),
            new OpenStreetMap($adapter, "en"),
            new Yandex($adapter, "en"),
        );
```

Dump of the Address Model after geocoding:

``` php
Geocoder\Model\Address {#2286
  -coordinates: Geocoder\Model\Coordinates {#2287
    -latitude: 45.509506023
    -longitude: -73.55162252
  }
  -bounds: Geocoder\Model\Bounds {#2288
    -south: null
    -west: null
    -north: null
    -east: null
  }
  -streetNumber: "367"
  -streetName: "367 Rue St-Paul E, Montréal, Québec, H2Y"
  -subLocality: null
  -locality: "Montréal"
  -postalCode: "H2Y"
  -adminLevels: Geocoder\Model\AdminLevelCollection {#2289
    -adminLevels: array:1 [
      1 => Geocoder\Model\AdminLevel {#2285
        -level: 1
        -name: "Québec"
        -code: null
      }
    ]
  }
  -country: Geocoder\Model\Country {#2290
    -name: null
    -code: "CAN"
  }
  -timezone: null
}
```

$address->getStreetName() should be equal to Rue St-Paul E and not that whole string

I can't really tell which provider causes the bug.

**Comment by collmomo** [comment]
Found it, it's arcGis

the dump in provider\ArcGISOnline

```php
{#2264
  +"Loc_name": "CAN.PointAddress"
  +"Score": 100
  +"Match_addr": "367 Rue St-Paul E, Montréal, Québec, H2Y"
  +"Addr_type": "PointAddress"
  +"Type": ""
  +"PlaceName": ""
  +"Place_addr": ""
  +"Phone": ""
  +"URL": ""
  +"Rank": ""
  +"AddBldg": ""
  +"AddNum": "367"
  +"AddNumFrom": ""
  +"AddNumTo": ""
  +"Side": "L"
  +"StPreDir": ""
  +"StPreType": "Rue"
  +"StName": "St-Paul"
  +"StType": ""
  +"StDir": "E"
  +"StAddr": "367 Rue St-Paul E"
  +"Nbrhd": ""
  +"City": "Montréal"
  +"Subregion": ""
  +"Region": "Québec"
  +"Postal": "H2Y"
  +"PostalExt": ""
  +"Country": "CAN"
  +"LangCode": "FRE"
  +"Distance": 0
  +"X": -73.551624
  +"Y": 45.509506
  +"DisplayX": -73.551751
  +"DisplayY": 45.50953
  +"Xmin": -73.552624
  +"Xmax": -73.550624
  +"Ymin": 45.508506
  +"Ymax": 45.510506
}
```
Line 84:
change `$streetName   = !empty($data->Match_addr) ? $data->Match_addr : null;`
with `$streetName   = !empty($data->Match_addr) ? "$data->StPreType $data->StName $data->StDir" : null;` 

Id do a pull request but whatever, it'll take you 10 sec

**Comment by toin0u** [comment]
@collmomo Thank you! Do you mind to make a PR? :)

**Comment by ratibus** [comment]
Hi.
Shouldn't StAddr be used instead ? It seems to already be formatted.

**Comment by Nyholm** [comment]
I agree with you @ratibus. `getStreetName` should use the `StAddr`. Could you send a PR?

**Comment by ratibus** [comment]
I've just submitted a PR but I have a question: should getStreetName should also contain the street number ?

**Comment by Nyholm** [comment]
How does other provider do? Like GoogleMaps provider?

**Comment by ratibus** [comment]
The GoogleMaps provider use the value from the "route" address component that we can see [here](https://maps.googleapis.com/maps/api/geocode/json?address=10%20avenue%20Gambetta%2C%20Paris%2C%20France).
That component does not contain the street number (contained in street_number component).

I guess my current PR is wrong :)

**Comment by DJaeger** [comment]
getStreetName of the MapQuest provider also contains the street number and getStreetNumber is always empty.
I do not think this is the correct behaviour.

**Comment by DJaeger** [comment]
The StreetName of MapQuest is still not well formatted.
As the name of this issue is not ArcGIS specific it should not be closed.

**Comment by Nyholm** [comment]
Sorry. I only changed one provider. Do you mind creating a PR fixing this issue?

**Comment by DJaeger** [comment]
I currently do not know how to do it, but I can dig into this.
If someone is faster, please do it.

**Comment by Nyholm** [comment]
I have reviewed all providers `streetName` now. They all are well formatted. 

Please feel free to open a new issue if you found that I am misstaken.
