### ISSUE TITLE
[Feature] getProvidedBy() in the Address Model when geocoding and chaining

### ISSUE THREAD

**Issue by collmomo** [geocoder-php/Geocoder#490]
When using the Chain Class and geocoding, sometimes some providers are good, others are not. As of now there's the no easy way to know which provider did geocode the sent address.

Could it be possible to add `$address->getProvidedBy();`

**Comment by toin0u** [comment]
@collmomo Have you tried this? https://github.com/geocoder-php/Geocoder/issues/425

**Comment by stevevance** [comment]
I asked for this feature a year or two ago and the response was "Why would you need to know this?"
One reason is to know the quality of the response of each provider and see if there's a pattern – and doing so without trying out each provider individually. 

I looked at #425 and it's not very intuitive for me to know where to put that code.

**Comment by collmomo** [comment]
Basically, its telling you to extend the provider aggregator and change the return answer or cache the game in another variable and then get it. It's a good temporary solution.

**Comment by aight8** [comment]
Please implement this.

**Comment by Nyholm** [comment]
Im about to write a PR for this. Should the `getProvdedBy()` be on the `Geocoder\Collection` or the `Geocoder\Location`?

There is rarely a case where you have a Collection for Locations from different providers, right?
