### ISSUE TITLE
Include @throws in Geocoder interace geocode/reverse method docblock

### ISSUE THREAD

**Issue by benglass** [geocoder-php/Geocoder#491]
If the recommended way of determining if there were errors during geocoding is to catch exceptions throw by the providers inside the Geocoder it would make reading the code more instructive to include an @throws annotation on the geocode/reverse methods and perhaps a @see method indicating where to look to understand how errors are handled

**Comment by willdurand** [comment]
I am fine with that.

**Comment by benglass** [comment]
@willdurand Ok I will get a PR together thanks for the quick response
