### ISSUE TITLE
Get provider used in ProviderAggregator

### ISSUE THREAD

**Issue by LeftPinkie** [geocoder-php/Geocoder#494]
If I have multiple providers using ProviderAggregator, how do I get which provider return the geocode data?

**Comment by toin0u** [comment]
@LeftPinkie Which version are you using?

**Comment by toin0u** [comment]
@LeftPinkie you need to use the `using()` method otherwise it uses the first registered provider.

**Comment by LeftPinkie** [comment]
I am using v3.3.0. I understand about the `using()` method.  What I would like to know if is there is a way to determine which provider returned the geocode data if I have multiple providers.

**Comment by toin0u** [comment]
@LeftPinkie Ah sorry I understand now - you're using the chain provider :) Have you tried this? https://github.com/geocoder-php/Geocoder/issues/425

**Comment by LeftPinkie** [comment]
Nice! Sorry I didn't see that post on my original search.  Thanks!

**Comment by toin0u** [comment]
@LeftPinkie No problem! You're welcome. I think we need to implement this feature :)

**Comment by LeftPinkie** [comment]
Yes, I agree / would like to see this method made available in next release.  Is there a list of enhancements that I can vote on? Would like to contribute but not a great programmer... still trying to figure out how to extend the class to implement this work around. I am new to oop but reading up on it as much as I can.

**Comment by toin0u** [comment]
We don't have that but we have a feature request here https://github.com/geocoder-php/Geocoder/issues/490

Do not hesitate to contribute and if you need any help just poke us. I think it's not a good idea to start to work on this feature as we need to decide if we should do it or not to not waste your time :)

If you're new in OOP - I can advice you to read those slides http://edu.williamdurand.fr/php-slides/#slide20 and http://www.phptherightway.com/ (a more general stuff about PHP)

**Comment by LeftPinkie** [comment]
Sorry for all the noob questions and thanks very much for your patience.  I have tried extending the class `ProviderAggregator`.  I can get the `AddressCollection` object but I get null for either the `key($this->providers)` or `$this->providers`.  Can you tell me what I am doing wrong?

Here's my code:
```
class TestProvider extends \Geocoder\ProviderAggregator {
	public function geocode( $value ) {
		$name = key($this->providers) ; // Here is the name of the current provider.
		$result = parent::geocode( $value ) ;

		return $result ;
//		return key($this->providers) ; // returns NULL
//		return $this->providers ; // returns NULL
	}
}
$test_geocoder = new TestProvider() ;
$test_geocoder -> registerProvider( $chain ) ;
$result = $test_geocoder -> geocode( '123 Main St, Anytown USA' ) ;
$address = $result -> first() ;
var_export( $address ) ;
```
