### ISSUE TITLE
Random coordinates

### ISSUE THREAD

**Issue by christophrumpel** [geocoder-php/Geocoder#495]
Hey,

is there a built-in functionality to get random coordinates?

I would need to get a random location inside a specific country.
Cheers

Christoph

**Comment by Baachi** [comment]
Hey @christophrumpel 

no there is no built-in functionality to get random coordinates. This library offers only a way to geocode addresses, places or hostnames.
Maybe you can grab random places and then geocode them with this library.

Hope it helps!

**Comment by christophrumpel** [comment]
Ok thx for letting me know.
