### ISSUE TITLE
Wrong exception thrown

### ISSUE THREAD

**Issue by theofidry** [geocoder-php/Geocoder#497]
The `Geocoder` interface specifies that calling the `geocode()` function can throw a `Geocoder\Exception\Exception` exception. However after using the `FreeGeoIp` provider with the Ivory `CurlHttpAdapter`, I got in some cases a `Ivory\HttpAdapter\HttpAdapterException` exception thrown, which is not an instance of `Geocoder\Exception\Exception`.

When checking the code, we can see [here](https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Provider/FreeGeoIp.php#L68) that the Ivory adapter is being used without any try/catch, hence any exception thrown by the adapter breaks the `Geocoder::geocode()` interface - at least for `FreeGeoIp`. I did not check for the other providers.

**Comment by willdurand** [comment]
Oh good catch! Could you write a patch for that?

**Comment by Nyholm** [comment]
Closed by #617
