### ISSUE TITLE
Dependeny on abandoned package egeloen/http-adapter 

### ISSUE THREAD

**Issue by thomaspreiss** [geocoder-php/Geocoder#498]
The package egeloen/http-adapter is marked as abandoned and will no longer maintained. Switch to php-http/httplug package.

Do you see any criticals here or should it be safe to use for now?

**Comment by egeloen** [comment]
It is marked as abandonned in order to promote HttPlug, but I still maintain it for security reasons. So, don't worry for now and AFAIK, there is WIP about moving to HttPlug (#487)

**Comment by thomaspreiss** [comment]
Thank you!!
