### ISSUE TITLE
Fail to install version 2.8

### ISSUE THREAD

**Issue by remyLemeunier** [geocoder-php/Geocoder#515]
Hello,
since this morning we can't install the version 2.8 anymore.
You can reproduce this using this exemple:
```{
    "name": "composer-test/composer-test",
    "require": {
        "willdurand/geocoder": "~2.8"
    }
}```
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package willdurand/geocoder ~2.8 is satisfiable by willdurand/geocoder[2.x-dev] but these conflict with your requirements or minimum-stability.
```
Best regards.

**Comment by Nyholm** [comment]
It seams like all the stable releases have disappeared from Packagist. https://packagist.org/packages/willdurand/Geocoder

Maybe @Seldaek knows what happened?

**Comment by giannidhooge** [comment]
+1

**Comment by artjomsimon** [comment]
Seems to be a packagist issue, more packages are having this isue:
https://twitter.com/klatys/status/754747942897061889

**Comment by willdurand** [comment]
I **manually** updated the whole project on Packagist. Should be better now.

**Comment by artjomsimon** [comment]
@willdurand Thank you, works as expected again! :+1:

**Comment by pylebecq** [comment]
@willdurand @Nyholm Thank you guys for your quick help :-)

**Comment by willdurand** [comment]
Good to read. Thank you all!

**Comment by remyLemeunier** [comment]
Thanks a lot guys !
