### ISSUE TITLE
Impossible to get subway station name in Yandex provider

### ISSUE THREAD

**Issue by reticulum** [geocoder-php/Geocoder#532]
When you requesting reverse geocoding with Yandex provider, using a 'metro' toponym, you can't get station name.  Original API URL: https://geocode-maps.yandex.ru/1.x/?geocode=30.324285,%2060.036843&kind=metro&format=json
You can't get "PremiseName" using Geocoder now.

**Comment by Nyholm** [comment]
Related to #533
