### ISSUE TITLE
Unable to get 'region' and 'precision' components from resultSet ('GoogleMaps')

### ISSUE THREAD

**Issue by RomanPerekhrest** [geocoder-php/Geocoder#533]
How to get 'region' and 'precision' components from resultSet ('GoogleMaps') ?

**Comment by Nyholm** [comment]
Related to #532

**Comment by Nyholm** [comment]
We need to add "region" to `GoogleAddress`. Ping @svrdlic. Can you do a PR?

**Comment by svrdlic** [comment]
sure :)

**Comment by svrdlic** [comment]
Ping @RomanPerekhrest   ‘region’  is optional query parameter, not component from resultset, as you can see in docs https://developers.google.com/maps/documentation/geocoding/intro#RegionCodes
 
Could you provide additional information about issue?

**Comment by Nyholm** [comment]
Thank you Svrdlic. 

Im closing this since Google does not offer any data for 'region' and 'precision'
