### ISSUE TITLE
RFC: GeoIp2 Provider AuthenticationException and OutOfQueriesException

### ISSUE THREAD

**Issue by redthor** [geocoder-php/Geocoder#534]
I'm looking at using the GeoIp2 provider for the Maxmind Web Service.

I notice that there is only an adaptation of the `GeoIp2\Exception\AddressNotFoundException` to the `Geocoder\Exception\NoResult` here:
https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Provider/GeoIP2.php#L107

Would it be good to convert some of the others? For example:

``` php
        try {
            $result = $this->adapter
                ->setLocale($this->locale)
                ->getContent($uri);
        } catch (AddressNotFoundException $e) {
            throw new NoResult(sprintf('No results found for IP address "%s".', $address));
        } catch (AuthenticationException $e) {
            throw new InvalidCredentials(
                sprintf(
                    'There was an error with your maxmind userId and license key. Upstream error is [%s]',
                    $e->getMessage()
                )
            );
        } catch (OutOfQueriesException $e) {
            throw new QuotaExceeded(
                sprintf(
                    'You have run out of queries. Upstream error is [%s]',
                    $e->getMessage()
                )
            );
        }
```

I can imagine (and I think I've read before, but now I can't remember where) a use case where it would be beneficial to catch the `QuotaExceeded` exception and at least return a stale cache value.

**Comment by Nyholm** [comment]
I like this suggestion. Could you create a PR?

**Comment by redthor** [comment]
Yes, I'll look into it. Given the :christmas_tree: season, it may not be until the back half of Jan.

**Comment by Nyholm** [comment]
Okey, it is the far opposite for me =) I will take time to do loads of open source during the holidays. =)

Enjoy your Christmas. Im looking forward to your PR in January.

**Comment by Nyholm** [comment]
Any updates here?

**Comment by Nyholm** [comment]
Ping

**Comment by Nyholm** [comment]
I will close this issue in mid July if there is no interest for it.

**Comment by redthor** [comment]
Is this heading the right way?
https://github.com/redthor/Geocoder/commit/87ca2d8a0a0ed55e1172b42bd17b270b34426700

**Comment by Nyholm** [comment]
This looks excellent. Just add a few more and create a PR. I will be happy to review it. 

A thought: Maybe not `convertException` is needed? We could use the different catch instead.
