### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jonashaag** [geocoder-php/Geocoder#535]
The last release is almost a year old, and that version doesn't even work for one of the most common use cases anymore: Google Maps integration, because the recommended CURL adapter is deprecated and throws SSL errors: 

```
Ivory\HttpAdapter\HttpAdapterException with message 'An error occurred when fetching the URI "https://maps.googleapis.com/maps/api/..." with the adapter "curl" ("SSLRead() return error -9806").'
```

Using the Guzzle client recommended here in the README doesn't work with that version either:

```
TypeError: Argument 1 passed to Geocoder\Provider\GoogleMaps::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, instance of Http\Adapter\Guzzle6\Client given
```

**Comment by willdurand** [comment]
Hi! Latest version is [3.3.0](https://github.com/geocoder-php/Geocoder/releases/tag/v3.3.0).

We are working on 4.0 now, which will change the way HTTP is managed. So, this is in the pipe...
In the meantime, if we can do something for 3.x, like fixing the bug you described, maybe we could release a minor version (3.4.0). Could you describe your problem in another issue? Or maybe even come up with a patch and Pull Request? Thanks!
