### ISSUE TITLE
Google Maps HTTP/SSL broken for 3.3.0

### ISSUE THREAD

**Issue by jonashaag** [geocoder-php/Geocoder#536]
Example from the docs:

```
$geocoder = new \Geocoder\Provider\GoogleMaps(
    new \Ivory\HttpAdapter\CurlHttpAdapter(),
    "de", "de", /*ssl*/true,
    "XXXX"
);
$geocoder->geocode(...);
```

```
Ivory\HttpAdapter\HttpAdapterException with message 'An error occurred when fetching the URI "https://maps.googleapis.com/maps/api/..." with the adapter "curl" ("SSLRead() return error -9806").'
```

Disabling SSL doesn't work with Google Maps.

Using the Guzzle client recommended here in the README doesn't work with that version either:

```
TypeError: Argument 1 passed to Geocoder\Provider\GoogleMaps::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, instance of Http\Adapter\Guzzle6\Client given
```

Operating system: macOS sierra
Geocoder version: 3.3.0

**Comment by Nyholm** [comment]
We are soon about to push a new major version. Do you have the same issue with dev-master?

**Comment by jonashaag** [comment]
No

**Comment by Nyholm** [comment]
Could this issue be closed since it is fixed in master?

**Comment by jonashaag** [comment]
When are you releasing the next major version?

**Comment by Nyholm** [comment]
As soon as possible. There are a few things we need to do first: https://github.com/geocoder-php/Geocoder/milestone/3

Join the discussion and it will go faster. Have a look at this PR: https://github.com/geocoder-php/Geocoder/pull/529

**Comment by jonashaag** [comment]
Ok then!
