### ISSUE TITLE
Make provider classes finalised

### ISSUE THREAD

**Issue by vicchi** [geocoder-php/Geocoder#537]
All provider class constructors should be finalised; see https://github.com/geocoder-php/Geocoder/pull/531#discussion_r79915180 for context.

**Comment by unkind** [comment]
For clarity, the original discussion was about classes.

**Comment by Nyholm** [comment]
Why would we make providers final? I guess some people extend our provider class to just to some minor change.

Also, we can not make `GoogleMaps` final because our `GoogleMapsBusiness` inherits form that. Same with `Nominatim` and `OpenStreetMap`.

**Comment by unkind** [comment]
> Also, we can not make GoogleMaps final because our GoogleMapsBusiness inherits form that. Same with Nominatim and OpenStreetMap.

Why they use inheritance? Why `GoogleMaps` can't have optional named constructor like `business`, e.g. `GoogleMaps::business()` with `clientId` and `privateKey`? Why `OpenStreetMap` extends `Nominatim`, just for default value of `rootUrl`? Is it possible to replace it with `Nominatim::defaultServer()` or simply pass it from configuration file?

> Why would we make providers final? I guess some people extend our provider class to just to some minor change.

In general, inheritance should be avoided in favour of composition.

If you look at the providers, in most cases they don't have any `protected` members, there is no place for inheritance here. If somebody still wants to use it, he probably makes design mistake. Do you really want to keep BC for users with design issues?

After all, in case of emergency, if user needs to fix something quick, he can create completely new implementation by copy-pasting original one. And he also can send patch for new extension point of existing provider or bugfix.

**Comment by willdurand** [comment]
I like the idea of making the providers `final` but as @Nyholm said, we have inheritance. Maybe we could compose these providers instead of using inheritance, but it might not be worth doing it.

**Comment by Nyholm** [comment]
I do not have an opinion in the matter. Im just asking =)

I like your arguments @unkind. Do you want to make a PR trying to solve the GoogleMaps/Nominatim issues or should I?

@willdurand: We can try and see if it is worth doing. =)

**Comment by Nyholm** [comment]
Closed by #540
