### ISSUE TITLE
PluginClient to implement HttpAdapterInterface (Cookbook Caching Responses)

### ISSUE THREAD

**Issue by jpastoor** [geocoder-php/Geocoder#541]
I have a question regarding the example:
https://github.com/geocoder-php/Geocoder/blob/master/docs/cookbook/cache.md

With the current libs versions it seems that the GoogleMaps Provider expects a Ivory\HttpAdapter\HttpAdapterInterface, but the PluginClient only implements Http\Client\HttpClient and Http\Client\HttpAsyncClient. 

I cannot see a way to adapt one to the other. Any tips/clues?

Related installed packages and versions:
php-http/cache-plugin             v1.2.0  PSR-6 Cache plugin for HTTPlug
php-http/client-common            1.3.0   Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                v1.0.0  Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter          v1.1.1  Guzzle 6 HTTP Adapter
php-http/httplug                  v1.1.0  HTTPlug, the HTTP client abstraction for PHP
egeloen/http-adapter              0.8.0   Issue HTTP request for PHP 5.3+.
guzzlehttp/guzzle                 6.2.2   Guzzle is a PHP HTTP client library
guzzlehttp/promises               1.2.0   Guzzle promises library
guzzlehttp/psr7                   1.3.1   PSR-7 message implementation
cache/adapter-common              0.3.3   Common classes for PSR-6 adapters
psr/cache                         1.0.1   Common interface for caching libraries
willdurand/geocoder               v3.3.0  The almost missing Geocoder PHP 5.4 library.

**Comment by Nyholm** [comment]
Hey. 
Very good question. We are soon about to tag a new release. The latest version and master are quite different. Please try dev-master. That should work flawlessly with the cookbook entry.

**Comment by willdurand** [comment]
That is a documentation problem then :(

**Comment by Nyholm** [comment]
No, not at all. It is a version mixup problem. 

Here is the documentation for dev-master: https://github.com/geocoder-php/Geocoder
Here is a documentation for 3.3.0 that @jpastoor is using: https://github.com/geocoder-php/Geocoder/tree/v3.3.0

The issue is that @jpastoor is using 3.3.0 but reading docs for dev-master.

**Comment by willdurand** [comment]
Yes, that's my point. The documentation is not accurate because it says it is the documentation for Geocoder 3.x, which is not true anymore. See #542

**Comment by Nyholm** [comment]
You are correct. Thank you.

**Comment by jpastoor** [comment]
Thanks a lot for clearing that up. Switching to master resolved the issue indeed and docs are clearer now :)
