### ISSUE TITLE
[Docs] Error in a link in the Geocoder documentation

### ISSUE THREAD

**Issue by JaimeChavarriaga** [geocoder-php/Geocoder#544]
In the Geocoder documentation (at Github Pages), there is a link in the table of content that does not work:  The _"Address & AddressCollection"_ link does not work

- The `href` in the source code goes to `#address--addresscollection`
- but the generated HTML uses the id `#address-amp-addresscollection`

**Comment by vicchi** [comment]
+1 LGTM
