### ISSUE TITLE
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

### ISSUE THREAD

**Issue by vinyvicente** [geocoder-php/Geocoder#548]

**Comment by Nyholm** [comment]
Yes, we have fixed that in dev-master.

**Comment by curry684** [comment]
But the last stable release dates back to December 2015. Changes in dev-master aren't helping people writing production quality software until they make a stable release...

**Comment by Nyholm** [comment]
You are correct. Please help the community to finish the [milestone for 4.0.0](https://github.com/geocoder-php/Geocoder/milestone/3). Im happy to put in some work but I need feedback on my PRs and issues.

**Comment by egeloen** [comment]
@curry684 Don't worry too much, I still maintain `egeloen/ivory-http-adapter`. Deprecated does not mean buggy or broken (I have trigger a build this week-end and everything is still green). I have just mark it as abandonned in order to inform people they need to move forward as there is a better solution namely Httplug.

**Comment by curry684** [comment]
@Nyholm not really in a position to help yet, I was setting up a new project which will need geocoding at some time, hit the "abandoned" message and started investigating as using abandoned software is not something I can sell my customer in this (enterprisey stability requirements). I'm not at home at all in the library yet so my help isn't worth much at this point in time.

@egeloen thanks for confirming the state is actually deprecated and the library is still being maintainted. That will do for now to silence my customers  ;)

**Comment by Nyholm** [comment]
> @Nyholm not really in a position to help yet...

That is great. Im looking forward to work with you later. All help is always appreciated.

**Comment by vinyvicente** [comment]
Hello, I would work on this if we can. Already exists another issue about this?

**Comment by Nyholm** [comment]
This issue is already fixed in master. 

Have a look at issues in https://github.com/geocoder-php/Geocoder/milestone/3. An easy way to get started is to write comments/feedback on open issues and PRs.

**Comment by vinyvicente** [comment]
Okay, if you needs more work, I'm here, o/

Thanks, advance.
