### ISSUE TITLE
Undefined method Geocoder\Model\AddressCollection

### ISSUE THREAD

**Issue by sarment0** [geocoder-php/Geocoder#549]
`$curl     = new \Ivory\HttpAdapter\CurlHttpAdapter();
$geocoder = new \Geocoder\Provider\GoogleMaps($curl);
$address = $geocoder->geocode("Address of my house, sao paulo, brazil");
$coord = $address->getCoordinates();`

PHP Fatal error:  Call to undefined method Geocoder\Model\AddressCollection::getCoordinates()

I followed the 3.3 documentation and i had this bug, what i'm doing wrong?

**Comment by willdurand** [comment]
You get a collection, which is a set of adresses. Each address gets coordinates, but the collection is just a set/array, without any coordinates. You should, for instance, get the first address of the collection with `$coll->first()`

**Comment by willdurand** [comment]
Sorry if it was not clear enough in the doc..

**Comment by Nyholm** [comment]
Im closing this PR because of inactivity and that William's answer will resolve the issue.
