### ISSUE TITLE
Question to Bounds 

### ISSUE THREAD

**Issue by arubacao** [geocoder-php/Geocoder#554]
I've got a question regarding the coordinates format in the [`Bounds` Model](https://github.com/geocoder-php/Geocoder/blob/0014c0ba480811fb2066d0fd23add1774e70118e/src/Geocoder/Model/Bounds.php).

I've never seen this format before:

```
  -bounds: Geocoder\Model\Bounds {#456
    -south: 48.139682
    -west: 11.5384689
    -north: 48.1580821
    -east: 11.5876321
  }
```

shouldn't it be more like (or similar): 

```
  -bounds: Geocoder\Model\Bounds {#456
      -southwest: Geocoder\Model\Coordinates {#429
        -latitude: 48.139682
        -longitude: 11.5384689
    }
      -northeast: Geocoder\Model\Coordinates {#428
        -latitude: 48.1580821
        -longitude: 11.5876321
    }
  }
```
Thanks for the great library!
Cheers,
Chris

**Comment by willdurand** [comment]
That would make sense indeed.

**Comment by unkind** [comment]
OSM uses this format, for example: http://wiki.openstreetmap.org/wiki/Bounding_Box

**Comment by arubacao** [comment]
Hm, I guess if OSM uses it and nobody else compliant about it in 2 years, it's 🆗 👌
