### ISSUE TITLE
Wrong Address model getters docs

### ISSUE THREAD

**Issue by norkunas** [geocoder-php/Geocoder#556]
I have a doctrine entity named `Location` and event listener which sets geocoded values on it.
For example:
```
    /**
     * Returns the city or locality value.
     *
     * @return string
     */
    public function getLocality()
    {
        return $this->locality;
    }
```
This states that it returns only a string, so I expect that it always returns a string and not null, but I've got this:
`[2016-12-15 10:12:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Location::setLocality() must be of the type string, null given`

**Comment by Nyholm** [comment]
You are correct. We should update the doc block to be more clear that it can return null.
