### ISSUE TITLE
Problem with company location

### ISSUE THREAD

**Issue by soclosed** [geocoder-php/Geocoder#557]
Hi,

I have a problem with a company location. With this:
`$geocoder->geocode("Rue Jean Rostand, Labège, France")`
there is a result. But with this:
`$geocoder->geocode("IOT Valley, Rue Jean Rostand, Labège, France")`
there is no result. It's an existing location, Google suggests it when i fill the field.

Any ideas?

Regards

**Comment by Nyholm** [comment]
I **think** this is related to #447. We do not currently support places. #447 will fix that.

**Comment by Nyholm** [comment]
I have created an issue for requesting a new Google Maps places provider ( #711 ). At the moment there is nothing we can do on our side.

**Comment by soclosed** [comment]
Great thanks
