### ISSUE TITLE
Add cached responses for Maxmind API

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#570]
This is an easy pick for the one with a maxmind API key. 

How to do it: 
1) Copy phpunit.xml.dist to phpunit.xml
2) Just add your API key in the phpunit.xml
3) Run the test suite. 
4) Commit the new cached responses in tests/.cached_responses. 
5) Uncomment the dummy value for maxmind in phpunit.xml.dist

If there is any bugs when running the test suite. Either you fix them or let someone else fix them. The important thing is that we get the cached response so we can do some testing.

**Comment by atymic** [comment]
So I was looking into this, and it seems that maxmind no longer offers access to the v1 api for new customers
https://dev.maxmind.com/geoip/legacy/

If you'd like I can create a PR to update the library to use the V2 geoip API.
https://dev.maxmind.com/geoip/geoip2/web-services/

**Comment by jbelien** [comment]
Thanks @atymic that would be awesome ! 👍

**Comment by atymic** [comment]
So after doing some research, we already have a `GeoIp2` provider which supports using the web service.

Maybe we should consider deprecating the `MaxMind` provider, as the legacy api is no longer recommend?

**Comment by jbelien** [comment]
There is indeed a `GeoIP2` provider (mentioning the webservice) but after a quick look I couldn't find any reference to the webservice in the code itself.

If you have a moment, could you have a look ?
Thanks a lot !

**Comment by atymic** [comment]
I'll submit a PR to update the documentation to make it clearer.
Unfortunately I don't think we can add an API test, as there's no way to mock it.

**Comment by atymic** [comment]
@jbelien I think we can close this, as the maxmind v1 API can't be accessed to get the response

**Comment by atymic** [comment]
cc @jbelien :)
