### ISSUE TITLE
Allow extending of models

### ISSUE THREAD

**Issue by ddinchev** [geocoder-php/Geocoder#575]
In my geo-aware app, I do need to use primitive geo models like `Coordinates` or `Bounds` a lot. I prefer not to keep a copy of those in my app. Instead, I'd like to extend the ones provided by the geocoder library (without redefining anything) so it would be easier to swap the underlying implementation at some later moment, if necessary. However the classes provided by geocoder lib are final, so they can not be extended.

Is there a specific reason that they are final and is it possible to open them up for 4.0 release?

**Comment by Nyholm** [comment]
Thank you for this issue. 
I do not really understand your scenario. You want an object implementing Location but without Coordinates and Bounds, right? How would you solve this by extending our Location? If you want to wrap our objects to be able to swap things out, wouldn't composition be better?

**Comment by ddinchev** [comment]
So, I want to use`Coordinates` object, I also want to use `Bounds` object. Not only for purposes to interact with `Geocoder` but also for my own app business logic. However, I do not want my own classes around the app to depend on `Geocoder\Coordinates`, instead, I would want them to depend on `myapp\geo\Coordinates` for example, which just extends `geocoder\Coordinates` without redefining any of the underlying logic.

This way, if at some point I get rid of `Geocoder` I would just have to fill my own classes, instead of having to fix references to this external library all over the code. I hope this is more clear.

**Comment by ddinchev** [comment]
@Nyholm did my explanation/use case make sense?

**Comment by Nyholm** [comment]
I understand your use case but I think you are solving it wrong. You want your application to be decoupled from the Geocoder. But by using inheritance you are still affected to changes in the Geocoder library. 

Your approach also violates the *composition of inheritance principle*. What you should do is either make a business decision to couple your code to the Geocoder or write your own `PHPGeocoderAdapter` (not "provider") that your application is coupled to. You will also need adapter classes for `Coordinates`, `Bounds` etc. Those classes could use composition or you just copies the values from `PHPGeocoderBounds` to `MyAppBounds`

**Comment by ddinchev** [comment]
@Nyholm actually I agree and already started such a solution (where I keep instances of `PHPGeocoder` models as internal structures in my adapters but don't expose their API). I'm closing the issue and I want to thank you for taking the time to reply!

**Comment by Nyholm** [comment]
Thank you for challenging this. I believe there a many more that are struggling with this issue. 

👍
