### ISSUE TITLE
How to set google API key ?

### ISSUE THREAD

**Issue by matdev** [geocoder-php/Geocoder#582]
Hello
I am using your library to do some reverse geocoding. 
How can I include my Google API key in google geocoding's URL ?
Here is the code I am using:

```
$adapter = new \Http\Adapter\Guzzle6\Client();
$geocoder = new \Geocoder\Provider\GoogleMaps($adapter);
$addresses = $geocoder->reverse($this->lat, $this->lng);
```

**Comment by egeloen** [comment]
Take a look to the [`GoogleMaps`](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/GoogleMaps.php#L84) provider constructor. The api key is the 4th arguments.

``` php
$geocoder = new GoogleMaps($adapter, null, null, $apiKey);
```

**Comment by matdev** [comment]
it works :)
Thanks A lot @egeloen !
