### ISSUE TITLE
FreeGeoIP auto detect public IP

### ISSUE THREAD

**Issue by stelgenhof** [geocoder-php/Geocoder#590]
The FreeGeoIP service allows to have your (public) IP address to be auto detected by simply leaving it out of the API call. The GeoCoder Provider class however requires a valid IP address for its argument. 

Would it be possible to have the IP address optional?

**Comment by Baachi** [comment]
Why do you need this feature? You can just use `$_SERVER['SERVER_ADDR'];` to get the ip adresse from the current server.

**Comment by stelgenhof** [comment]
I would like to use it running in CLI mode. `$SERVER['SERVER_ADDR']` is not populated when running PHP from the CLI.

**Comment by Nyholm** [comment]
Im closing this issue since the FeeGeoIp does not have any requirement on your IP anymore.
