### ISSUE TITLE
Can `Address Line 2` field (or similar) be added?

### ISSUE THREAD

**Issue by mikebronner** [geocoder-php/Geocoder#593]
@ellisio posted in the GeocoderLaravel issues list (https://github.com/geocoder-php/GeocoderLaravel/issues/52) the following request:

> When parsing an address with an apartment number, you receive a "Subpremise" attribute. This attribute is typically mapped to an "Address Line 2".
>
> For example: https://maps.googleapis.com/maps/api/geocode/json?address=2123%20W%20Mineral%20Ave%20Apt%2061,%20Littleton,%20CO%2080120
>
> It would be nice to have this added as the subpremise on the Address object.

Is this something you would consider adding? Or any thoughts on work-arounds?

Thanks!
~Mike

**Comment by Nyholm** [comment]
Does it make sense to add "getSubpremise" to the GoogleAddress? When/how often does subpremise exist in the response from google?

Ping @svrdlic

**Comment by svrdlic** [comment]
From google maps docs: subpremise indicates a first-order entity below a named location, usually a singular building within a collection of buildings with a common name.

‘Subpremise’ is what Google Maps return in case that query address contains Apt/Suite/Unit number. I think it wont hurt if we add this, if someone adds it in query, it would be nice to get it back :)

**Comment by Nyholm** [comment]
Okey, good. 

Can you submit a PR that adds supremise to the `GoogleAddress`?

**Comment by svrdlic** [comment]
Sure

**Comment by Nyholm** [comment]
Closed by #657
