### ISSUE TITLE
Release 3.4 ?

### ISSUE THREAD

**Issue by drupol** [geocoder-php/Geocoder#594]
Hi,

What's left to do before the new 3.4 release ?
I woud like to release the Drupal module using the 3.4 release and I'm waiting for it.

Thanks.

**Comment by Nyholm** [comment]
Hey. 
Next release is going to be 4.0.0. See our milestone: https://github.com/geocoder-php/Geocoder/milestone/3

Im happy to put in some work and push towards this release but I do need feedback and people reviewing my PRs. 
Have a look at #583 and #578. After those 2 has been decided on the rest of the issues will be pretty quick.

**Comment by Nyholm** [comment]
I've just released 4.0.0-beta1. You should consider using that version.
