### ISSUE TITLE
Nominatim provider

### ISSUE THREAD

**Issue by DJaeger** [geocoder-php/Geocoder#598]
Why is it not possible to set the zoom within the constructor of the nominatim (OpenStreetmap) provider?

**Comment by Nyholm** [comment]
Providers should be stateless. There should be an option to use a Query object to set the default zoom. 
I've added this to the 4.0 milestone.

**Comment by DJaeger** [comment]
That would be nice.
Could this also be added to the 3.x tree?

**Comment by Nyholm** [comment]
No, sorry. Not in any good way. That is why we need 4.0.

**Comment by DJaeger** [comment]
:+1:
