### ISSUE TITLE
GoogleMaps constructor inconsistency?

### ISSUE THREAD

**Issue by artiegold** [geocoder-php/Geocoder#605]
Looking at 
Geocoder\Provider\GoogleMaps::business
and 
Geocoder\Provider\GoogleMaps::__construct

something has to be out of whack (note the use of the constructor in the static 'business' method).

    public static function business(HttpClient $client, $clientId, $privateKey = null, $locale = null, $region = null, $apiKey = null)
    {
        $provider = new self($client, $locale, $region, $apiKey);
        $provider->clientId = $clientId;
        $provider->privateKey = $privateKey;

        return $provider;
    }

    /**
     * @param HttpClient $client An HTTP adapter
     * @param string     $region Region biasing (optional)
     * @param string     $apiKey Google Geocoding API key (optional)
     */
    public function __construct(HttpClient $client, $region = null, $apiKey = null)
    {
        parent::__construct($client);

        $this->region = $region;
        $this->apiKey = $apiKey;
    }

**Comment by Nyholm** [comment]
You are correct. That is weird. The constructor is correct but not the `business` method or signature. We should remove the locale. 

Can you send a PR for this?
