### ISSUE TITLE
Unable to easily extend FreeGeoIp Provider

### ISSUE THREAD

**Issue by funkflute** [geocoder-php/Geocoder#607]
I am hosting my own version of the FreeGeoIp code (as described from their website), I tried to extend the FreeGeoIp provider and make the only change altering the ENDPOINT_URL, pointing locally. But since

https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/FreeGeoIp.php#L44

uses self::ENDPOINT_URL instead of static::ENDPOINT_URL I have to duplicate the entire class and code, because I kept getting the extended class' URL, not mine. Wondering if this is something that could be changed to allow for better extension of this (or any) provider?

**Comment by Nyholm** [comment]
Thank you for the issue. 

Tell me more about you scenario, why would you like to change the URL?

**Comment by funkflute** [comment]
Sure, we have a high-load server that we use the ip-based geolocation for, but the traffic is higher than the FreeGeoIp.net site will allow. So, we run our own version of their software (using their pre-compiled binaries) locally on each node of our web cluster. So it works exactly the same as freegeoip.net and there's no limit to the number of calls. Only difference in the code is the ENDPOINT_URL, so I just created an extended class of the provider:

```
<?php namespace App\Providers;

use Geocoder\Provider\FreeGeoIp;

class LocalGeoIpProvider extends FreeGeoIp {
    const ENDPOINT_URL = 'http://localhost:8080/json/%s';
}

```

but when the url is retrieved in the geocode() method, self::ENDPOINT_URL returns the parent (freegeoip.net) url. and I can't just override the geocode() method, because executeQuery is a private function. static:ENDPOINT_URL would return the constant from this class, rather than the parent class.

**Comment by Nyholm** [comment]
Ping @unkind, do you have an opinion here?

**Comment by unkind** [comment]
`new LocalGeoIpProvider(..., 'http://localhost:8080/json/%s')`?

**Comment by Nyholm** [comment]
Thank you for the suggestion. I've created a PR for this.
