### ISSUE TITLE
Google Maps: fails to populate country for "Ireland"

### ISSUE THREAD

**Issue by norkunas** [geocoder-php/Geocoder#641]
http://maps.googleapis.com/maps/api/geocode/json?address=Ireland&language=en
http://maps.googleapis.com/maps/api/geocode/json?address=Netherlands&language=en

Geocoding netherlands properly returns "country" in address components, while Ireland returns "establishment" instead and `updateAddressComponent` fails to populate the country name. Is there an easy way to workaround this? Because this violates `Geocoder\Model\Country::getName()` return type

**Comment by Nyholm** [comment]
I do not quite understand. But aren't you saying that this is an error on Google?

**Comment by norkunas** [comment]
I don't know if this is an error on google, but I expect that Ireland like other countries should be properly populated :)

**Comment by arubacao** [comment]
The geocoder library relies on external services. If external services like googlemaps do not return satisfactory results, it is not the fault of geocoder. 
That being said, api calls to googlemaps can (and should) be more explicit: 
https://developers.google.com/maps/documentation/geocoding/intro?hl=en#ComponentFiltering
PRs #619 and #620 now support this functionality

**Comment by Nyholm** [comment]
Thank you @arubacao 

I will close this issue.
