### ISSUE TITLE
Replace egeloen/http-adapter dependency for php-http/httplug

### ISSUE THREAD

**Issue by pedropapa** [geocoder-php/Geocoder#642]
As egeloen/http-adapter project on github (https://github.com/egeloen/ivory-http-adapter) states, you should replace it for the php-http/httplug package, since egeloen/http-adapter is now abandoned. Composer also started warning packages that contains egeloen/http-adapter with _"Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead."_ message.

**Comment by Nyholm** [comment]
Thank you. This has actually already been done. Check out the master branch. We are dong our very best to make sure to release this change in and many more in 4.0. See https://github.com/geocoder-php/Geocoder/milestone/3
