### ISSUE TITLE
Separate HTTP providers

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#681]
About 40% of the providers we currently have in this lib does not require HTTP. The common package should therefore not require PSR7 and HTTPlug stuff. However, there is one class in common (`AbstractHttpProvider`) that is depending on HTTP stuff. 

We could:
A) Ignore the dependencies of this class and move all `php-http/*` requirements to the providers. 
B) Create a new package `geocoder-php/common-http` which has all `php-http/*` requirements and the `AbstractHttpProvider`. 

I think we should do B since it is better package design. `AbstractHttpProvider` is really an outlier in common.

**Comment by arubacao** [comment]
B) ✅
