### ISSUE TITLE
Class 'Geocoder\Provider\GoogleMaps' not found

### ISSUE THREAD

**Issue by senguttuvang** [geocoder-php/Geocoder#684]
I installed the package using the command provided in the doc

`$ composer require geocoder-php/google-maps-provider php-http/guzzle6-adapter php-http/message`

But, it throws this exception. I noticed that this class exists but composer somehow not recognising it. Should I have tweak any config so composer autoload would recognise this package?

**Comment by Nyholm** [comment]
The readme has docs for master. If you run the command before release of 4.0.0 you will get a 3.x version. Try run the following: 

```
composer require geocoder-php/google-maps-provider:dev-master php-http/guzzle6-adapter php-http/message
```

**Comment by Nyholm** [comment]
I've just tagged some beta versions, feel free to try them out.

**Comment by thatryan** [comment]
I just received this same error, but am I reading correct that the issue should be resolved without needing to change branch?
