### ISSUE TITLE
Create provider for Google Maps Places API

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#711]

**Comment by TerjeBr** [comment]
Unfinished work on this can be found in #447

**Comment by TerjeBr** [comment]
PR #447 was @gmauricio work. I had nothing to do with it. I just linked his work to this Issue.

**Comment by jbelien** [comment]
Oh, sorry about that ...

I forward the question to @gmauricio then : Would you have some time to work on the Google Maps Places provider (based on your PR #447) ? :)

**Comment by atymic** [comment]
Hmm, I wonder if we were going to implement https://github.com/geocoder-php/Geocoder/issues/942 if this is still required?

**Comment by jbelien** [comment]
> Hmm, I wonder if we were going to implement #942 if this is still required?

It's a different API, so IMHO it should be a different provider!

**Comment by atymic** [comment]
Oh, my bad. Getting them confused, ignore me :P

**Comment by atymic** [comment]
I've created a PR in #980 😄
