### ISSUE TITLE
type "premise" missing in google-maps-provider

### ISSUE THREAD

**Issue by nigam214** [geocoder-php/Geocoder#715]
Issues in address parsing from Google Map API
https://github.com/geocoder-php/google-maps-provider

Missing Type: 
"types" : [ "premise" ]

Example:
https://maps.googleapis.com/maps/api/geocode/json?address=28.6105873,77.3885597

**Comment by Nyholm** [comment]
Oh. I thought we did. Can you create a PR with a test and fix for this? Make the PR to this repo

**Comment by svrdlic** [comment]
Earlier this month we added 'subpremise', not 'premise' :)

**Comment by Nyholm** [comment]
Ah, okey. We should add premise as well.

**Comment by svrdlic** [comment]
And I could fix this one also, if nobody replays

**Comment by svrdlic** [comment]
Why dont we add all of AddressType parameters from google map replay..? https://developers.google.com/maps/documentation/geocoding/intro#Types

**Comment by svrdlic** [comment]
Why dont we add all parameters from google map replay?
https://developers.google.com/maps/documentation/geocoding/intro#Types

Maybe we can add them to the dynamic array, that @Nyholm added instead of dynamic parameters?

**Comment by Nyholm** [comment]
Feel free to do so =)

**Comment by nigam214** [comment]
@svrdlic please go ahead. sorry, couldn't able to reply earlier.

**Comment by nigam214** [comment]
we can consider adding "formatted_address" as well. in my project, I wanted to get the formatted address of given lat/long and encounter your library and these missing components. as @svrdlic suggested, adding all address parameters could be a better option.

**Comment by svrdlic** [comment]
@nigam214  "formatted_address" is already added, I think. 
I hope that I'll be able to create PR until tomorrow.

**Comment by nigam214** [comment]
@svrdlic saw the "formatted_address" in the code. thank you for pointing it out.

https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php#L264-L266

**Comment by svrdlic** [comment]
@Nyholm I have a problem with tests. I created new test in src/Provider/GoogleMaps/Tests/GoogleMapsTest.php, and when I run it, it says that functions that I added to GoogleAddress.php doesn't exit. Is it possible that it looks for those functions in vendor/geocoder-php/google-maps-provider?

**Comment by Nyholm** [comment]
Please submit a PR so we can see your work.

**Comment by svrdlic** [comment]
ok

**Comment by aditya-cherukuri** [comment]
I see there is work being done on this issue. Is it going to be part of the 4.x release or will it be a 3.3.1 release?

**Comment by Nyholm** [comment]
It is going to be a part of 4.x and released at the end of the month. There are no good way of making this work with the 3.3.x branch. That is one of the reasons we need a new release.

**Comment by Nyholm** [comment]
Closed by #732
