### ISSUE TITLE
type "sublocality_level_#" missing in google-maps-provider

### ISSUE THREAD

**Issue by nigam214** [geocoder-php/Geocoder#716]
Issues in address parsing from Google Map API
https://github.com/geocoder-php/google-maps-provider

Missing Type: 
"types" : [ "political", "sublocality", "sublocality_level_1" ]
"types" : [ "political", "sublocality", "sublocality_level_2" ]

Example:
https://maps.googleapis.com/maps/api/geocode/json?address=28.6105873,77.3885597

**Comment by Nyholm** [comment]
Thank you for both issues. Can you try to fix this as well? Maybe with the same PR if it makes sense?

**Comment by svrdlic** [comment]
I could fix this issue, if nobody replays

**Comment by Nyholm** [comment]
That would be great.

**Comment by nigam214** [comment]
@svrdlic please fix it if you can. it will be very helpful.

**Comment by Nyholm** [comment]
Closed by #751
