### ISSUE TITLE
Remove IpAddressGeocoder and LocaleAwareGeocoder

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#719]
Since introduction of the Query objects Im having second thoughts about the `IpAddressGeocoder` and `LocaleAwareGeocoder`. What do you think about removing them?

**Comment by Nyholm** [comment]
Ping @unkind, what are your thoughts?

**Comment by unkind** [comment]
Great.

**Comment by Nyholm** [comment]
Fixed by #720
