### ISSUE TITLE
Contribute provider best practices

### ISSUE THREAD

**Issue by rayrutjes** [geocoder-php/Geocoder#735]
I came to understand that from version 4.x providers are shipped as standalone repositories.

It would be nice to add a section to the CONTRIBUTING.md file to explain best practices regarding developing a new provider.

Some things to address:
- Policy regarding the hosting of repositories (should all providers be under the `geocoder-php` organization?)
- What is the process to get accepted there?
- Tests should run on the provider repository and on the main repository?
- Licensing requirements?
- Who is responsible for maintenance? Do you give access to repositories for provider owners?
- Do we strictly need to use the HTTP client?

Awesome project ;) Feel free to quickly give some answers in the comments and I will gladly format a PR for the CONTRIBUTING.md file.

I will also send a PR for adding a new provider in the upcoming weeks.

**Comment by willdurand** [comment]
Hi!

> Policy regarding the hosting of repositories (should all providers be under the geocoder-php organization?)

We use a mono-repository for all the code, then subtree splits to create all the provider-specific repositories. We will continue to maintain the code base in this mono-repo, so if your provider gets accepted here, a project under the `geocoder-php` umbrella will be created (as well as a Packagist entry).

> What is the process to get accepted there?

This has changed a lot over the years, but a feature-complete and well-tested provider could be accepted I would say. Let's wait for @Nyholm's reply though (also cc @geocoder-php/geocoder).

> Tests should run on the provider repository and on the main repository?

I think tests run on the main repository.

> Licensing requirements?

Same as the main repo. All the provider repos are read-only.

> Who is responsible for maintenance? Do you give access to repositories for provider owners?

You do not need to have special rights to maintain a specific provider. Being a contributor is a first step, then if you contribute a lot, chances are that you get an email from me 😉 

> Do we strictly need to use the HTTP client?

No. For instance, there used to be a Maxmind binary provider, which is file-based.

**Comment by Nyholm** [comment]
I agree with all your answers. 

I would be happy to review a `CONTRIBUTING.md.

**Comment by willdurand** [comment]
I'd be happy to review a better version of the contributing guidelines.

**Comment by rayrutjes** [comment]
I'm finishing my provider and then I'll try to review the CONTRIBUTING.md with what I've learned ;)

**Comment by jbelien** [comment]
Hello @rayrutjes ,

Any progress on improving `CONTRIBUTING.md` ?

Thanks 😃

**Comment by Nyholm** [comment]
Closing due inactivity. 

We would still be happy to see a PR.
