### ISSUE TITLE
Address Number Lost

### ISSUE THREAD

**Issue by afabros** [geocoder-php/Geocoder#747]
For numbers outside USA, numbers are lost in the geocoder data.
For numbers inside USA, numbers are intact.

ex. 3 street name, province, country

**Comment by Nyholm** [comment]
What provider are you using?

**Comment by afabros** [comment]
I'm using GeocoderLaravel -- I get intermittent result from Philippines data, sometimes with streetNumber others none. I have null in provider but the coordinates are correct.
<img width="421" alt="screen shot 2017-07-21 at 15 50 08" src="https://user-images.githubusercontent.com/805713/28452241-b233e8e4-6e2c-11e7-9aee-8898ce1a57d1.png">

**Comment by afabros** [comment]
process done: input '3 snapdragon street, cainta' to get the coordinates. data that came back has null streetNumber.

**Comment by Nyholm** [comment]
Sure, but what **provider**? Do you get data from google maps? Bing? Yandex? etc

What does the HTTP response from prover say? Does the street number exist there?

**Comment by afabros** [comment]
Not sure how to do that with the GeocoderLibrary through https://github.com/geocoder-php/Geocoder/pull/654. provider is always null on my end.

**Comment by afabros** [comment]
again for USA, provider is not null, both address i tested in the philippines, provider is null.
<img width="455" alt="screen shot 2017-07-21 at 16 12 24" src="https://user-images.githubusercontent.com/805713/28452859-7edb2ffe-6e2f-11e7-9b6a-32bb7cf0c65a.png">

**Comment by afabros** [comment]
Tried again and I'm getting this as the provider, still null streetNumber.
<img width="466" alt="screen shot 2017-07-21 at 16 17 10" src="https://user-images.githubusercontent.com/805713/28453001-2263c3a2-6e30-11e7-8d49-0b9824ec78e5.png">

**Comment by Nyholm** [comment]
I need you to debug this for me to have a chance to figure it out. Not just giving me results of your queries. 

What versions are you running of the packages? `compser show | grep geocoder`
You also have to find out if you are using GoogleMaps or BingMaps. I've seen both in your results. 

When you know what provider do are using, you need to figure out if it is for all request to that provider or only for some.

**Comment by afabros** [comment]
Hard to test which provider because the library is throwing null or two providers.

I manually tested both. only BingMaps provided the correct streetNumber.
The problem is not the parsing on your end but on the provider side -- streetNumber on other countries are not yet correctly mapped. 

Thank you for your time.

**Comment by Nyholm** [comment]
Okey. As you say, then there is nothing we can do about this. 

Thank you for the issue.
