### ISSUE TITLE
ID from Service Provider in Address Model

### ISSUE THREAD

**Issue by arubacao** [geocoder-php/Geocoder#749]
Is there any chance on adding the original IDs from the service providers to the address model?
I'm heavily relying on them and have to keep an almost identical fork of some providers since inheriting the final base classes is not possible.

Cheers,
Chris

**Comment by Nyholm** [comment]
We have the `Location::getProvidedBy`([source](https://github.com/geocoder-php/Geocoder/blob/master/src/Common/Location.php#L115)) which is the same as `Provider::getName`. Isn't that what you are asking for?

**Comment by arubacao** [comment]
yes, I'm also using this method to distinguish between providers. But what I'm referring to in my question is the actual ID.
So somewhere within the [`updateAddressComponent`](https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php#L244) method I'd get the value from `place_id` and set it on [address object](https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php#L204)

> place_id is a unique identifier that can be used with other Google APIs. For example, you can use the place_id in a Google Places API request to get details of a local business, such as phone number, opening hours, user reviews, and more. See the [place ID overview](https://developers.google.com/places/place-id).

**Comment by Nyholm** [comment]
Ah, on the GoogleMaps provider. Of course, we should definitely extend Google Maps' address object with a place ID. 

I would be happy to review and merge such PR.

**Comment by arubacao** [comment]
Consider it done

**Comment by arubacao** [comment]
Do you think it would make sense to add the `ID` to the `Geocoder\Model\Address` class?
I guess most (maybe all ?) providers provide some sort of identification.
