### ISSUE TITLE
Error attempting to install via composer

### ISSUE THREAD

**Issue by thatryan** [geocoder-php/Geocoder#759]
Sorry, utter noob with composer but pretty sure I have it all right. Attempting to try the library and running the command

`❯ composer require geocoder-php/google-maps-provider php-http/guzzle6-adapter php-http/message`

However I get shot an error after that showing this,

![2017-08-01 at 11 46 am](https://user-images.githubusercontent.com/26583/28841418-06e832ac-76af-11e7-9db8-ad9f87b0ba44.png)

Which makes me think I am on old PHP, however I confirm I am on PHP 7 here,

	vagrant@vvv:/srv/www/my-site$ wp --info
	PHP binary:     /usr/bin/php7.1
	PHP version:    7.1.7-1+ubuntu14.04.1+deb.sury.org+1
	php.ini used:   /etc/php/7.1/cli/php.ini
	WP-CLI root dir:        phar://wp-cli.phar
	WP-CLI vendor dir:      phar://wp-cli.phar/vendor
	WP_CLI phar path:       /srv/www/my-site
	WP-CLI packages dir:
	WP-CLI global config:
	WP-CLI project config:  /srv/www/my-site/wp-cli.yml
	WP-CLI version: 1.3.0-alpha-42bbe3e

What am I not understanding here?

Thank you.

**Comment by Nyholm** [comment]
That error message is sure telling you that you are running PHP 5.5.38. Could it be that you have specified a "fake" php version in your composer.json? Like this: https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L50-L52

If so, you should remove that.

**Comment by thatryan** [comment]
Thank you, but nope. My composer file is pretty barren lol

https://github.com/thatryan/s-core/blob/master/composer.json

**Comment by willdurand** [comment]
What would be the output of `which composer`?

**Comment by thatryan** [comment]
❯ which composer
    /usr/local/bin/composer

**Comment by willdurand** [comment]
and `which php`?

**Comment by thatryan** [comment]
❯ which php
    /usr/bin/php

**Comment by Nyholm** [comment]
`php --version`?

**Comment by thatryan** [comment]
ahh that is dumping 5.5.38...

**Comment by willdurand** [comment]
You could move `/usr/bin/php` to `/usr/bin/php5.5` and move `/usr/bin/php7.1` to `/usr/bin/php`.

**Comment by thatryan** [comment]
OK thanks guys, ill get it fixed up now, sorry for my bad!

**Comment by Nyholm** [comment]
No worries. Thank you for submitting the issue.
