### ISSUE TITLE
Fatal error: Uncaught Error: Class

### ISSUE THREAD

**Issue by thatryan** [geocoder-php/Geocoder#760]
Got it all installed finally, thank you guys :)

Attempting to walk through your README steps, https://github.com/geocoder-php/Geocoder#usage

And got the error, 

`Fatal error: Uncaught Error: Class 'Geocoder\Provider\GoogleMaps' not found`

Google led me to issue [684](https://github.com/geocoder-php/Geocoder/issues/684)

But I have version 4.0 so I am not sure that applies correct?

My code is verbatim as the README,

    $address = get_theme_mod('s_core_business_address');
    $adapter  = new \Http\Adapter\Guzzle6\Client();
    $provider = new \Geocoder\Provider\GoogleMaps($adapter);
    $geocoder = new \Geocoder\StatefulGeocoder($provider, 'en');

**Comment by Nyholm** [comment]
That's a typo in the readme. Try Geocoder\Provider\GoogleMaps\GoogleMaps

//Tobias Nyholm

**Comment by thatryan** [comment]
Got it, thank you again.

**Comment by thatryan** [comment]
Same issue with 

`$result = $geocoder->geocodeQuery(GeocodeQuery::create($address));`

"Fatal error: Uncaught Error: Class 'GeocodeQuery' not found "

**Comment by Nyholm** [comment]
I've added #761.

**Comment by Nyholm** [comment]
Again, thank you for this issue. 

I've updated the Readme now. It includes namespaces and use statements. Please ping me if you are finding more issues.
