### ISSUE TITLE
Document the cache provider

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#762]
There is nothing about that provider ATM.

**Comment by Baachi** [comment]
Do we still need this provider? We rely on the PSR7 standard and guzzle and httplug have already a caching mechanism built-in. So in my opinion we can deprecate this provider and rather document how migrate to the "new cache mechanism". 

WDYT?

**Comment by ruudk** [comment]
I would keep it. Having a separate plugin that gets the `Query` object and then calculates the cache key is valuable. For example see https://github.com/geocoder-php/Geocoder/issues/882

**Comment by atymic** [comment]
PR open in #977
