### ISSUE TITLE
PHP error in Bounds

### ISSUE THREAD

**Issue by dereuromark** [geocoder-php/Geocoder#767]
When calling $address->toArray() this happens:

    TypeError: Return value of Geocoder\Model\Bounds::getSouth() must be of the type float, null returned

So nullable seems to either be missing, or a cast. The first sounds more reasonable.

Debugging the object reveals:
```
object(Geocoder\Model\Address) {
	[private] coordinates => object(Geocoder\Model\Coordinates) {
		[private] latitude => (float) 49.0803566
		[private] longitude => (float) 9.6881269
	}
	[private] bounds => object(Geocoder\Model\Bounds) {
		[private] south => null
		[private] west => null
		[private] north => null
		[private] east => null
	}
```
I wonder how this ends up to be null in the first place, as this is a valid address.

**Comment by Nyholm** [comment]
Thank you for this issue. 

> I wonder how this ends up to be null in the first place, as this is a valid address.

Yeah. Can you investigate in that? Looking at the [Bounds constructor](https://github.com/geocoder-php/Geocoder/blob/4.0.0/src/Common/Model/Bounds.php#L48) it seams to be impossible.

**Comment by Nyholm** [comment]
Btw, What version are you using?

**Comment by dereuromark** [comment]
https://github.com/geocoder-php/Geocoder/releases/tag/4.0.0

**Comment by Nyholm** [comment]
Have you found what lines of code that creates the Bounds object?

**Comment by Nyholm** [comment]
Closed because of inactivity.
