### ISSUE TITLE
Geonames provider notice

### ISSUE THREAD

**Issue by kornrunner** [geocoder-php/Geocoder#782]
I've submitted a https://github.com/geocoder-php/geonames-provider/pull/1 within geonames repo.
Given `geonames` key seems to be missing sometimes from responses, and patch avoids the notice issued by PHP.

The change is simple, I'll be more than happy to change anything if required. Thank you!

**Comment by Nyholm** [comment]
That repo is read only. Please make you PR to this repo instead

**Comment by kornrunner** [comment]
Sure, thanks, it's in #783

**Comment by Nyholm** [comment]
Thanks!

**Comment by kornrunner** [comment]
Any chance of tagging this as a minor? Thanks!

**Comment by Nyholm** [comment]
4.1 is tagged. Thank you for the reminder.
