### ISSUE TITLE
Invalid base class for Yandex provider.

### ISSUE THREAD

**Issue by roro15** [geocoder-php/Geocoder#785]
Yanex provider inherit from Geocoder\Http\Provider\AbstractHttpProvider, but that class doesnot exist.
Added GoogleMaps provider and it has "geocoder-php/common-http": "^4.0", in dependencies, so problem solved. Think  "geocoder-php/common-http": "^4.0" should be in depenencies of Yandex provider.

**Comment by Nyholm** [comment]
Thank you. That is very correct. Could you send a PR?

**Comment by Nyholm** [comment]
Closed by#788
