### ISSUE TITLE
Administrative level 4 is defined twice

### ISSUE THREAD

**Issue by benwrigley** [geocoder-php/Geocoder#793]
Hi There,

Using the Google API and ReverseQuery with coordinates sometimes  dies  with Geocoder\Exception\InvalidArgument 'Administrative level 4 is defined twice'

Google docs do say this might happen. Is it possible to merge the two lists for the purposes of returning data and therefore not having to generate an Exception?

**Comment by Nyholm** [comment]
Hey. 

Thank you for this issue. 
You are correct. What do you suggest we should do if we notice multiple level 4’s?

**Comment by benwrigley** [comment]
Hi,

I wonder if there is a way to merge the lists in the level 4s?

**Comment by benwrigley** [comment]
so take this example:

`        {
          "long_name": "Kings Hill",
          "short_name": "Kings Hill",
          "types": [
            "administrative_area_level_4",
            "locality",
            "political"
          ]
        },
        {
          "long_name": "Kings Hill",
          "short_name": "Kings Hill",
          "types": [
            "administrative_area_level_4",
            "political"
          ]
        },`

The types would all be merged and uniqued so the result might be ['locality','political']

**Comment by Nyholm** [comment]
Hm.. A bunch of questions comes to my mind.
- Should we always merge?
- Should we only merge if they are exactly the same?
- Should we really correct Google? If Google does not care about this issue, should we?

**Comment by Nyholm** [comment]
Closed because of inactivity.

**Comment by geodeveloper** [comment]
Same, here **Administrative level 3 is defined twice**. I guess the correct solution would be to get the first administrative area level of the same type.

**Comment by fritzmg** [comment]
Same here, with __Administrative level 1 is defined twice__ with the following query:
```
{“text”:“\u017delezni\u010dn\u00e1 53 Stupava 90031",“bounds”:“null”,“locale”:null,“limit”:5,“data”:[]}
```
and following result:
```
{
   "results":[
      {
         "address_components":[
            {
               "long_name":"53",
               "short_name":"53",
               "types":[
                  "street_number"
               ]
            },
            {
               "long_name":"\u017delezni\u010dn\u00e1",
               "short_name":"\u017delezni\u010dn\u00e1",
               "types":[
                  "route"
               ]
            },
            {
               "long_name":"Stupava",
               "short_name":"Stupava",
               "types":[
                  "political",
                  "sublocality",
                  "sublocality_level_1"
               ]
            },
            {
               "long_name":"Stupava",
               "short_name":"Stupava",
               "types":[
                  "political",
                  "sublocality",
                  "sublocality_level_1"
               ]
            },
            {
               "long_name":"Malacky",
               "short_name":"Malacky",
               "types":[
                  "administrative_area_level_2",
                  "political"
               ]
            },
            {
               "long_name":"Bratislavsk\u00fd kraj",
               "short_name":"Bratislavsk\u00fd kraj",
               "types":[
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name":"Slovakia",
               "short_name":"SK",
               "types":[
                  "country",
                  "political"
               ]
            },
            {
               "long_name":"900 31",
               "short_name":"900 31",
               "types":[
                  "postal_code"
               ]
            }
         ],
         "formatted_address":"\u017delezni\u010dn\u00e1 53, 900 31 Stupava, Slovakia",
         "geometry":{
            "location":{
               "lat":48.2690826,
               "lng":17.0170817
            },
            "location_type":"RANGE_INTERPOLATED",
            "viewport":{
               "northeast":{
                  "lat":48.27043158029149,
                  "lng":17.0184306802915
               },
               "southwest":{
                  "lat":48.26773361970849,
                  "lng":17.0157327197085
               }
            }
         },
         "place_id":"EirFvWVsZXpuacSNbsOhIDUzLCA5MDAgMzEgU3R1cGF2YSwgU2xvdmFraWEiGhIYChQKEgnNEl0zb-1sRxGxKFRFRK8LrBA1",
         "types":[
            "street_address"
         ]
      }
   ],
   "status":"OK"
}
```
Weirdly, there is only one `administrative_area_level_1`.

**Comment by jbelien** [comment]
I submitted a PR (#943), could one of you test and confirm the PR fix the issue ? Thanks !
