### ISSUE TITLE
[Feature Request] Implementing "partial_match"-Attribute

### ISSUE THREAD

**Issue by jentscke** [geocoder-php/Geocoder#796]
To check the quality of address, we would like to receive the partial_match attribute.

See Google Maps Docs for details:
https://developers.google.com/maps/documentation/geocoding/intro?hl=en
> **partial_match**: indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.

**Comment by Nyholm** [comment]
That is an excellent idea
