### ISSUE TITLE
Question: Determining unique places from multiple responses of different APIs?

### ISSUE THREAD

**Issue by burzum** [geocoder-php/Geocoder#797]
First I'm aware of the caching solution, but this seems to cache only response from an API. I've done some research but couldn't come up with a good solution. 

Different APIs might return different data sets in terms of completion and probably slightly different geographic coordinates for a place as well. For example one API might return locality but not sub locality and a slightly different coordinate. Also the same API might return slightly different results depending on how much info was provided. However, I would like to somehow try to map both responses to the same place in my local DB.

Is there any recommended way to store the locations locally in a DB and make sure there are as less duplicates as possible?

**Comment by Baachi** [comment]
You could write something similar to the [`Chain`](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/Chain/Chain.php) provider, which asks more providers for there result and try to get the most accurate result.

And to your next question, you could save this result in a database, of course. But take care of there terms of uses. Some of them forbid to store there results permantly (e.g. Google).

**Comment by Nyholm** [comment]
Closed because of inactivity.
