### ISSUE TITLE
Does the System support distancematrix API

### ISSUE THREAD

**Issue by DawoudIO** [geocoder-php/Geocoder#801]
https://developers.google.com/maps/documentation/distance-matrix/intro

**Comment by Nyholm** [comment]
Hey. 
I’m not sure. What does the docs say? Or what does it say in the code?

**Comment by DawoudIO** [comment]
I did not see it in code or doc

**Comment by Nyholm** [comment]
Okey. I guess it is not supported yet. If you send a PR I would be happy to review it

**Comment by Nyholm** [comment]
Closed because of inactivity.

**Comment by DamienHarper** [comment]
@DawoudIO Hi, better late than never, I wrote this bundle that may respond to your needs ;)
https://packagist.org/packages/damienharper/navigation-bundle

**Comment by DawoudIO** [comment]
Thanks ill look into it

**Comment by almare** [comment]
This is great! Hopefully this gets included
