### ISSUE TITLE
Nominatim Provider improvements

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#805]
Hello everyone (and happy holidays 🎉 ),

I started to have a look at `geocoder-php` and it's really awesome ! 👍 
I use *Nominatim* a lot and since now, I did my query directly on the Nominatim API.

I feel like there are useful items missing in the Nominatim Provider :
- The **locationType** provided by `class` parameter ;
- The **formattedAddress** provided by `display_name` parameter ;
- The **copyright**/**licence** (indeed, the [Nominatim Usage Policy](https://operations.osmfoundation.org/policies/nominatim/) asks to display clearly the attributions) provided by `attribution` parameter ;

Since, it's my first use of `geocoder-php` I would like to know how you feel about this before suggesting any PR and what would be the best way to do it ? Should I base Nominatim Provider on Google Maps provider for instance (which includes **locationType** and **formattedAddress**) ?

Thanks a lot !

**Comment by Nyholm** [comment]
Hey. 

Thank you for your feedback. I would be happy to review a PR. 

Providers should not depend on eachother. Ie, you should not base Nominatim Provider on Google Maps provider. You should however be inspired by Google Maps and maybe *copy* some of its solutions.

**Comment by jbelien** [comment]
> Providers should not depend on eachother. Ie, you should not base Nominatim Provider on Google Maps provider. You should however be inspired by Google Maps and maybe copy some of its solutions.

Yes, sorry, that's what I meant :)

I'll take care of this ASAP !
