### ISSUE TITLE
Mapzen is shutting down its geocoder

### ISSUE THREAD

**Issue by stevevance** [geocoder-php/Geocoder#808]
https://mapzen.com/blog/shutdown/

(This is a placeholder issue. I don't know exactly what needs to happen for this repository. Does the Mapzen provider just need to be de-registered? The Mapzen Search is open source so it's possible that someone could stand up their own instance and use the existing Mapzen geocoder-php provider hook.)

**Comment by Nyholm** [comment]
I think we just add a comment in the Mapzen provider readme.

**Comment by stevevance** [comment]
There is now a drop-in replacement for Mapzen Search/Pelias called [geocode.earth](https://geocode.earth) which is created by the same people (formerly of Mapzen) who created Pelias!

I got an API key from them and replaced the Mapzen URL with "https://api.geocode.earth" and everything worked!

**Comment by Nyholm** [comment]
Awesome. Could you make a PR to add this new provider. Basically just copy the mapzen provider and add a new namespace.

**Comment by atymic** [comment]
I'll jump on this one and get a PR up soon :smile:

**Comment by atymic** [comment]
Also, what should we do with the old Mapzen provider?
I was thinking we could add depreciation docblock tags to the classes/methods, and update the readme if we don't want to remove the provider for BC reasons (i.e in case it's still in the code, but not actually used)

**Comment by jbelien** [comment]
Yes, I was indeed planning to state somewhere in the README to switch to GeocoderEarth provider but never took the time to add the GeocoderEarth provider myself !

**Comment by atymic** [comment]
Thanks, I'll open up a separate PR for that.

**Comment by orangejulius** [comment]
@atymic I'd recommend removing or at least deprecating the Mapzen provider. The service is long gone and not coming back.

**Comment by atymic** [comment]
> @atymic I'd recommend removing or at least deprecating the Mapzen provider. The service is long gone and not coming back.

I was thinking deprecating it using annotations, and  marking the packaging repo as abandoned. That way we won't risk breaking anything still pulling down the package but not actually using it.
