### ISSUE TITLE
Get installed providers list

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#809]
I was wondering if there is a "simple" way to get the list of all the installed providers ?

**Comment by jbelien** [comment]
As proposed by @Nyholm in #221 :
> Maybe with Symfony autowirng

[Symfony autowiring](https://symfony.com/doc/current/service_container/autowiring.html)

or

[PHP-DI autowiring](http://php-di.org/doc/autowiring.html)

**Comment by Nyholm** [comment]
I thought the issue was posted on the GeocoderBundle repo. There is no good way to get all installed providers as far as I know.

**Comment by chriscalip** [comment]
Currently de-facto installed providers are done via directory `/src/Provider`. Until a use-able api to install providers for geocoder-php to use.. this is what we have.

**Comment by Nyholm** [comment]
Closed because of inactivity.
