### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by barannd** [geocoder-php/Geocoder#811]
I get a php error "Allowed memory size of x bytes exhausted", if I try to geocode an address like "asdd21f2fdwf9, 2fj12djl12dl1 2kdj1l2d12d2".

Is there a way to catch this error?

**Comment by Nyholm** [comment]
What provider are you using?

**Comment by barannd** [comment]
I'm using the ProviderAggregator with just one registered provider (GoogleMaps)

**Comment by barannd** [comment]
Do you have a solution? :)

**Comment by Nyholm** [comment]
Im not sure at all.
Could you debug this a bit more. Does it get stuck in a loop?

**Comment by barannd** [comment]
Ok I'm really sorry to inform you that i ran into an endless loop in my application which triggers the error. Everything works fine. Thanks for the hint and the fast response!
