### ISSUE TITLE
Create provider for Mapbox

### ISSUE THREAD

**Issue by chriscalip** [geocoder-php/Geocoder#831]

**Comment by chriscalip** [comment]
https://github.com/mapbox/mapbox-gl-geocoder/issues/146

**Comment by jbelien** [comment]
Actually it's more https://www.mapbox.com/api-documentation/#geocoding than the `mapbox-gl-geocoder` JavaScript library :)

I'll have a look when I have a bit of free time, it shouldn't be to difficult to add this provider :)

**Comment by fedeisas** [comment]
I started working on this: https://github.com/fedeisas/mapbox-provider

I'm not sure I made the right choices when it comes to converting Mapbox features into Address components. But it's a start.

How can we make it an official provider @willdurand?

**Comment by Nyholm** [comment]
When you are happy with your implementation, feel free to add a link to in in the readme. 

Im not sure we have any specific requirements for including it in this repo. But send a PR and I'll review it.

**Comment by fedeisas** [comment]
@Nyholm done :-)
