### ISSUE TITLE
Documentation: Address::getLongitude() & Address::getLatitude()

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#834]
I just noticed that on http://geocoder-php.org/Geocoder/ it says :

> Address & AddressCollection
>
> Both geocode() and reverse() methods return a collection of Address objects (AddressCollection), each providing the following API:
>
>    getCoordinates() will return a Coordinates object (with latitude and longitude properties);
>    getLatitude() will return the latitude value;
>    getLongitude() will return the longitude value;

Indeed, in `Address` model, `getCoordinates()` function is available, but `getLongitude()` and `getLatitude()` are not available.

Did I miss something or is the documentation not up-to-date ?

PS: I also tried to find where http://geocoder-php.org/Geocoder/ documentation is on GitHub but could not find it. I only found the homepage here : https://github.com/geocoder-php/geocoder-php.github.io

**Comment by Nyholm** [comment]
`Address::getLatitude()` and `Address::getLongitude()` has been removed. You are correct, the documentation is not up to date. All the up to date documentation is in the readme of this repo: https://github.com/geocoder-php/Geocoder

Maybe @willdurand can tell us how to update the website?

**Comment by jbelien** [comment]
> All the up to date documentation is in the readme of this repo: https://github.com/geocoder-php/Geocoder

That's what I thought 😃 

> Maybe @willdurand can tell us how to update the website?

Could be usefule IMHO !
