### ISSUE TITLE
Use Address object as query, instead of just one line of free text

### ISSUE THREAD

**Issue by TerjeBr** [geocoder-php/Geocoder#839]
You have this class `Geocoder\Model\Address` that implements `Geocoder\Location`. But is is only used when returning responses/results.

What I would like to see is a way to also pass this as the request to the geocoder. Currently it is only possible to pass the address in the request as free formatted text string.

The background for this is that I noticed that at mapquest.com you can pass something they call a 5-box format to give better results. See [Map Quest API](https://developer.mapquest.com/documentation/open/geocoding-api/) and [Specifying Locations](https://developer.mapquest.com/documentation/common/forming-locations/).

One way around this may be to pass the Address object on the data section of the query. But I thought that seemed a bit clunky. Since the only purpose of this library is to send queries about addresses, should it not be a more streamlined way to send an actual `Address` object as a query instead of just a free text string?

**Comment by Nyholm** [comment]
Thank you for this issue. You could pass the GeocodeQuery some arbitrary data. See https://github.com/geocoder-php/Geocoder/blob/master/src/Common/Query/GeocodeQuery.php#L131

I would love to see a PR to MapQuest that supports this.

**Comment by TerjeBr** [comment]
Yes, I know I can use `GeocodeQuery->withData()` to send arbitary data along with the query.

But my question was if you would consider changing the `GeocodeQuery` class, along with the interface `Query` to allow for a more direct or explicit reference to an object implementing `Geocoder\Location`?

Then various providers could may be call `$query->getLocation()` as well as `$query->getText()`?

As I said, it seems a bit clunky that the standard way to pass an `Address` object should be in the data section of the query.

**Comment by TerjeBr** [comment]
May be a solution is to just extend `GeocodeQuery` and send that. If I make a PR where would that extended `GeocodeQuery` live? In the MapQuest provider directory, or in the Common directory?

**Comment by Nyholm** [comment]
> But my question was if you would consider changing the GeocodeQuery class, along with the interface Query to allow for a more direct or explicit reference to an object implementing Geocoder\Location?

No, that would be a BC break. 

> Then various providers could may be call $query->getLocation() as well as $query->getText()?

Right now there is over 30 providers and only one need this function. That does not sound like a good abstraction. 

> May be a solution is to just extend GeocodeQuery and send that. If I make a PR where would that extended GeocodeQuery live?

Since this is specific feature for MapQuest. I suggest you use `GeocodeQuery::withData` and make your changes only to the MapQuest provider.

**Comment by jbelien** [comment]
I think that `withData()` is the way to go.

You can see how I use it in my [bpost provider](https://github.com/geo6/geocoder-php-bpost-provider).
