### ISSUE TITLE
Nominatim provider requires non-existent package

### ISSUE THREAD

**Issue by burzum** [geocoder-php/Geocoder#841]
There is no such package, just different implementations of it.

```sh
λ composer require geocoder-php/common-http
Using version ^4.0 for geocoder-php/common-http
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for geocoder-php/common-http ^4.0 -> satisfiable by geocoder-php/common-http[4.0.0].
    - geocoder-php/common-http 4.0.0 requires psr/http-message-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by Nyholm** [comment]
Thank you for this issue. 

This is mentioned in [our docs](https://github.com/geocoder-php/Geocoder#installation) and  [HTTPlug docs](http://docs.php-http.org/en/latest/httplug/users.html). 

And also, did you do a search of packagist before writing this issue? [Packagist shows plenty](https://packagist.org/providers/psr/http-message-implementation) =)

Im going to close this issue now.

**Comment by burzum** [comment]
@Nyholm yes, my stupid fault. I just realized that I just need to add some adapter. The point was that I've tried to install the adapter without a http adapter and it pointed to `psr/http-message-implementation` which is on packagist just a list of packages instead of a package.

**Comment by Nyholm** [comment]
No worries. 
I have an open issue on composer to give you a better user experience in this case.

**Comment by burzum** [comment]
Awesome, thanks again!
