### ISSUE TITLE
Nominatim Provider: osm_id conversion to int with intval

### ISSUE THREAD

**Issue by sheub** [geocoder-php/Geocoder#848]
Hi there,
I had issues with the conversion of the osm_id to integer.
nominatim.php at 185
````php
$location = $location->withOSMId(intval($resultNode->getAttribute('osm_id')));
````
As an example of request giving me issue: Einfach unverpackt Kochstraße 6 Leipzig Germany
Its node ID is 4201897293, and the geocoder-php returned me 2147483647.

Modifying the code to get directly the string value solved my issue.

Why not keeping this value as string? There won't be any arithmetic performed on the ID anyway.

**Comment by sheub** [comment]
Your right, I did the test on a 64 architecture and got correct result.

**Comment by jbelien** [comment]
I just found documentation about this topic :

> On 9th of February, 2013, node identifiers surpassed 2,147,483,647, which is the highest number that can be stored as a 32-bit signed integer. On 10th July 2016, they reached 4,294,967,295, which is the limit for a 32-bit unsigned integer. Software that uses such variables will break, so it is important that everyone has latest versions of every tool in their toolchains. 

See documentation : https://wiki.openstreetmap.org/wiki/64-bit_Identifiers
