### ISSUE TITLE
Get address from GoogleMaps using Postalcode/Housenumber 

### ISSUE THREAD

**Issue by Yamakasi** [geocoder-php/Geocoder#851]
As the examples are not completely clear to me I wonder if it's possible to get an address from GoogleMaps using Postalcode/Housenumber and also get the distance between 2 addresses if you receive those using the postalcode/housenumber.

**Comment by Yamakasi** [comment]
OK found the address part, this is the same as the JS way.

Then I would like to know if I could get a route like:

`http://maps.googleapis.com/maps/api/directions`

**Comment by jbelien** [comment]
Hello @Yamakasi,

Even though Google Maps provides a [Routes & Directions API](https://cloud.google.com/maps-platform/routes/), that's not the goal or purpose of *Geocoder PHP* project.
*Geocoder PHP* is only focused on geocoding.

**Comment by Yamakasi** [comment]
@jbelien Thanks I thought so, still I use it as it has a great way of reverseQuery which saves me writing it my own :)

**Comment by jbelien** [comment]
That's exactly the point 😉 

And if you want to switch from Google API to any other ... you don't have to change anything in your code, just change the provider 👍

**Comment by Yamakasi** [comment]
I wanted to update this as I get different results when I query a postalcode / housenumber what goes OK when I use the direct Google API, also with reverse geocoding. 

With the direct API of Google I do a postalcode / housenumber lookup, I get the city, streetname, country of the postalcode, this without using the country in the earlier query and do a reverse lookup using this full address.

The first step doesn't seem to be that accurate, postalcode also checked without spaces between numbers/letters.

Any idea ?

**Comment by Yamakasi** [comment]
OK, I can update this. I missed a step between the lookups which I did using the javascript against Google earlier. 

I will close the tocket, thanks for the help!
