### ISSUE TITLE
Provide valid User-Agent for Nominatim

### ISSUE THREAD

**Issue by eileenmcnaughton** [geocoder-php/Geocoder#853]
Per https://github.com/eileenmcnaughton/org.wikimedia.geocoder/issues/1 it has been reported to us that 

"The nominatim.openstreetmap.org states that users must "provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do)."

The User-Agent is currently set to the default GuzzleHttp one. This is in violation of the usage policy."

Is it currently possible to control the user-agent with the Nominatim plugin to avoid this?

**Comment by jbelien** [comment]
Thanks for the notice !

I'll have a look at this to se how we could fix the Nominatim provider to be compliant with the usage policy !

As an OpenStreetMap Belgium board member, I feel a bit ashamed about this... 🙈

**Comment by eileenmcnaughton** [comment]
That's has made me smile. Also - I like your avatar! Everything is awesome

**Comment by jbelien** [comment]
I just had a look at it !
I can fix it ; really not an issue but I need advice from the team ( ping @Nyholm @willdurand ) !

To set `Referer` and `User-Agent` headers, I'll need to replace the use of `getUrlContents()` from the parent `AbstractHttpProvider` class by its own (like I did for my provider here : https://github.com/geo6/geocoder-php-geo6-provider/blob/master/Geo6.php#L173-L198).

I was looking at the best way to do it and I found this PR #353 !
If we could add `getHeaders()`, `getHeader()`, and `setHeaders()` to the `AbstractHttpProvider` class, it would save us the trouble to "overload" the `getUrlContents()` function for each provider that needs to set headers.

What do you think about this ?
Thanks a lot !

**Comment by eileenmcnaughton** [comment]
Looks good to me :-) But I guess you need @Nyholm @willdurand input

**Comment by jbelien** [comment]
> Looks good to me :-) But I guess you need @Nyholm @willdurand input

Indeed :)
If I don't have any news, I'll just submit a PR on Nominatim provider without adding the "headers" functions to `AbstractHttpProvider` class in the next few days.

**Comment by Nyholm** [comment]
Thank you for this issue. 

The "correct" way of doing this is something like: (not sure if "correct" is the correct word...)

```php
use Geocoder\Query\GeocodeQuery;
use Geocoder\Query\ReverseQuery;
use Http\Client\Common\Plugin\HeaderDefaultsPlugin;
use Http\Client\Common\PluginClient;

$httpClient = new \Http\Adapter\Guzzle6\Client();
$httpClient = new PluginClient(httpClient, [
   new HeaderDefaultsPlugin(['User-Agent' => 'My-app']), 
]);
$provider = new \Geocoder\Provider\Nominatim\Nominatim($httpClient);

$result = $provider->geocodeQuery(GeocodeQuery::create('Buckingham Palace, London'));
```

However, Since **all** users need this it might be better (more developer friendly) to add an argument to the Nominatim constructor as @jbelien suggests. 

-----------

Could you provide such PR? 
Note, it may be useful to create two PRs. The first will modify `AbstractHttpProvider::getUrlContents` and split it up to two functions. One that creates the request/response and another function that parses the response.

**Comment by jbelien** [comment]
Thanks for the suggestions @Nyholm !
I'll try to take care of it begin of July !

**Comment by Nyholm** [comment]
FYI https://github.com/geocoder-php/Geocoder/pull/864
