### ISSUE TITLE
freegeoip.net will be discontinued on July 1, 2018

### ISSUE THREAD

**Issue by mwisner** [geocoder-php/Geocoder#860]
According to https://github.com/apilayer/freegeoip#readme the freegeoip.net service will be discontinued on July 1st, 2018. 

It's suggested in that announcement to use ipstack which doesn't appear to be supported by this package. 

Should the freegeoip provider be removed and / or ipstack added?

**Comment by Nyholm** [comment]
Thank you. 
I suggest to add ipstack. There is no need to remove the provider at this time.

**Comment by jGielen** [comment]
https://github.com/geocoder-php/Geocoder/pull/879

**Comment by jGielen** [comment]
@mwisner in the mean time you can change the url

**Comment by jbelien** [comment]
The ipstack provider is now merged and will be release in the next few days 🎉
