### ISSUE TITLE
Can i parser respon from google maps provider to json?

### ISSUE THREAD

**Issue by juragandotid** [geocoder-php/Geocoder#861]
`Geocoder\Model\AddressCollection Object
(
    [locations:Geocoder\Model\AddressCollection:private] => Array
        (
            [0] => Geocoder\Provider\GoogleMaps\Model\GoogleAddress Object
                (
                    [id:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => EiczNDkgUyBTdGF0ZSBTdCwgU3lyYWN1c2UsIE5ZIDEzMjAyLCBVU0EiGxIZChQKEgmX5rq9u_PZiRHTH3j5h04aXxDdAg
                    [locationType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => RANGE_INTERPOLATED
                    [resultType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Array
                        (
                            [0] => street_address
                        )

                    [formattedAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 349 S State St, Syracuse, NY 13202, USA
                    [streetAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [intersection:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [political:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => United States
                    [colloquialArea:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [ward:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [neighborhood:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Downtown
                    [premise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subpremise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [naturalFeature:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [airport:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [park:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [pointOfInterest:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [establishment:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subLocalityLevels:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                )

                        )

                    [coordinates:Geocoder\Model\Address:private] => Geocoder\Model\Coordinates Object
                        (
                            [latitude:Geocoder\Model\Coordinates:private] => 43.0483083
                            [longitude:Geocoder\Model\Coordinates:private] => -76.1474409
                        )

                    [bounds:Geocoder\Model\Address:private] => Geocoder\Model\Bounds Object
                        (
                            [south:Geocoder\Model\Bounds:private] => 43.046959319708
                            [west:Geocoder\Model\Bounds:private] => -76.148789880292
                            [north:Geocoder\Model\Bounds:private] => 43.049657280291
                            [east:Geocoder\Model\Bounds:private] => -76.146091919708
                        )

                    [streetNumber:Geocoder\Model\Address:private] => 349
                    [streetName:Geocoder\Model\Address:private] => South State Street
                    [subLocality:Geocoder\Model\Address:private] =>
                    [locality:Geocoder\Model\Address:private] => Syracuse
                    [postalCode:Geocoder\Model\Address:private] => 13202
                    [adminLevels:Geocoder\Model\Address:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                    [1] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 1
                                            [name:Geocoder\Model\AdminLevel:private] => New York
                                            [code:Geocoder\Model\AdminLevel:private] => NY
                                        )

                                    [2] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 2
                                            [name:Geocoder\Model\AdminLevel:private] => Onondaga County
                                            [code:Geocoder\Model\AdminLevel:private] => Onondaga County
                                        )

                                )

                        )

                    [country:Geocoder\Model\Address:private] => Geocoder\Model\Country Object
                        (
                            [name:Geocoder\Model\Country:private] => United States
                            [code:Geocoder\Model\Country:private] => US
                        )

                    [timezone:Geocoder\Model\Address:private] =>
                    [providedBy:Geocoder\Model\Address:private] => google_maps
                )

            [1] => Geocoder\Provider\GoogleMaps\Model\GoogleAddress Object
                (
                    [id:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => ChIJx0Y8Qbnz2YkRrGVC7MdYpzo
                    [locationType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => APPROXIMATE
                    [resultType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Array
                        (
                            [0] => neighborhood
                            [1] => political
                        )

                    [formattedAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Downtown, Syracuse, NY, USA
                    [streetAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [intersection:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [political:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => United States
                    [colloquialArea:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [ward:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [neighborhood:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Downtown
                    [premise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subpremise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [naturalFeature:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [airport:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [park:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [pointOfInterest:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [establishment:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subLocalityLevels:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                )

                        )

                    [coordinates:Geocoder\Model\Address:private] => Geocoder\Model\Coordinates Object
                        (
                            [latitude:Geocoder\Model\Coordinates:private] => 43.0484643
                            [longitude:Geocoder\Model\Coordinates:private] => -76.1508385
                        )

                    [bounds:Geocoder\Model\Address:private] => Geocoder\Model\Bounds Object
                        (
                            [south:Geocoder\Model\Bounds:private] => 43.042166
                            [west:Geocoder\Model\Bounds:private] => -76.1583461
                            [north:Geocoder\Model\Bounds:private] => 43.054231
                            [east:Geocoder\Model\Bounds:private] => -76.1428463
                        )

                    [streetNumber:Geocoder\Model\Address:private] =>
                    [streetName:Geocoder\Model\Address:private] =>
                    [subLocality:Geocoder\Model\Address:private] =>
                    [locality:Geocoder\Model\Address:private] => Syracuse
                    [postalCode:Geocoder\Model\Address:private] =>
                    [adminLevels:Geocoder\Model\Address:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                    [1] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 1
                                            [name:Geocoder\Model\AdminLevel:private] => New York
                                            [code:Geocoder\Model\AdminLevel:private] => NY
                                        )

                                    [2] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 2
                                            [name:Geocoder\Model\AdminLevel:private] => Onondaga County
                                            [code:Geocoder\Model\AdminLevel:private] => Onondaga County
                                        )

                                )

                        )

                    [country:Geocoder\Model\Address:private] => Geocoder\Model\Country Object
                        (
                            [name:Geocoder\Model\Country:private] => United States
                            [code:Geocoder\Model\Country:private] => US
                        )

                    [timezone:Geocoder\Model\Address:private] =>
                    [providedBy:Geocoder\Model\Address:private] => google_maps
                )

            [2] => Geocoder\Provider\GoogleMaps\Model\GoogleAddress Object
                (
                    [id:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => ChIJDZqXv5vz2YkRRZWt1-IM1QA
                    [locationType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => APPROXIMATE
                    [resultType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Array
                        (
                            [0] => locality
                            [1] => political
                        )

                    [formattedAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Syracuse, NY, USA
                    [streetAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [intersection:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [political:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => United States
                    [colloquialArea:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [ward:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [neighborhood:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [premise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subpremise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [naturalFeature:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [airport:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [park:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [pointOfInterest:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [establishment:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subLocalityLevels:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                )

                        )

                    [coordinates:Geocoder\Model\Address:private] => Geocoder\Model\Coordinates Object
                        (
                            [latitude:Geocoder\Model\Coordinates:private] => 43.0481221
                            [longitude:Geocoder\Model\Coordinates:private] => -76.1474244
                        )

                    [bounds:Geocoder\Model\Address:private] => Geocoder\Model\Bounds Object
                        (
                            [south:Geocoder\Model\Bounds:private] => 42.984366
                            [west:Geocoder\Model\Bounds:private] => -76.204476
                            [north:Geocoder\Model\Bounds:private] => 43.0861018
                            [east:Geocoder\Model\Bounds:private] => -76.0740841
                        )

                    [streetNumber:Geocoder\Model\Address:private] =>
                    [streetName:Geocoder\Model\Address:private] =>
                    [subLocality:Geocoder\Model\Address:private] =>
                    [locality:Geocoder\Model\Address:private] => Syracuse
                    [postalCode:Geocoder\Model\Address:private] =>
                    [adminLevels:Geocoder\Model\Address:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                    [1] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 1
                                            [name:Geocoder\Model\AdminLevel:private] => New York
                                            [code:Geocoder\Model\AdminLevel:private] => NY
                                        )

                                    [2] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 2
                                            [name:Geocoder\Model\AdminLevel:private] => Onondaga County
                                            [code:Geocoder\Model\AdminLevel:private] => Onondaga County
                                        )

                                )

                        )

                    [country:Geocoder\Model\Address:private] => Geocoder\Model\Country Object
                        (
                            [name:Geocoder\Model\Country:private] => United States
                            [code:Geocoder\Model\Country:private] => US
                        )

                    [timezone:Geocoder\Model\Address:private] =>
                    [providedBy:Geocoder\Model\Address:private] => google_maps
                )

            [3] => Geocoder\Provider\GoogleMaps\Model\GoogleAddress Object
                (
                    [id:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => ChIJXX3gEb7z2YkRrJj_0-rmXOQ
                    [locationType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => APPROXIMATE
                    [resultType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Array
                        (
                            [0] => postal_code
                        )

                    [formattedAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Syracuse, NY 13202, USA
                    [streetAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [intersection:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [political:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => United States
                    [colloquialArea:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [ward:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [neighborhood:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [premise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subpremise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [naturalFeature:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [airport:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [park:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [pointOfInterest:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [establishment:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subLocalityLevels:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                )

                        )

                    [coordinates:Geocoder\Model\Address:private] => Geocoder\Model\Coordinates Object
                        (
                            [latitude:Geocoder\Model\Coordinates:private] => 43.0481645
                            [longitude:Geocoder\Model\Coordinates:private] => -76.1473156
                        )

                    [bounds:Geocoder\Model\Address:private] => Geocoder\Model\Bounds Object
                        (
                            [south:Geocoder\Model\Bounds:private] => 43.030467
                            [west:Geocoder\Model\Bounds:private] => -76.163988
                            [north:Geocoder\Model\Bounds:private] => 43.0564569
                            [east:Geocoder\Model\Bounds:private] => -76.1420219
                        )

                    [streetNumber:Geocoder\Model\Address:private] =>
                    [streetName:Geocoder\Model\Address:private] =>
                    [subLocality:Geocoder\Model\Address:private] =>
                    [locality:Geocoder\Model\Address:private] => Syracuse
                    [postalCode:Geocoder\Model\Address:private] => 13202
                    [adminLevels:Geocoder\Model\Address:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                    [1] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 1
                                            [name:Geocoder\Model\AdminLevel:private] => New York
                                            [code:Geocoder\Model\AdminLevel:private] => NY
                                        )

                                    [2] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 2
                                            [name:Geocoder\Model\AdminLevel:private] => Onondaga County
                                            [code:Geocoder\Model\AdminLevel:private] => Onondaga County
                                        )

                                )

                        )

                    [country:Geocoder\Model\Address:private] => Geocoder\Model\Country Object
                        (
                            [name:Geocoder\Model\Country:private] => United States
                            [code:Geocoder\Model\Country:private] => US
                        )

                    [timezone:Geocoder\Model\Address:private] =>
                    [providedBy:Geocoder\Model\Address:private] => google_maps
                )

            [4] => Geocoder\Provider\GoogleMaps\Model\GoogleAddress Object
                (
                    [id:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => ChIJNf-jRf702YkRWbJ48qyiSrI
                    [locationType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => APPROXIMATE
                    [resultType:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Array
                        (
                            [0] => administrative_area_level_2
                            [1] => political
                        )

                    [formattedAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Onondaga County, NY, USA
                    [streetAddress:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [intersection:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [political:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => United States
                    [colloquialArea:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [ward:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [neighborhood:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [premise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subpremise:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [naturalFeature:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => 
                    [airport:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [park:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [pointOfInterest:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [establishment:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] =>
                    [subLocalityLevels:Geocoder\Provider\GoogleMaps\Model\GoogleAddress:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                )

                        )

                    [coordinates:Geocoder\Model\Address:private] => Geocoder\Model\Coordinates Object
                        (
                            [latitude:Geocoder\Model\Coordinates:private] => 43.026819
                            [longitude:Geocoder\Model\Coordinates:private] => -76.1783739
                        )

                    [bounds:Geocoder\Model\Address:private] => Geocoder\Model\Bounds Object
                        (
                            [south:Geocoder\Model\Bounds:private] => 42.7712569
                            [west:Geocoder\Model\Bounds:private] => -76.499324
                            [north:Geocoder\Model\Bounds:private] => 43.271605
                            [east:Geocoder\Model\Bounds:private] => -75.8960789
                        )

                    [streetNumber:Geocoder\Model\Address:private] =>
                    [streetName:Geocoder\Model\Address:private] =>
                    [subLocality:Geocoder\Model\Address:private] =>
                    [locality:Geocoder\Model\Address:private] =>
                    [postalCode:Geocoder\Model\Address:private] =>
                    [adminLevels:Geocoder\Model\Address:private] => Geocoder\Model\AdminLevelCollection Object
                        (
                            [adminLevels:Geocoder\Model\AdminLevelCollection:private] => Array
                                (
                                    [1] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 1
                                            [name:Geocoder\Model\AdminLevel:private] => New York
                                            [code:Geocoder\Model\AdminLevel:private] => NY
                                        )

                                    [2] => Geocoder\Model\AdminLevel Object
                                        (
                                            [level:Geocoder\Model\AdminLevel:private] => 2
                                            [name:Geocoder\Model\AdminLevel:private] => Onondaga County
                                            [code:Geocoder\Model\AdminLevel:private] => Onondaga County
                                        )

                                )

                        )

                    [country:Geocoder\Model\Address:private] => Geocoder\Model\Country Object
                        (
                            [name:Geocoder\Model\Country:private] => United States
                            [code:Geocoder\Model\Country:private] => US
                        )

                    [timezone:Geocoder\Model\Address:private] =>
                    [providedBy:Geocoder\Model\Address:private] => google_maps
                )

        )

)`

**Comment by Nyholm** [comment]
Sure. Have a look at our dumpers: https://github.com/geocoder-php/Geocoder#dumpers

**Comment by juragandotid** [comment]
`require_once('vendor/autoload.php');

use Geocoder\Query\GeocodeQuery;
use Geocoder\Query\ReverseQuery;

$httpClient = new \Http\Adapter\Guzzle6\Client();
$provider = new \Geocoder\Provider\GoogleMaps\GoogleMaps($httpClient);
$geocoder = new \Geocoder\StatefulGeocoder($provider, 'en');

$result = $geocoder->reverseQuery(ReverseQuery::fromCoordinates('43.0481','-76.1474'));

$dumper = new \Geocoder\Dumper\Gpx();
$strGpx = $dumper->dump($result);

echo $strGpx;`


igot an error : 

'PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Geocoder\Dumper\Gpx::dump() must implement interface Geocoder\Location, instance of Geocoder\Model\AddressCollection given, called in F:\geocoder\tester.php on line 15 and defined in F:\geocoder\vendor\willdurand\geocoder\Dumper\Gpx.php:28
Stack trace:
#0 F:\geocoder\tester.php(15): Geocoder\Dumper\Gpx->dump(Object(Geocoder\Model\AddressCollection))
#1 {main}
  thrown in F:\geocoder\vendor\willdurand\geocoder\Dumper\Gpx.php on line 28

Fatal error: Uncaught TypeError: Argument 1 passed to Geocoder\Dumper\Gpx::dump() must implement interface Geocoder\Location, instance of Geocoder\Model\AddressCollection given, called in F:\geocoder\tester.php on line 15 and defined in F:\geocoder\vendor\willdurand\geocoder\Dumper\Gpx.php:28
Stack trace:
#0 F:\geocoder\tester.php(15): Geocoder\Dumper\Gpx->dump(Object(Geocoder\Model\AddressCollection))
#1 {main}
  thrown in F:\geocoder\vendor\willdurand\geocoder\Dumper\Gpx.php on line 28'

**Comment by Nyholm** [comment]
Could you please use words instead of non formatted code?

**Comment by jbelien** [comment]
Hello @juragandotid ,

First of all, could you have a look at ["Mastering Markdown" guide](https://guides.github.com/features/mastering-markdown/) to display pieces of code the right way.
Then please do not copy paste such a huge amount of code, it's useless. Try to only copy-paste the useful information.

I'll have a look at your issue.

**Comment by juragandotid** [comment]
@jbelien i wanna parse this response 
using dumper `["formattedAddress":"Geocoder\Provider\GoogleMaps\Model\GoogleAddress":private]=>
      string(23) "Syracuse, NY 13202, USA"`

could you give me example please..

Thank you.

**Comment by jbelien** [comment]
As you can see in the error message *Argument 1 passed to Geocoder\Dumper\Gpx::dump() must implement interface Geocoder\Location, null given*, you have to send a *Location* to `Gpx::dump()` function.

In your example, you send a `reverseQuery()` result (and on top of that, the result is apparently `null` in your case).

So, you have to go through every result (or use `$results->first()` to have the first result) and send **that** to `Gpx::dump()` !
