### ISSUE TITLE
Street number / Premise

### ISSUE THREAD

**Issue by landsman** [geocoder-php/Geocoder#863]
Hi, on my address I am getting null for getStreetNumber() but there is privated key "premise" with the right value of street number but without getter. Why?

Thanks

**Comment by Nyholm** [comment]
Hey. 
What provider are we talking about?

**Comment by jbelien** [comment]
Hello @landsman ,

Did you find a solution to your issue ?

Thanks.

**Comment by Nyholm** [comment]
Closing due inactivity.
