### ISSUE TITLE
Cannot get city

### ISSUE THREAD

**Issue by juragandotid** [geocoder-php/Geocoder#877]
Could not get city providers google maps, i think null or problem. Please review

this is my script : 
```
$getLatitude = $record->latitude;
$getLongitude = $record->longitude;

$result = $geocoder->reverseQuery(ReverseQuery::fromCoordinates($getLatitude,$getLongitude));

$number = $result->first()->getStreetNumber();
$street = $result->first()->getStreetName();
$subcity = $result->first()->getSubLocality();
$city = $result->first()->getLocality();
$state = $GEOIP_REGION_NAME[$record->country_code][$record->region];
$postalcode = $result->first()->getPostalCode();
$country = $result->first()->getCountry();
$timezone = $result->first()->getTimezone();

print "Result : " . $number. " " .$street. " " .$city. " " .$state. " " .$postalcode. " " .$country. " " .$timezone. "\r\n";
```

Please check my script my be i'm typo.

Thank You.

**Comment by Nyholm** [comment]
Maybe your coordinates is is not near a city =)

**Comment by jbelien** [comment]
Could give us the coordinates and the result of the `reverseQuery()` function ?
Thanks :)

**Comment by juragandotid** [comment]
@jbelien this is my cordinate Lat : -6.1744, Lon: 106.8294.
and this is the response : `Result :  Jalan Titian Indah  Jakarta Raya 10110 Indonesia`

**Comment by juragandotid** [comment]
@Nyholm i think this is have response full address number , address name , sublocalcity, city , state , postalcode, country. But the response only get address number, address name, state , postalcode, country.

this is url google maps with my example cordinate : 
`http://maps.googleapis.com/maps/api/geocode/json?latlng=-7.2492,112.7508&sensor=true`

The response : 
`{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "2",
               "short_name" : "2",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Jalan Ngaglik",
               "short_name" : "Jl. Ngaglik",
               "types" : [ "route" ]
            },
            {
               "long_name" : "014",
               "short_name" : "014",
               "types" : [ "political" ]
            },
            {
               "long_name" : "05",
               "short_name" : "05",
               "types" : [ "political" ]
            },
            {
               "long_name" : "Kapasari",
               "short_name" : "Kapasari",
               "types" : [ "administrative_area_level_4", "political" ]
            },
            {
               "long_name" : "Genteng",
               "short_name" : "Genteng",
               "types" : [ "administrative_area_level_3", "political" ]
            },
            {
               "long_name" : "Kota Surabaya",
               "short_name" : "Kota SBY",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Jawa Timur",
               "short_name" : "Jawa Timur",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Indonesia",
               "short_name" : "ID",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "60273",
               "short_name" : "60273",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "Jl. Ngaglik No.2, RT.014/RW.05, Kapasari, Genteng, Kota SBY, Jawa Timur 60273, Indonesia",
         "geometry" : {
            "location" : {
               "lat" : -7.2491079,
               "lng" : 112.7508449
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : -7.247758919708498,
                  "lng" : 112.7521938802915
               },
               "southwest" : {
                  "lat" : -7.250456880291503,
                  "lng" : 112.7494959197085
               }
            }
         },
         "place_id" : "ChIJ3-XpgG351y0RmVYfvuIg_hw",
         "types" : [ "street_address" ]
      }
   ],
   "status" : "OK"
}`

Could You fix them, mybe you check again any mistack on this source.

Thank You.

**Comment by jbelien** [comment]
Hello @juragandotid ,

Any news about your issue ?

Thanks.

**Comment by Nyholm** [comment]
Closing due inactivity. 

Thank you @jbelien
