### ISSUE TITLE
Get type (and other privates) from nominatim

### ISSUE THREAD

**Issue by Yamakasi** [geocoder-php/Geocoder#891]
I wonder if there is a way to get the type property from the address object and also the other info which is in a nominatim response object (and maybe others as well).

**Comment by jbelien** [comment]
Hello,

You can get the `type` property with [`getType()` function](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/Nominatim/Model/NominatimAddress.php#L160).
You can see all the properties available in [`Model/NominatimAddress.php`](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/Nominatim/Model/NominatimAddress.php).

**Comment by Yamakasi** [comment]
Hi,

Thanks! I would have believed the same but I don't get the options on an Address object so I got confused. I already fiddeled a little but with the code to see why. Can you give a small example maybe ? I can do a toArray() and such, getProvidedBy()...

**Comment by jbelien** [comment]
I don't have time to investigate this right now but I'll do it ASAP :)

**Comment by Yamakasi** [comment]
Thanks, I'm testing also using the Nominatim tests from the repo, let me know if you find something.

Should it work with registering the provider as well ?

**Comment by jbelien** [comment]
Hello again @Yamakasi ,

I checked and there is nothing wrong, as expected you can get the `type` property with [`getType()` function](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/Nominatim/Model/NominatimAddress.php#L160).

Here is an example :
```
use Geocoder\Query\GeocodeQuery;

$httpClient = new \Http\Adapter\Guzzle6\Client();
$provider = \Geocoder\Provider\Nominatim\Nominatim::withOpenStreetMapServer($httpClient, $_SERVER['HTTP_USER_AGENT']);
$geocoder = new \Geocoder\StatefulGeocoder($provider, 'en');

$result = $geocoder->geocodeQuery(GeocodeQuery::create('Buckingham Palace, London'));

echo $result->first()->getType();
```

**Comment by Nyholm** [comment]
Thank you @jbelien. 
I see that you solved this issue.
