### ISSUE TITLE
[HostIp Provider] Doesn't work with docker localhost

### ISSUE THREAD

**Issue by bazo** [geocoder-php/Geocoder#892]
Hi,

i upgraded today from version 3.3.2 of geocoder to the new version
and i was surprised that suddenly the geocoding stopped working on localhost

as i am running on docker my ip is not 127.0.0.1

the service api.hostip.info returns data like Private address, country XX which the old version processed ok and all was working as expected.

The new version checks for this and doesn't return an address which results in exception

Deleting the check for private address restored the functionality

I don't think it makes sense to artificially remove the result if the online service returns data

More and more developers are using docker so this version will stop working for them

**Comment by jbelien** [comment]
Hello @bazo ,

I'm a bit confused here (and I never used HostIP provider myself).

If I compare current version of HostIP provider ([HostIpTest.php#L44](https://github.com/geocoder-php/Geocoder/blob/master/src/Provider/HostIp/Tests/HostIpTest.php#L44)) with Geocoder 3.x version of HostIp provider ([HostIpTest.php#L46](https://github.com/geocoder-php/Geocoder/blob/3.x/tests/Geocoder/Tests/Provider/HostIpTest.php#L46)) it seems to have the same test for `localhost` with `127.0.0.1`.

Could you develop a bit more about your issue ?

Thanks a lot !

**Comment by atymic** [comment]
@bazo 
Did you manage to solve your issue?

**Comment by atymic** [comment]
@jbelien 
I think this can be closed now :)
