### ISSUE TITLE
Cache and providers Terms of service

### ISSUE THREAD

**Issue by sheub** [geocoder-php/Geocoder#893]
I just would like to get your thought on this:
Some providers (e.g. I know [mapbox](https://www.mapbox.com/tos/#[YmouYmoq])) have a strict policy and doesn't allow to cache Geocodes.
Isn't it an infraction to use the caching feature of Geocoder-php together with such a provider?

Hereafter the § of Mapbox Terms of service.
> You may only use responses from the Geocoding API ("Geocodes") in conjunction with a Mapbox map. You may not export, store or cache Geocodes. You may not resell or re-syndicate Geocodes to other publishers or third parties (except to your end users or as an integrated part of your application). You may use latitude and longitude information from Geocodes to position results on a map, but you may not display the latitudes or longitudes directly to end users. You may only query the Geocoding API in response to human user queries and human app interactions; you may not perform bulk or automated queries.

**Comment by Nyholm** [comment]
>  Isn't it an infraction to use the caching feature of Geocoder-php together with such a provider?

You are correct. You should not use the caching features with those providers.
