### ISSUE TITLE
No message factories found. To use Guzzle, Diactoros or Slim Framework factories install php-http/message and the chosen message implementation

### ISSUE THREAD

**Issue by garak** [geocoder-php/Geocoder#894]
I'm getting such error when trying to instantiate `GoogleMaps`.
It looks like there's no way to pass a MessageFactory to it, and sadly MessageFactoryDiscovery is failing here.
I'm pretty sure that I'm doing something wrong and this is more a support request than a bug report.

Here is the super crazy part: if I install dev requirement, it works. If I don't (like in production), it fails.

thanks in advance

**Comment by jbelien** [comment]
Hello @garak ,

Did you install `php-http/message` as specified in the [`README` file](https://github.com/geocoder-php/Geocoder/blob/master/README.md#summary-just-give-me-the-command) ?

You will need `php-http/guzzle6-adapter` and `php-http/message` on top of the Google Maps provider to make it work :

```
composer require geocoder-php/google-maps-provider php-http/guzzle6-adapter php-http/message
```

**Comment by garak** [comment]
Thanks for your reply. I already installed all required packages

**Comment by garak** [comment]
Opened an issue on https://github.com/php-http/discovery/issues/114

**Comment by garak** [comment]
As explained in mentioned issue, I solved by replacing Buzz with Guzzle.
Thanks anyway.
