### ISSUE TITLE
Provider GoogleMapsBusiness is missing channel query key

### ISSUE THREAD

**Issue by aamalain** [geocoder-php/Geocoder#895]
Provider GoogleMapsBusiness should accept "channel" attribute in __construct and use it in buildQuery

**Comment by jbelien** [comment]
Hello @aamalain ,

I'm not familiar with Google Map Business.
Could you give us a bit more information and documentation about this `channel` key ?

Thanks a lot.

**Comment by aamalain** [comment]
The channel query string param is used only for analytics. For example, if you use the same account on multiple domains, the channel might contain the domain name.

Here is some documentation about it:
https://developers.google.com/maps/premium/reports/usage-reports#channels

The URL will be like: 
https://maps.googleapis.com/maps/api/js?v=3
&client=gme-yourclientid
&signature=your_signature
&channel=your_channel

**Comment by jbelien** [comment]
Understood.
I guess it's an optional parameter, right ?

I'll try to find some time to add it in the [Google Maps Geocoder provider](https://github.com/geocoder-php/google-maps-provider) ! 👍

**Comment by aamalain** [comment]
yes, it is optional

**Comment by maxhelias** [comment]
You have already this feature [here](https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php#L169)

Use it like this : `GoogleMaps::business($client, $clientId, $privateKey, $region, $apiKey, $channel)` :wink:

**Comment by jbelien** [comment]
Even better, thanks @maxhelias ! 🎉
