### ISSUE TITLE
provider package for php 5.6

### ISSUE THREAD

**Issue by cleoni** [geocoder-php/Geocoder#897]
Hello,
I am trying to make version 4 to work on a server using 5.6 for legacy needs.

Is there any geocode provider package working on php5 with geocoder 4?

**Comment by jbelien** [comment]
Hello @cleoni ,

Unfortunately, as stated in the [`CHANGELOG.md`](https://github.com/geocoder-php/Geocoder/blob/4.0.0/CHANGELOG.md), we drop the support for PHP < 7.0 with the release of version 4.0 !
