### ISSUE TITLE
How to use the logger

### ISSUE THREAD

**Issue by simonschaufi** [geocoder-php/Geocoder#901]
Hi, I'm using your package with a proxy package https://github.com/geocoder-php/GeocoderLaravel.

I would like to log the Exception thrown here:

https://github.com/geocoder-php/Geocoder/blob/1bd7d59a6725586158d4aae121c23195334cf842/src/Provider/Chain/Chain.php#L123-L128

but I have no clue how to inject a logger. I also didn't find anything in the documentation. Could you please help?

**Comment by atymic** [comment]
@simonschaufi 
Did you get this solved?

**Comment by atymic** [comment]
@jbelien 
I think this can be closed now :)
