### ISSUE TITLE
Having trouble committing to git because of submodules

### ISSUE THREAD

**Issue by onassar** [geocoder-php/Geocoder#913]
I'm getting a bunch of strange submodules errors after running composer against `v4.0.0`. Is there a recommended way of using this library with a repo that's inside of git?

**Comment by Nyholm** [comment]
Have you read the docs? 
https://github.com/geocoder-php/Geocoder#summary-just-give-me-the-command

**Comment by onassar** [comment]
Ahh, I ran `composer install` agains the downloaded release, but when I just ran `composer require willdurand/geocoder` it ran okay :)

**Comment by Nyholm** [comment]
Im happy you got it working
