### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by Carlsans** [geocoder-php/Geocoder#932]
Hi, I'm using a remote server over wish I have no control. I can't use composer nor ask any command to the Apaches server. Is there any way I can get around the installation with Composer ?

**Comment by atymic** [comment]
> Another idea is to build everything locally and then upload the whole thing on your remote server.

@Carlsans 
This is probably the easiest approach.
Did you get the issue solved?

**Comment by atymic** [comment]
@jbelien 
I think this can be closed now :)
