### ISSUE TITLE
Add 2GIS Provider

### ISSUE THREAD

**Issue by vassilaros** [geocoder-php/Geocoder#935]
Is it impossible to add 2GIS provider? (https://2gis.com.cy)

**Comment by vassilaros** [comment]
I found these websites which are in Russian and I do not understand (one is in English). But it has information about their API. 
http://api.2gis.ae/
https://github.com/2gis/mapsapi
https://habr.com/ru/company/2gis/blog/229097/
https://www.npmjs.com/package/2gis-api

I have no more information about api!

**Comment by jbelien** [comment]
Thanks @vassilaros ! I had a look at the links you posted. I see documentation about their JavaScript library to "display a map" but no documentation about the REST/SOAP/? API for geocoding !

**Comment by vassilaros** [comment]
Maybe this helps?
http://tile1.maps.2gis.com/tiles?x={x}&y={y}&z={z}

**Comment by jbelien** [comment]
> Maybe this helps?
> http://tile1.maps.2gis.com/tiles?x={x}&y={y}&z={z}

No, sorry, that's the tiles : the image of the map.
I made some research, the "geocoding" API seems to be `https://catalog.api.2gis.ru/`.
Found (at least) those 2 functions:
- `https://catalog.api.2gis.ru/3.0/suggest/global/list`
- `https://catalog.api.2gis.ru/2.0/geo/get`
But I didn't find any documentation on this...

Maybe you could try to contact them ?

**Comment by atymic** [comment]
@vassilaros 
Did you manage to get any more information?
Maybe this would be better as a community provider rather than an official one

**Comment by atymic** [comment]
I'm going to close this due to inactivity. 
Feel free to ping one of us and we'll reopen.
