### ISSUE TITLE
[Google Maps] API access denied

### ISSUE THREAD

**Issue by AlifAbhiesa** [geocoder-php/Geocoder#941]
![image](https://user-images.githubusercontent.com/27193997/54836165-44b6b080-4cf6-11e9-9a10-0097cf5db064.png)
Where i must placed the API KEY for google maps?
because when i try manually it's working, like this
![image](https://user-images.githubusercontent.com/27193997/54836298-834c6b00-4cf6-11e9-860a-f6f62b2d9555.png)

**Comment by AlifAbhiesa** [comment]
And i already placed my API KEY in here, but still doesn't work

![image](https://user-images.githubusercontent.com/27193997/54837113-3073b300-4cf8-11e9-888a-9a35e367ab76.png)

**Comment by jbelien** [comment]
Hello @AlifAbhiesa ,

Have a look at the constructor : https://github.com/geocoder-php/google-maps-provider/blob/master/GoogleMaps.php#L97
You'll see that the last parameter is your key.

So it should be something like this:

```php
new GoogleMaps($client, null, 'myApiKey');
```

**Comment by atymic** [comment]
@AlifAbhiesa 
Did you get this resolved?

**Comment by AlifAbhiesa** [comment]
i put the key manually on this function

![image](https://user-images.githubusercontent.com/27193997/58608559-4c826a80-82ce-11e9-9cf1-f516c998c6f9.png)

on this file

![image](https://user-images.githubusercontent.com/27193997/58608570-5e640d80-82ce-11e9-8118-43839af7114d.png)

FYI : i'm using composer

**Comment by atymic** [comment]
@AlifAbhiesa 

You should not modify parts of the library, could you post the code you are using to do the geocode?
You should just be using something like this:

```
use Geocoder\Query\GeocodeQuery;
use Geocoder\Query\ReverseQuery;

$httpClient = new \Http\Adapter\Guzzle6\Client();
$provider = new \Geocoder\Provider\GoogleMaps\GoogleMaps($httpClient, 'YOURAPIKEYHERE');
$geocoder = new \Geocoder\StatefulGeocoder($provider, 'en');

$result = $geocoder->geocodeQuery(GeocodeQuery::create('Buckingham Palace, London'));
```

Note where I put `YOURAPIKEYHERE`, instead use your API there.

**Comment by AlifAbhiesa** [comment]
Thank you @atymic it's work for me ;)

**Comment by atymic** [comment]
No worries :smile:

**Comment by jbelien** [comment]
Haha I'm a bit confused here, that's exactly what I said [here](https://github.com/geocoder-php/Geocoder/issues/941#issuecomment-475792737). 😋 

The good new is that it's "fixed" ! 🎉
