### ISSUE TITLE
What is the domain are of this project?

### ISSUE THREAD

**Issue by gnumoksha** [geocoder-php/Geocoder#951]
Hi. I'm a bit confused about the domain area of this project. Is this related to geocoding only?

Quoting [google maps docs](https://developers.google.com/maps/documentation/geocoding/start):

> Geocoding is the process of converting addresses (like a street address) into geographic coordinates (like latitude and longitude), which you can use to place markers on a map, or position the map.
> 
> Reverse geocoding is the process of converting geographic coordinates into a human-readable address.

Just to be clear, I need to enrich address data received from many different resources and I've found geocoding providers are designed for unambiguous address. Do all providers have this same rule?

**Comment by jbelien** [comment]
From the README:
> Geocoder is a PHP library which helps you build geo-aware applications by providing a powerful abstraction layer for geocoding manipulations.

This library provides an easy way to query plenty of geocoding providers. Each geocoding provider has its own rules !
We provide a structured way to query every provider the same way and the result is also always structured the same way no matter what geocoding provider you chose.

Geocoder library includes geocoding, reverse geocoding but also "IP geocoding".

**Comment by gnumoksha** [comment]
> This library provides an easy way to query plenty of geocoding providers. Each geocoding provider has its own rules !

I've quoted Google's definition of Geocoding but in fact, this is the global definition of Geocoding (see [Wikipedia](https://en.wikipedia.org/wiki/Geocoding))

> We provide a structured way to query every provider the same way and the result is also always structured the same way no matter what geocoding provider you chose.
> 
> Geocoder library includes geocoding, reverse geocoding but also "IP geocoding".

Right. What I'm saying is to clarify what this result would be. Besides Google Maps, the [Here](https://github.com/geocoder-php/here-provider) provider is also using geocoding and the [nominatim](https://github.com/geocoder-php/nominatim-provider) provider uses address + geocoding.

I'm saying all this because for many people the concept of "geocoding" is unclear. The fact of one need a nonambiguous address to search an address using geocoding is an issue that the README can clarify too. For example, I came to this issue with the geocoding definition because of my team at work had thought it was ok to search ambiguous address using geocoding, when in fact, it resulted in poor results.results.

**Comment by jbelien** [comment]
> Right. What I'm saying is to clarify what this result would be. Besides Google Maps, the Here provider is also using geocoding and the nominatim provider uses address + geocoding.

I don't get this.

For the addresses, the Geocoder library only provides geocoding (= converting an address into geographic coordinates) and reverse geocoding (= converting geographic coordinates into an address) !
Those 2 functionalities are based on external API and we, of course, do not have any control on how the external API process the address (or the geographic coordinates).

Each external API will process a ambiguous address its own way, that's out of this library scope and goal.

**Comment by gnumoksha** [comment]
I agree with what you said, my only concern here is explicit what geocoding is supposed to do.

I am going to close this issue and leave the PR for you to do what you think is best.
