### ISSUE TITLE
Algolia places provider is not working anymore

### ISSUE THREAD

**Issue by jkobus** [geocoder-php/Geocoder#960]
Algolia Places response structure changed, therefore the provider is not working anymore. 
Algolia added localized names (client expects value but it instead sees another array):
https://community.algolia.com/places/api-clients.html#json-answer

Algolia is also missing its factory.

**Comment by jbelien** [comment]
Thanks for the notice @jkobus !

Would you have some time to provide a PR ?

**Comment by jkobus** [comment]
In a spare time, sure. Todo:

- add factory (should it be in the main repository?)
- fix bug in provider 
- add or update documentation

**Comment by jbelien** [comment]
Ping @Fabex the original author of Algolia Places provider !

**Comment by atymic** [comment]
Happy to jump on this when I have some time if required :)

**Comment by atymic** [comment]
I've opened a PR.
@jkobus what do you mean by adding a factory?

**Comment by jbelien** [comment]
New release is published: https://packagist.org/packages/geocoder-php/algolia-places-provider 🎉

**Comment by jkobus** [comment]
@atymic factory is for the symfony bundle (https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/index.md#usage), although it is possible to use the geocoder provider without it.
