### ISSUE TITLE
Deprecating Shutdown Providers

### ISSUE THREAD

**Issue by atymic** [geocoder-php/Geocoder#965]
Since the provider has been shut down for over a year, should we consider deprecating it?
http://freegeoip.net/shutdown

Maybe it would be a good idea to come up with a policy for handling provider shutdowns.

Possible steps:
- Mark packagist package as abandoned
- adding `@deprecated` annotations to the class & constructor (which will warn people using IDEs)
- Remove provider from main README
- Update provider README to indicate it's deprecation
- Skip/Remove tests (maybe)?

**Comment by atymic** [comment]
Also seems that the [GeoIps Provider](https://github.com/geocoder-php/geoips-provider) has shut down as well.

**Comment by jbelien** [comment]
Seems like a good idea to "clean" the providers that can't be used anymore.

If some providers can be replaced by another one, we should state it (like Mapzen > GeocodeEarth, FreeGeoIp > Ipstack).

What do you think about this @willdurand @Nyholm ? :)

**Comment by atymic** [comment]
> If some providers can be replaced by another one, we should state it (like Mapzen > GeocodeEarth, FreeGeoIp > Ipstack).

Good idea.
Might be a good idea to add that in the README of the deprecated package.

**Comment by atymic** [comment]
I have opened a PR in #972 😄
