### ISSUE TITLE
[MaxMindBinary] Issue with geoip 1.1.1

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#983]
Don't have time to have a deeper look at it now but maybe someone knows how to fix this.
There is an issue in the `PHP 7.3 deps="low"` and `PHP 7.3 deps="high"` builds (see https://travis-ci.org/geocoder-php/Geocoder/builds/561973179)

```
Problem 1
    - Installation request for ext-geoip 1.1.1 -> satisfiable by ext-geoip[1.1.1].
    - geoip/geoip v1.17 conflicts with ext-geoip[1.1.1].
    - Installation request for geoip/geoip ^1.17 -> satisfiable by geoip/geoip[v1.17].
```

**Comment by jbelien** [comment]
Damn that's blocking all the PR at the moment! 😭 

I'll try to find some time to check ! @Nyholm any idea why it happens for `deps="low"` and `deps="high"` only ?

**Comment by atymic** [comment]
Look like it's failing because only the low/high deps try to use the geoip extensions: 
```
echo "$COMPONENTS" | parallel --gnu -j10% "tfold {} 'cd {} && $GEOIP_EXT && $COMPOSER_UP && $PHPUNIT_X$LEGACY'"
```

**Comment by atymic** [comment]
And the reason it's failing is because `geoip/geoip` requires the extension NOT to be installed:
https://github.com/maxmind/geoip-api-php/blob/master/composer.json
```
"conflict": {
    "ext-geoip": "*"
},
```

**Comment by atymic** [comment]
PR open in #985 :)

**Comment by jbelien** [comment]
Awesome!
Nice catch @atymic 👍

**Comment by atymic** [comment]
No worries :)
