### ISSUE TITLE
Yandex Provider ApiKey

### ISSUE THREAD

**Issue by romec512** [geocoder-php/Geocoder#987]
Hello. Yandex geocoder api requires api key now. Can you add this feature?
[from](https://yandex.ru/blog/mapsapi/novye-pravila-dostupa-k-api-kart?from=tech_pp)

**Comment by atymic** [comment]
Happy to jump on this one. Will have a look at the docs today.

**Comment by atymic** [comment]
PR open in #988.

**Comment by jbelien** [comment]
New release is live: https://packagist.org/packages/geocoder-php/yandex-provider 🍾
