### ISSUE TITLE
Create missing sub-packages

### ISSUE THREAD

**Issue by jbelien** [geocoder-php/Geocoder#996]
@Nyholm Could you create the 2 missing sub-packages ?

- [ ] [GeocodeEarth](https://github.com/geocoder-php/Geocoder/tree/master/src/Provider/GeocodeEarth)
- [ ] [GoogleMapsPlaces](https://github.com/geocoder-php/Geocoder/tree/master/src/Provider/GoogleMapsPlaces)

Tack så mycket!

PS: I don't seem to be able to contact you via Twitter messages.

**Comment by Nyholm** [comment]
Hey. Sorry. It is just me being uncontactable for the past month or two. I'll create the packages now!

**Comment by jbelien** [comment]
Haha, no worries!

Thanks a lot 🎉

**Comment by Nyholm** [comment]
So, what I just did:
- I created new repositories
- I've update subtreesplit.com to map the path and repositories
- I activated Travis
- I made a PR to push to the new packages (#1000). When that was merged subtreesplit pushed to  the new repos. 
- I activated Scrutinizer
- I added the new package on Packagist.

**Comment by atymic** [comment]
Great work @Nyholm 

That should make things easier going forward!
