### ISSUE TITLE
Make atymic an official maintainer

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#999]
Hey @atymic 

I create this issue just to message you. I could not find you email or Twitter. 

@jbelien and I think you have done some great work here for the past few months. We would be happy to have you on the team. 

There are basically only three rules: 
1) Follow Semver
2) Dont delete tags
3) Try to not merge your own PRs

**Comment by jbelien** [comment]
🎉🎉🎉 Welcom onboard @atymic ! 🎉🎉🎉

Thanks a lot for all the work these past few months!
Looking forward to work even more "closer" with you!

**Comment by atymic** [comment]
Hey @Nyholm!

Thanks for the invite, I'm honoured!
I'll make sure to follow those rules to the T.

Thanks for the welcome @jbelien :)

**Comment by atymic** [comment]
FYI I've created a twitter account if you need to contact me :)
https://twitter.com/atymic
